export const NBA_2023_Prospects = [
  {
    id: 100000,
    rank: 1,
    firstName: "Victor",
    lastName: "Wembanyama",
    position: "C",
    class: "",
    height: 88,
    weight: 230,
    ras: null,
    school: "France",
    img: "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse4.mm.bing.net%2Fth%3Fid%3DOIP.zEZ3iFrQNaEocKxY_dEEpQHaDt%26pid%3DApi&f=1&ipt=7649d7b424d25337483ab84ac6d5585885936168da7b3ccb50cf37c73791321d&ipo=images",
    desc: [],
    archetype: "",
    strengths: [],
    weaknesses: [],
  },
  {
    id: 1,
    rank: 2,
    firstName: "Scoot",
    lastName: "Henderson",
    position: "PG",
    class: "",
    height: 74,
    weight: 195,
    ras: null,
    school: "G-League Ignite",
    img: "https://www.nbadraft.net/wp-content/uploads/2021/04/Scoot-Henderson-2.png",
    desc: [],
    archetype: "",
    strengths: [],
    weaknesses: [],
  },
  {
    id: 2,
    rank: 3,
    firstName: "Brandon",
    lastName: "Miller",
    position: "SF",
    class: "Fr.",
    height: 81,
    weight: 200,
    ras: null,
    school: "Alabama",
    img: "https://a.espncdn.com/combiner/i?img=/i/headshots/mens-college-basketball/players/full/4433287.png",
    desc: [],
    archetype: "",
    strengths: [],
    weaknesses: [],
  },
  {
    id: 3,
    rank: 4,
    firstName: "Amen",
    lastName: "Thompson",
    position: "SF",
    class: "",
    height: 78,
    weight: 214,
    ras: null,
    school: "Overtime Elite",
    img: "https://res.cloudinary.com/djcqmdgda/image/upload/nba/prospects/headshots/106537.png",
    desc: [],
    archetype: "",
    strengths: [],
    weaknesses: [],
  },
  {
    id: 4,
    rank: 5,
    firstName: "Ausar",
    lastName: "Thompson",
    position: "SF",
    class: "",
    height: 78,
    weight: 218,
    ras: null,
    school: "Overtime Elite",
    img: "https://res.cloudinary.com/djcqmdgda/image/upload/nba/prospects/headshots/106537.png",
    desc: [],
    archetype: "",
    strengths: [],
    weaknesses: [],
  },
  {
    id: 5,
    rank: 6,
    firstName: "Jarrace",
    lastName: "Walker",
    position: "PF",
    class: "Fr.",
    height: 79,
    weight: 249,
    ras: null,
    school: "Houston",
    img: "https://www.papercitymag.com/wp-content/uploads/2022/05/Jarace_Walker_3-1200x800.jpeg",
    desc: [],
    archetype: "",
    strengths: [],
    weaknesses: [],
    },
    // {
    // id: 6,
    // rank: 7,

];
