export const NBA_2023_Prospects = [
  {
    id: 100000,
    rank: 1,
    firstName: "Victor",
    lastName: "Wembanyama",
    position: "C",
    class: "",
    height: 88,
    weight: 230,
    ras: null,
    school: "France",
    img: "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse4.mm.bing.net%2Fth%3Fid%3DOIP.zEZ3iFrQNaEocKxY_dEEpQHaDt%26pid%3DApi&f=1&ipt=7649d7b424d25337483ab84ac6d5585885936168da7b3ccb50cf37c73791321d&ipo=images",
    desc: [],
    archetype: "",
    strengths: [],
    weaknesses: [],
  },
  {
    id: 1,
    rank: 2,
    firstName: "Scoot",
    lastName: "Henderson",
    position: "PG",
    class: "",
    height: 74,
    weight: 195,
    ras: null,
    school: "G-League Ignite",
    img: "https://www.nbadraft.net/wp-content/uploads/2021/04/Scoot-Henderson-2.png",
    desc: [],
    archetype: "",
    strengths: [],
    weaknesses: [],
  },
  {
    id: 2,
    rank: 3,
    firstName: "Brandon",
    lastName: "Miller",
    position: "SF",
    class: "Fr.",
    height: 81,
    weight: 200,
    ras: null,
    school: "Alabama",
    img: "https://a.espncdn.com/combiner/i?img=/i/headshots/mens-college-basketball/players/full/4433287.png",
    desc: [],
    archetype: "",
    strengths: [],
    weaknesses: [],
  },
  {
    id: 3,
    rank: 4,
    firstName: "Amen",
    lastName: "Thompson",
    position: "SF",
    class: "",
    height: 78,
    weight: 214,
    ras: null,
    school: "Overtime Elite",
    img: "https://res.cloudinary.com/djcqmdgda/image/upload/nba/prospects/headshots/106537.png",
    desc: [],
    archetype: "",
    strengths: [],
    weaknesses: [],
  },
  {
    id: 4,
    rank: 5,
    firstName: "Ausar",
    lastName: "Thompson",
    position: "SF",
    class: "",
    height: 78,
    weight: 218,
    ras: null,
    school: "Overtime Elite",
    img: "https://res.cloudinary.com/djcqmdgda/image/upload/nba/prospects/headshots/106537.png",
    desc: [],
    archetype: "",
    strengths: [],
    weaknesses: [],
  },
  {
    id: 5,
    rank: 7,
    firstName: "Jarrace",
    lastName: "Walker",
    position: "PF",
    class: "Fr.",
    height: 79,
    weight: 249,
    ras: null,
    school: "Houston",
    img: "https://www.papercitymag.com/wp-content/uploads/2022/05/Jarace_Walker_3-1200x800.jpeg",
    desc: [],
    archetype: "",
    strengths: [],
    weaknesses: [],
    },
    {
    id: 6,
    rank: 6,
    firstName: "Cam",
    lastName: "Whitmore",
    position: "SF",
    class: "Fr.",
    height: 78,
    weight: 235,
    ras: null,
    school: "Villanova",
    img: "https://a.espncdn.com/i/headshots/mens-college-basketball/players/full/5105592.png",
    desc: [],
    archetype: "",
    strengths: [],
    weaknesses: [],
  },
  {
    id: 7,
    rank: 9,
    firstName: "Taylor",
    lastName: "Hendricks",
    position: "PF",
    class: "Fr.",
    height: 80,
    weight: 214,
    ras: null,
    school: "UCF",
    img: "https://res.cloudinary.com/djcqmdgda/image/upload/nba/prospects/headshots/4684806.png",
    desc: [],
    archetype: "",
    strengths: [],
    weaknesses: [],
  },
  {
    id: 8,
    rank: 8,
    firstName: "Anthony",
    lastName: "Black",
    position: "SG",
    class: "Fr.",
    height: 78,
    weight: 210,
    ras: null,
    school: "Arkansas",
    img: "https://a.espncdn.com/i/headshots/mens-college-basketball/players/full/5105516.png",
    desc: [],
    archetype: "",
    strengths: [],
    weaknesses: [],
  },
  {
    id: 9,
    rank: 11,
    firstName: "Gradey",
    lastName: "Dick",
    position: "SG",
    class: "Fr.",
    height: 78,
    weight: 204,
    ras: null,
    school: "Kansas",
    img: "https://a.espncdn.com/combiner/i?img=/i/headshots/mens-college-basketball/players/full/5106258.png",
    desc: [],
    archetype: "",
    strengths: [],
    weaknesses: [],
  },
  {
    id: 10,
    rank: 10,
    firstName: "Keyonte",
    lastName: "George",
    position: "SG",
    class: "Fr.",
    height: 76,
    weight: 185,
    ras: null,
    school: "Baylor",
    img: "https://a.espncdn.com/combiner/i?img=/i/headshots/mens-college-basketball/players/full/4433627.png&w=350&h=254",
    desc: [],
    archetype: "",
    strengths: [],
    weaknesses: [],
  },
  {
    id: 11,
    rank: 12,
    firstName: "Cason",
    lastName: "Wallace",
    position: "PG",
    class: "Fr.",
    height: 74,
    weight: 195,
    ras: null,
    school: "Kentucky",
    img: "https://a.espncdn.com/combiner/i?img=/i/headshots/mens-college-basketball/players/full/4683692.png&w=350&h=254",
    desc: [],
    archetype: "",
    strengths: [],
    weaknesses: [],
  },
  {
    id: 12,
    rank: 13,
    firstName: "Jordan",
    lastName: "Hawkins",
    position: "PG",
    class: "So.",
    height: 76,
    weight: 186,
    ras: null,
    school: "UConn",
    img: "https://a.espncdn.com/combiner/i?img=/i/headshots/mens-college-basketball/players/full/4683750.png&w=350&h=254",
    desc: [],
    archetype: "",
    strengths: [],
    weaknesses: [],
  },
  {
    id: 13,
    rank: 14,
    firstName: "Nick",
    lastName: "Smith",
    position: "SG",
    class: "Fr.",
    height: 77,
    weight: 185,
    ras: null,
    school: "Arkansas",
    img: "https://collegehoopstoday.com/wp-content/uploads/2022/10/NICK-SMITH-2022.jpeg",
    desc: [],
    archetype: "",
    strengths: [],
    weaknesses: [],
  },
  {
    id: 14,
    rank: 15,
    firstName: "Dereck",
    lastName: "Lively II",
    position: "C",
    class: "Fr.",
    height: 85,
    weight: 230,
    ras: null,
    school: "Duke",
    img: "https://a.espncdn.com/combiner/i?img=/i/headshots/mens-college-basketball/players/full/4683688.png&w=350&h=254",
    desc: [],
    archetype: "",
    strengths: [],
    weaknesses: [],
  },
  {
    id: 15,
    rank: 16,
    firstName: "Kobe",
    lastName: "Bufkin",
    position: "SG",
    class: "So.",
    height: 76,
    weight: 187,
    ras: null,
    school: "Michigan",
    img: "https://a.espncdn.com/combiner/i?img=/i/headshots/mens-college-basketball/players/full/4683736.png&w=350&h=254",
    desc: [],
    archetype: "",
    strengths: [],
    weaknesses: [],
  },
  {
    id: 16,
    rank: 17,
    firstName: "Jalen",
    lastName: "Hood-Schifino",
    position: "PG",
    class: "Fr.",
    height: 76,
    weight: 217,
    ras: null,
    school: "Indiana",
    img: "https://a.espncdn.com/combiner/i?img=/i/headshots/mens-college-basketball/players/full/5105797.png&w=350&h=254",
    desc: [],
    archetype: "",
    strengths: [],
    weaknesses: [],
  },
  {
    id: 17,
    rank: 18,
    firstName: "Bilal",
    lastName: "Coulibaly",
    position: "SF",
    class: "",
    height: 79,
    weight: 230,
    ras: null,
    school: "France",
    img: "https://www.proballers.com/media/cache/resize_300/ul/player/backup/001-1ed3c212-5e8f-6956-a613-470c0a9f9560.jpg",
    desc: [],
    archetype: "",
    strengths: [],
    weaknesses: [],
  },
  {
    id: 18,
    rank: 19,
    firstName: "Jett",
    lastName: "Howard",
    position: "SG",
    class: "Fr.",
    height: 80,
    weight: 215,
    ras: null,
    school: "Michigan",
    img: "https://a.espncdn.com/combiner/i?img=/i/headshots/mens-college-basketball/players/full/5105806.png&w=350&h=254",
    desc: [],
    archetype: "",
    strengths: [],
    weaknesses: [],
  },
  {
    id: 19,
    rank: 20,
    firstName: "Leonard",
    lastName: "Miller",
    position: "SF",
    class: "",
    height: 81,
    weight: 213,
    ras: null,
    school: "G League Ignite",
    img: "https://cdn.nba.com/manage/2022/06/miller216.jpg",
    desc: [],
    archetype: "",
    strengths: [],
    weaknesses: [],
  },
];
