export const NFL_2024_Prospects = [
  {
    id: 1,
    rank: 1,
    firstName: "Caleb",
    lastName: "Williams",
    position: "QB",
    class: "Jr.",
    height: 73,
    weight: 215,
    ras: null,
    school: "USC",
    img: "https://a.espncdn.com/combiner/i?img=/i/headshots/college-football/players/full/4431611.png",
    desc: [],
    archetype: "",
    strengths: [],
    weaknesses: [],
  },
  {
    id: 2,
    rank: 2,
    firstName: "Drake",
    lastName: "Maye",
    position: "QB",
    class: "So.",
    height: 76,
    weight: 230,
    ras: null,
    school: "North Carolina",
    img: "https://a.espncdn.com/combiner/i?img=/i/headshots/college-football/players/full/4431452.png&w=350&h=254",
    archetype: "",
  },
  {
    id: 3,
    rank: 3,
    firstName: "Marvin",
    lastName: "Harrison Jr.",
    position: "WR",
    class: "Jr.",
    height: 76,
    weight: 205,
    ras: null,
    school: "Ohio State",
    img: "https://a.espncdn.com/combiner/i?img=/i/headshots/college-football/players/full/4432708.png&w=350&h=254",
    archetype: "",
  },
  {
    id: 4,
    rank: 4,
    firstName: "Jayden",
    lastName: "Daniels",
    position: "QB",
    class: "Sr.",
    height: 76,
    weight: 210,
    ras: null,
    school: "LSU",
    img: "https://a.espncdn.com/combiner/i?img=/i/headshots/college-football/players/full/4426348.png&w=350&h=254",
    archetype: "",
  },
  {
    id: 5,
    rank: 5,
    firstName: "Malik",
    lastName: "Nabers",
    position: "WR",
    class: "Jr.",
    height: 72,
    weight: 200,
    ras: null,
    school: "LSU",
    img: "https://a.espncdn.com/combiner/i?img=/i/headshots/college-football/players/full/4595348.png&w=350&h=254",
    archetype: "",
  },
  {
    id: 6,
    rank: 9,
    firstName: "Brock",
    lastName: "Bowers",
    position: "TE",
    class: "Jr.",
    height: 76,
    weight: 240,
    ras: null,
    school: "Georgia",
    img: "https://a.espncdn.com/combiner/i?img=/i/headshots/college-football/players/full/4432665.png&w=350&h=254",
    archetype: "",
  },
  {
    id: 7,
    rank: 6,
    firstName: "Rome",
    lastName: "Odunze",
    position: "WR",
    class: "Jr.",
    height: 75,
    weight: 215,
    ras: 9.91,
    school: "Washington",
    img: "https://a.espncdn.com/combiner/i?img=/i/headshots/college-football/players/full/4431299.png&w=350&h=254",
    archetype: "",
  },
  {
    id: 8,
    rank: 8,
    firstName: "Joe",
    lastName: "Alt",
    position: "T",
    class: "Jr.",
    height: 80,
    weight: 322,
    ras: 9.91,
    school: "Notre Dame",
    img: "https://a.espncdn.com/combiner/i?img=/i/headshots/college-football/players/full/4683487.png&w=350&h=254",
    archetype: "",
  },
  {
    id: 9,
    rank: 7,
    firstName: "Dallas",
    lastName: "Turner",
    position: "ED",
    class: "Jr.",
    height: 76,
    weight: 242,
    ras: 9.48,
    school: "Alabama",
    img: "https://a.espncdn.com/combiner/i?img=/i/headshots/college-football/players/full/4565190.png&w=350&h=254",
    archetype: "",
  },
  {
    id: 10,
    rank: 10,
    firstName: "Olumuyiwa",
    lastName: "Fashanu",
    position: "T",
    class: "Jr.",
    height: 78,
    weight: 319,
    ras: 9.44,
    school: "Penn State",
    img: "https://a.espncdn.com/combiner/i?img=/i/headshots/college-football/players/full/4431809.png&w=350&h=254",
    archetype: "",
  },
  {
    id: 11,
    rank: 12,
    firstName: "Terrion",
    lastName: "Arnold",
    position: "CB",
    class: "RS So.",
    height: 72,
    weight: 196,
    ras: 8.82,
    school: "Alabama",
    img: "https://a.espncdn.com/combiner/i?img=/i/headshots/college-football/players/full/4592837.png&w=350&h=254",
    archetype: "",
  },
  {
    id: 12,
    rank: 13,
    firstName: "Jared",
    lastName: "Verse",
    position: "ED",
    class: "RS Jr.",
    height: 76,
    weight: 260,
    ras: 9.52,
    school: "Florida State",
    img: "https://a.espncdn.com/combiner/i?img=/i/headshots/college-football/players/full/4578085.png&w=350&h=254",
    archetype: "",
  },
  {
    id: 13,
    rank: 15,
    firstName: "Taliese",
    lastName: "Fuaga",
    position: "T",
    class: "Jr.",
    height: 78,
    weight: 334,
    ras: 9.71,
    school: "Oklahoma State",
    img: "https://a.espncdn.com/combiner/i?img=/i/headshots/college-football/players/full/4606711.png&w=350&h=254",
    archetype: "",
  },
  {
    id: 14,
    rank: 16,
    firstName: "Laiatu",
    lastName: "Latu",
    position: "ED",
    class: "Sr.",
    height: 77,
    weight: 265,
    ras: 9.16,
    school: "UCLA",
    img: "https://a.espncdn.com/combiner/i?img=/i/headshots/college-football/players/full/4426473.png&w=350&h=254",
    archetype: "",
  },
  {
    id: 15,
    rank: 11,
    firstName: "Quinyon",
    lastName: "Mitchell",
    position: "CB",
    class: "Jr.",
    height: 72,
    weight: 196,
    ras: 9.84,
    school: "Toldeo",
    img: "https://a.espncdn.com/combiner/i?img=/i/headshots/college-football/players/full/4686273.png&w=350&h=254",
    archetype: "",
  },
  {
    id: 16,
    rank: 17,
    firstName: "Nate",
    lastName: "Wiggins",
    position: "CB",
    class: "Jr.",
    height: 74,
    weight: 185,
    ras: 8.76,
    school: "Clemson",
    img: "https://a.espncdn.com/combiner/i?img=/i/headshots/college-football/players/full/4601278.png&w=350&h=254",
    archetype: "",
  },
  {
    id: 17,
    rank: 19,
    firstName: "JC",
    lastName: "Latham",
    position: "T",
    class: "Jr.",
    height: 78,
    weight: 335,
    ras: null,
    school: "Alabama",
    img: "https://a.espncdn.com/combiner/i?img=/i/headshots/college-football/players/full/4431437.png&w=350&h=254",
    archetype: "",
  },
  {
    id: 18,
    rank: 22,
    firstName: "Cooper",
    lastName: "DeJean",
    position: "CB",
    class: "Jr.",
    height: 73,
    weight: 207,
    ras: null,
    school: "Iowa",
    img: "https://a.espncdn.com/combiner/i?img=/i/headshots/college-football/players/full/4682618.png&w=350&h=254",
    archetype: "",
  },
  {
    id: 19,
    rank: 27,
    firstName: "Kool-Aid",
    lastName: "McKinstry",
    position: "CB",
    class: "Jr.",
    height: 73,
    weight: 195,
    ras: null,
    school: "Alabama",
    img: "https://a.espncdn.com/combiner/i?img=/i/headshots/college-football/players/full/4433975.png&w=350&h=254",
    archetype: "",
  },
  {
    id: 20,
    rank: 25,
    firstName: "Jer'Zhan",
    lastName: "Newton",
    position: "DI",
    class: "Jr.",
    height: 74,
    weight: 295,
    ras: null,
    school: "Illinois",
    img: "https://a.espncdn.com/combiner/i?img=/i/headshots/college-football/players/full/4430560.png&w=350&h=254",
    archetype: "",
  },
  {
    id: 21,
    rank: 18,
    firstName: "Byron",
    lastName: "Murphy II",
    position: "DI",
    class: "Jr.",
    height: 73,
    weight: 308,
    ras: 9.02,
    school: "Texas",
    img: "https://a.espncdn.com/combiner/i?img=/i/headshots/college-football/players/full/4570040.png&w=350&h=254",
    archetype: "",
  },
  {
    id: 22,
    rank: 20,
    firstName: "Brian",
    lastName: "Thomas Jr.",
    position: "WR",
    class: "Jr.",
    height: 76,
    weight: 205,
    ras: 9.97,
    school: "LSU",
    img: "https://a.espncdn.com/combiner/i?img=/i/headshots/college-football/players/full/4432773.png&w=350&h=254",
    archetype: "",
  },
  {
    id: 23,
    rank: 21,
    firstName: "Amarius",
    lastName: "Mims",
    position: "T",
    class: "Jr.",
    height: 79,
    weight: 340,
    ras: 9.50,
    school: "Georgia",
    img: "https://a.espncdn.com/combiner/i?img=/i/headshots/college-football/players/full/4431571.png&w=350&h=254",
    archetype: "",
  },
  {
    id: 24,
    rank: 14,
    firstName: "J.J.",
    lastName: "McCarthy",
    position: "QB",
    class: "Jr.",
    height: 75,
    weight: 202,
    ras: null,
    school: "Michigan",
    img: "https://a.espncdn.com/combiner/i?img=/i/headshots/college-football/players/full/4433970.png&w=350&h=254",
    archetype: "",
  },
  {
    id: 25,
    rank: 23,
    firstName: "Jackson",
    lastName: "Powers-Johnson",
    position: "C",
    class: "Jr.",
    height: 75,
    weight: 320,
    ras: null,
    school: "Oregon",
    img: "https://a.espncdn.com/combiner/i?img=/i/headshots/college-football/players/full/4875295.png&w=350&h=254",
    archetype: "",
  },
  {
    id: 26,
    rank: 24,
    firstName: "Troy",
    lastName: "Fautanu",
    position: "T",
    class: "Jr.",
    height: 76,
    weight: 317,
    ras: 9.40,
    school: "Washington",
    img: "https://a.espncdn.com/combiner/i?img=/i/headshots/college-football/players/full/4427170.png&w=350&h=254",
    archetype: "",
  },
  {
    id: 27,
    rank: 28,
    firstName: "Tyler",
    lastName: "Guyton",
    position: "T",
    class: "RS Jr.",
    height: 79,
    weight: 327,
    ras: 9.63,
    school: "Oklahoma",
    img: "https://a.espncdn.com/combiner/i?img=/i/headshots/college-football/players/full/4609048.png&w=350&h=254",
    archetype: "",
  },
  {
    id: 28,
    rank: 26,
    firstName: "Chop",
    lastName: "Robinson",
    position: "ED",
    class: "Jr.",
    height: 75,
    weight: 250,
    ras: 9.69,
    school: "Penn State",
    img: "https://a.espncdn.com/combiner/i?img=/i/headshots/college-football/players/full/4431586.png&w=350&h=254",
    archetype: "",
  },
  {
    id: 29,
    rank: 31,
    firstName: "Keon",
    lastName: "Coleman",
    position: "WR",
    class: "Jr.",
    height: 76,
    weight: 215,
    ras: 9.18,
    school: "Florida State",
    img: "https://a.espncdn.com/combiner/i?img=/i/headshots/college-football/players/full/4635008.png&w=350&h=254",
    archetype: "",
  },
  {
    id: 30,
    rank: 32,
    firstName: "Ennis",
    lastName: "Rakestraw Jr.",
    position: "CB",
    class: "Jr.",
    height: 72,
    weight: 188,
    ras: 5.74,
    school: "Missouri",
    img: "https://a.espncdn.com/combiner/i?img=/i/headshots/college-football/players/full/4566092.png&w=350&h=254",
    archetype: "",
  },
  {
    id: 31,
    rank: 29,
    firstName: "Graham",
    lastName: "Barton",
    position: "T",
    class: "Sr.",
    height: 77,
    weight: 314,
    ras: null,
    school: "Duke",
    img: "https://a.espncdn.com/combiner/i?img=/i/headshots/college-football/players/full/4429251.png&w=350&h=254",
    archetype: "",
  },
  {
    id: 32,
    rank: 38,
    firstName: "Troy",
    lastName: "Franklin",
    position: "WR",
    class: "Jr.",
    height: 75,
    weight: 187,
    ras: 8.18,
    school: "Oregon",
    img: "https://a.espncdn.com/combiner/i?img=/i/headshots/college-football/players/full/4431280.png&w=350&h=254",
    archetype: "",
  },
  {
    id: 33,
    rank: 35,
    firstName: "Bo",
    lastName: "Nix",
    position: "QB",
    class: "Sr.",
    height: 74,
    weight: 217,
    ras: null,
    school: "Oregon",
    img: "https://a.espncdn.com/combiner/i?img=/i/headshots/college-football/players/full/4426338.png&w=350&h=254",
    archetype: "",
  },
  {
    id: 34,
    rank: 43,
    firstName: "Bralen",
    lastName: "Trice",
    position: "ED",
    class: "Jr.",
    height: 76,
    weight: 274,
    ras: null,
    school: "Washington",
    img: "https://a.espncdn.com/combiner/i?img=/i/headshots/college-football/players/full/4428713.png&w=350&h=254",
    archetype: "",
  },
  {
    id: 35,
    rank: 36,
    firstName: "Jordan",
    lastName: "Morgan",
    position: "T",
    class: "Sr.",
    height: 78,
    weight: 320,
    ras: 8.99,
    school: "Arizona",
    img: "https://a.espncdn.com/combiner/i?img=/i/headshots/college-football/players/full/3821571.png&w=350&h=254",
    archetype: "",
  },
  {
    id: 36,
    rank: 40,
    firstName: "Kamari",
    lastName: "Lassiter",
    position: "CB",
    class: "Jr.",
    height: 72,
    weight: 180,
    ras: null,
    school: "Georgia",
    img: "https://a.espncdn.com/combiner/i?img=/i/headshots/college-football/players/full/4602699.png&w=350&h=254",
    archetype: "",
  },
  {
    id: 37,
    rank: 30,
    firstName: "Adonai",
    lastName: "Mitchell",
    position: "WR",
    class: "Jr.",
    height: 76,
    weight: 196,
    ras: 9.98,
    school: "Texas",
    img: "https://a.espncdn.com/combiner/i?img=/i/headshots/college-football/players/full/4597500.png&w=350&h=254",
    archetype: "",
  },
  {
    id: 38,
    rank: 39,
    firstName: "Michael",
    lastName: "Penix Jr.",
    position: "QB",
    class: "Sr.",
    height: 75,
    weight: 213,
    ras: null,
    school: "Washington",
    img: "https://a.espncdn.com/combiner/i?img=/i/headshots/college-football/players/full/4360423.png&w=350&h=254",
    archetype: "",
  },
  {
    id: 39,
    rank: 33,
    firstName: "Darius",
    lastName: "Robinson",
    position: "ED",
    class: "Sr.",
    height: 77,
    weight: 296,
    ras: 8.83,
    school: "Missouri",
    img: "https://a.espncdn.com/combiner/i?img=/i/headshots/college-football/players/full/4569480.png&w=350&h=254",
    archetype: "",
  },
  {
    id: 40,
    rank: 37,
    firstName: "Ladd",
    lastName: "McConkey",
    position: "WR",
    class: "Jr.",
    height: 72,
    weight: 185,
    ras: 8.84,
    school: "Georgia",
    img: "https://a.espncdn.com/combiner/i?img=/i/headshots/college-football/players/full/4612826.png&w=350&h=254",
    archetype: "",
  },
  {
    id: 41,
    rank: 34,
    firstName: "Xavier",
    lastName: "Worthy",
    position: "WR",
    class: "Jr.",
    height: 73,
    weight: 172,
    ras: 9.34,
    school: "Texas",
    img: "https://a.espncdn.com/combiner/i?img=/i/headshots/college-football/players/full/4683062.png&w=350&h=254",
    archetype: "",
  },
  {
    id: 42,
    rank: 41,
    firstName: "Kingsley",
    lastName: "Suamataia",
    position: "T",
    class: "So.",
    height: 78,
    weight: 315,
    ras: 9.14,
    school: "BYU",
    img: "https://a.espncdn.com/combiner/i?img=/i/headshots/college-football/players/full/4431595.png&w=350&h=254",
    archetype: "",
  },
  {
    id: 43,
    rank: 42,
    firstName: "Tyler",
    lastName: "Nubin",
    position: "S",
    class: "RS Sr.",
    height: 74,
    weight: 210,
    ras: null,
    school: "Minnesota",
    img: "https://a.espncdn.com/combiner/i?img=/i/headshots/college-football/players/full/4430261.png&w=350&h=254",
    archetype: "",
  },
  {
    id: 44,
    rank: 48,
    firstName: "T'Vondre",
    lastName: "Sweat",
    position: "DI",
    class: "Sr.",
    height: 76,
    weight: 362,
    ras: 4.07,
    school: "Texas",
    img: "https://a.espncdn.com/combiner/i?img=/i/headshots/college-football/players/full/4428617.png&w=350&h=254",
    archetype: "",
  },
  {
    id: 45,
    rank: 47,
    firstName: "Chris",
    lastName: "Braswell",
    position: "ED",
    class: "Sr.",
    height: 75,
    weight: 255,
    ras: 8.63,
    school: "Alabama",
    img: "https://a.espncdn.com/combiner/i?img=/i/headshots/college-football/players/full/4428989.png&w=350&h=254",
    archetype: "",
  },
  {
    id: 46,
    rank: 45,
    firstName: "Zach",
    lastName: "Frazier",
    position: "C",
    class: "Jr.",
    height: 75,
    weight: 310,
    ras: null,
    school: "West Virginia",
    img: "https://a.espncdn.com/combiner/i?img=/i/headshots/college-football/players/full/4429775.png&w=350&h=254",
    archetype: "",
  },
  {
    id: 47,
    rank: 52,
    firstName: "Ja'Tavion",
    lastName: "Sanders",
    position: "TE",
    class: "Jr.",
    height: 76,
    weight: 243,
    ras: 8.06,
    school: "Texas",
    img: "https://a.espncdn.com/combiner/i?img=/i/headshots/college-football/players/full/4431588.png&w=350&h=254",
    archetype: "",
  },
  {
    id: 48,
    rank: 49,
    firstName: "Kamren",
    lastName: "Kinchens",
    position: "S",
    class: "Jr.",
    height: 72,
    weight: 205,
    ras: 2.08,
    school: "Miami",
    img: "https://a.espncdn.com/combiner/i?img=/i/headshots/college-football/players/full/4596363.png&w=350&h=254",
    archetype: "",
  },
  {
    id: 49,
    rank: 53,
    firstName: "Patrick",
    lastName: "Paul",
    position: "T",
    class: "Jr.",
    height: 79,
    weight: 315,
    ras: 9.74,
    school: "Houston",
    img: "https://a.espncdn.com/combiner/i?img=/i/headshots/college-football/players/full/4567493.png&w=350&h=254",
    archetype: "",
  },
  {
    id: 50,
    rank: 44,
    firstName: "Edgerrin",
    lastName: "Cooper",
    position: "LB",
    class: "Jr.",
    height: 75,
    weight: 230,
    ras: 9.34,
    school: "Texas A&M",
    img: "https://a.espncdn.com/combiner/i?img=/i/headshots/college-football/players/full/4430438.png&w=350&h=254",
    archetype: "",
  },
  {
    id: 51,
    rank: 46,
    firstName: "Kris",
    lastName: "Jenkins",
    position: "DI",
    class: "Sr.",
    height: 75,
    weight: 305,
    ras: 8.92,
    school: "Michigan",
    img: "https://a.espncdn.com/combiner/i?img=/i/headshots/college-football/players/full/4432301.png&w=350&h=254",
    archetype: "",
  },
  {
    id: 52,
    rank: 57,
    firstName: "Payton",
    lastName: "Wilson",
    position: "LB",
    class: "Sr.",
    height: 76,
    weight: 238,
    ras: 9.81,
    school: "NC State",
    img: "https://a.espncdn.com/combiner/i?img=/i/headshots/college-football/players/full/4361652.png&w=350&h=254",
    archetype: "",
  },
  {
    id: 53,
    rank: 68,
    firstName: "T.J.",
    lastName: "Tampa",
    position: "CB",
    class: "Sr.",
    height: 74,
    weight: 200,
    ras: null,
    school: "Iowa State",
    img: "https://a.espncdn.com/combiner/i?img=/i/headshots/college-football/players/full/4575483.png&w=350&h=254",
    archetype: "",
  },
  {
    id: 54,
    rank: 51,
    firstName: "Roman",
    lastName: "Wilson",
    position: "WR",
    class: "Sr.",
    height: 72,
    weight: 192,
    ras: null,
    school: "Michigan",
    img: "https://a.espncdn.com/combiner/i?img=/i/headshots/college-football/players/full/4431492.png&w=350&h=254",
    archetype: "",
  },
  {
    id: 55,
    rank: 56,
    firstName: "Ja'Lynn",
    lastName: "Polk",
    position: "WR",
    class: "So.",
    height: 74,
    weight: 204,
    ras: 9.46,
    school: "Washington",
    img: "https://a.espncdn.com/combiner/i?img=/i/headshots/college-football/players/full/4430637.png&w=350&h=254",
    archetype: "",
  },
  {
    id: 56,
    rank: 50,
    firstName: "Xavier",
    lastName: "Legette",
    position: "WR",
    class: "So.",
    height: 75,
    weight: 227,
    ras: 9.92,
    school: "South Carolina",
    img: "https://a.espncdn.com/combiner/i?img=/i/headshots/college-football/players/full/4430034.png&w=350&h=254",
    archetype: "",
  },
  // {
  //   id: 57,
  //   rank: 57,
  //   firstName: "Malachi",
  //   lastName: "Corley",
  //   position: "WR",
  //   class: "Jr.",
  //   height: 71,
  //   weight: 210,
  //   ras: null,
  //   school: "Western Kentucky",
  //   img: "https://a.espncdn.com/combiner/i?img=/i/headshots/college-football/players/full/4613104.png&w=350&h=254",
  //   archetype: "",
  // },
  {
    id: 58,
    rank: 58,
    firstName: "Junior",
    lastName: "Colson",
    position: "LB",
    class: "Jr.",
    height: 75,
    weight: 247,
    ras: null,
    school: "Michigan",
    img: "https://a.espncdn.com/combiner/i?img=/i/headshots/college-football/players/full/4431212.png&w=350&h=254",
    archetype: "",
  },
  {
    id: 59,
    rank: 55,
    firstName: "Cooper",
    lastName: "Beebe",
    position: "G",
    class: "Sr.",
    height: 76,
    weight: 335,
    ras: 9.70,
    school: "Kansas State",
    img: "https://a.espncdn.com/combiner/i?img=/i/headshots/college-football/players/full/4426663.png&w=350&h=254",
    archetype: "",
  },
  {
    id: 60,
    rank: 70,
    firstName: "Adisa",
    lastName: "Isaac",
    position: "ED",
    class: "RS Sr.",
    height: 76,
    weight: 254,
    ras: 8.77,
    school: "Penn State",
    img: "https://a.espncdn.com/combiner/i?img=/i/headshots/college-football/players/full/4426372.png&w=350&h=254",
    archetype: "",
  },
  {
    id: 61,
    rank: 54,
    firstName: "Braden",
    lastName: "Fiske",
    position: "DI",
    class: "RS Sr.",
    height: 77,
    weight: 297,
    ras: 9.88,
    school: "Florida State",
    img: "https://a.espncdn.com/combiner/i?img=/i/headshots/college-football/players/full/4362245.png&w=350&h=254",
    archetype: "",
  },
  {
    id: 62,
    rank: 59,
    firstName: "Ricky",
    lastName: "Pearsall",
    position: "WR",
    class: "Sr.",
    height: 73,
    weight: 192,
    ras: 9.78,
    school: "Florida",
    img: "https://a.espncdn.com/combiner/i?img=/i/headshots/college-football/players/full/4428209.png&w=350&h=254",
    archetype: "",
  },
  {
    id: 63,
    rank: 60,
    firstName: "Javon",
    lastName: "Bullard",
    position: "S",
    class: "Jr.",
    height: 71,
    weight: 195,
    ras: null,
    school: "Georgia",
    img: "https://a.espncdn.com/combiner/i?img=/i/headshots/college-football/players/full/4688930.png&w=350&h=254",
    archetype: "",
  },
  {
    id: 64,
    rank: 61,
    firstName: "Michael",
    lastName: "Hall Jr.",
    position: "DI",
    class: "Jr.",
    height: 74,
    weight: 280,
    ras: null,
    school: "Ohio State",
    img: "https://a.espncdn.com/combiner/i?img=/i/headshots/college-football/players/full/4600415.png&w=350&h=254",
    archetype: "",
  },
  {
    id: 65,
    rank: 62,
    firstName: "Mike",
    lastName: "Sainristil",
    position: "CB",
    class: "G",
    height: 70,
    weight: 182,
    ras: 8.34,
    school: "Michigan",
    img: "https://a.espncdn.com/combiner/i?img=/i/headshots/college-football/players/full/4428414.png&w=350&h=254",
    archetype: "",
  },
  {
    id: 66,
    rank: 63,
    firstName: "Ruke",
    lastName: "Orhorhoro",
    position: "DI",
    class: "G",
    height: 76,
    weight: 295,
    ras: 9.87,
    school: "Clemson",
    img: "https://a.espncdn.com/combiner/i?img=/i/headshots/college-football/players/full/4430271.png&w=350&h=254",
    archetype: "",
  },
  {
    id: 67,
    rank: 64,
    firstName: "Jonathon",
    lastName: "Brooks",
    position: "RB",
    class: "So.",
    height: 72,
    weight: 207,
    ras: null,
    school: "Texas",
    img: "https://a.espncdn.com/combiner/i?img=/i/headshots/college-football/players/full/4678008.png&w=350&h=254",
    archetype: "",
  },
  {
    id: 68,
    rank: 65,
    firstName: "Devontez",
    lastName: "Walker",
    position: "WR",
    school: "North Carolina",
    class: "Jr.",
    height: 74,
    weight: 200,
    archetype: "",
    ras: 9.86,
    img: "https://a.espncdn.com/combiner/i?img=/i/headshots/college-football/players/full/4696882.png&w=350&h=254",
  },
  {
    id: 69,
    rank: 66,
    firstName: "Marshawn",
    lastName: "Kneeland",
    position: "ED",
    school: "Western Michigan",
    class: "RS Jr.",
    height: 75,
    weight: 275,
    archetype: "",
    ras: 9.54,
    img: "https://a.espncdn.com/combiner/i?img=/i/headshots/college-football/players/full/4429996.png&w=350&h=254",
  },
  {
    id: 70,
    rank: 67,
    firstName: "Blake",
    lastName: "Corum",
    position: "RB",
    school: "Michigan",
    class: "Sr.",
    height: 68,
    weight: 213,
    archetype: "",
    ras: 8.48,
    img: "https://a.espncdn.com/combiner/i?img=/i/headshots/college-football/players/full/4429096.png&w=350&h=254",
  },
  {
   id: 71,
    rank: 69,
    firstName: "Calen",
    lastName: "Bullock",
    position: "S",
    school: "USC",
    class: "Jr.",
    height: 75,
    weight: 190,
    archetype: "",
    ras: null,
    img: "https://a.espncdn.com/combiner/i?img=/i/headshots/college-football/players/full/4431517.png&w=350&h=254",
  },
];
