export const NFL_2025_Prospects = [
    {
        id: 251,
        rank: 1,
        firstName: "Shedeur",
        lastName: "Sanders",
        position: "QB",
        school: "Colorado",
        class: "Sr.",
        height: 74,
        weight: 215,
        archetype: "",
        ras: null,
    },
    {
        id: 252,
        rank: 2,
        firstName: "Cam",
        lastName: "Ward",
        position: "QB",
        school: "Miami",
        class: "Sr.",
        height: 74,
        weight: 223,
        archetype: "",
        ras: null,
    },
    {
        id: 253,
        rank: 3,
        firstName: "Travis",
        lastName: "Hunter",
        position: "CB",
        school: "Colorado",
        class: "Sr.",
        height: 73,
        weight: 185,
        archetype: "",
        ras: null,
    },
    {
        id: 254,
        rank: 4,
        firstName: "Mason",
        lastName: "Graham",
        position: "DI",
        school: "Michigan",
        class: "Jr.",
        height: 75,
        weight: 320,
        archetype: "",
        ras: null,
    },
    {
        id: 255,
        rank: 5,
        firstName: "Abdul",
        lastName: "Carter",
        position: "ED",
        school: "Penn State",
        class: "Jr.",
        height: 75,
        weight: 252,
        archetype: "",
        ras: null,
    },
    {
        id: 256,
        rank: 6,
        firstName: "Will",
        lastName: "Campbell",
        position: "T",
        school: "LSU",
        class: "Jr.",
        height: 78,
        weight: 323,
        archetype: "",
        ras: null,
    },
    {
        id: 257,
        rank: 7,
        firstName: "Will",
        lastName: "Johnson",
        position: "CB",
        school: "Michigan",
        class: "Jr.",
        height: 74,
        weight: 202,
        archetype: "",
        ras: null,
    },
    {
        id: 258,
        rank: 8,
        firstName: "Tetairoa",
        lastName: "McMillan",
        position: "WR",
        school: "Arizona",
        class: "Jr.",
        height: 75,
        weight: 212,
        archetype: "",
        ras: null,
    },
    {
        id: 259,
        rank: 9,
        firstName: "Kelvin",
        lastName: "Banks",
        position: "T",
        school: "Texas",
        class: "Jr.",
        height: 76,
        weight: 320,
        archetype: "",
        ras: null,
    },
    {
        id: 2510,
        rank: 10,
        firstName: "Mykel",
        lastName: "Williams",
        position: "ED",
        school: "Georgia",
        class: "Jr.",
        height: 77,
        weight: 265,
        archetype: "",
        ras: null,
    }
];
