export const NFL_2025_Prospects = [
    {
        id: 251,
        rank: 2,
        firstName: "Shedeur",
        lastName: "Sanders",
        position: "QB",
        school: "Colorado",
        class: "Sr.",
        height: 74,
        weight: 215,
        archetype: "",
        ras: null,
    },
    {
        id: 252,
        rank: 1,
        firstName: "Cam",
        lastName: "Ward",
        position: "QB",
        school: "Miami",
        class: "Sr.",
        height: 74,
        weight: 223,
        archetype: "",
        ras: null,
    },
    {
        id: 253,
        rank: 3,
        firstName: "Travis",
        lastName: "Hunter",
        position: "CB",
        school: "Colorado",
        class: "Sr.",
        height: 73,
        weight: 185,
        archetype: "",
        ras: null,
    },
    {
        id: 254,
        rank: 5,
        firstName: "Mason",
        lastName: "Graham",
        position: "DI",
        school: "Michigan",
        class: "Jr.",
        height: 75,
        weight: 320,
        archetype: "",
        ras: null,
    },
    {
        id: 255,
        rank: 4,
        firstName: "Abdul",
        lastName: "Carter",
        position: "ED",
        school: "Penn State",
        class: "Jr.",
        height: 75,
        weight: 252,
        archetype: "",
        ras: null,
    },
    {
        id: 256,
        rank: 8,
        firstName: "Will",
        lastName: "Campbell",
        position: "T",
        school: "LSU",
        class: "Jr.",
        height: 78,
        weight: 323,
        archetype: "",
        ras: null,
    },
    {
        id: 257,
        rank: 7,
        firstName: "Will",
        lastName: "Johnson",
        position: "CB",
        school: "Michigan",
        class: "Jr.",
        height: 74,
        weight: 202,
        archetype: "",
        ras: null,
    },
    {
        id: 258,
        rank: 6,
        firstName: "Tetairoa",
        lastName: "McMillan",
        position: "WR",
        school: "Arizona",
        class: "Jr.",
        height: 75,
        weight: 212,
        archetype: "",
        ras: null,
    },
    {
        id: 259,
        rank: 9,
        firstName: "Kelvin",
        lastName: "Banks",
        position: "T",
        school: "Texas",
        class: "Jr.",
        height: 76,
        weight: 320,
        archetype: "",
        ras: null,
    },
    {
        id: 2510,
        rank: 10,
        firstName: "Mykel",
        lastName: "Williams",
        position: "ED",
        school: "Georgia",
        class: "Jr.",
        height: 77,
        weight: 265,
        archetype: "",
        ras: null,
    },
    {
        id: 2511,
        rank: 12,
        firstName: "Malaki",
        lastName: "Starks",
        position: "S",
        school: "Georgia",
        class: "Jr.",
        height: 73,
        weight: 205,
        archetype: "",
        ras: null,
    },
    {
        id: 2512,
        rank: 11,
        firstName: "Ashton",
        lastName: "Jeanty",
        position: "RB",
        school: "Boise State",
        class: "Jr.",
        height: 69,
        weight: 215,
        archetype: "",
        ras: null,
    },
    {
        id: 2513,
        rank: 16,
        firstName: "Jalon",
        lastName: "Walker",
        position: "LB",
        school: "Georgia",
        class: "Jr.",
        height: 74,
        weight: 245,
        archetype: "",
        ras: null,
    },
    {
        id: 2514,
        rank: 13,
        firstName: "James",
        lastName: "Pearce Jr.",
        position: "ED",
        school: "Tennessee",
        class: "Jr.",
        height: 77,
        weight: 243,
        archetype: "",
        ras: null,
    },
    {
        id: 2515,
        rank: 14,
        firstName: "Luther",
        lastName: "Burden III",
        position: "WR",
        school: "Missouri",
        class: "Jr.",
        height: 71,
        weight: 208,
        archetype: "",
        ras: null,
    },
    {
        id: 2516,
        rank: 17,
        firstName: "Nic",
        lastName: "Scourton",
        position: "ED",
        school: "Texas A&M",
        class: "Jr.",
        height: 76,
        weight: 285,
        archetype: "",
        ras: null,
    },
    {
        id: 2517,
        rank: 15,
        firstName: "Tyler",
        lastName: "Warren",
        position: "TE",
        school: "Penn State",
        class: "Sr.",
        height: 78,
        weight: 261,
        archetype: "",
        ras: null,
    },
    {
        id: 2518,
        rank: 18,
        firstName: "Josh",
        lastName: "Simmons",
        position: "T",
        school: "Ohio State",
        class: "Sr.",
        height: 77,
        weight: 310,
        archetype: "",
        ras: null,
    },
    {
        id: 2519,
        rank: 22,
        firstName: "Jalen",
        lastName: "Milroe",
        position: "QB",
        school: "Alabama",
        class: "RS Jr.",
        height: 74,
        weight: 225,
        archetype: "",
        ras: null,
    },
    {
        id: 2520,
        rank: 20,
        firstName: "Colston",
        lastName: "Loveland",
        position: "TE",
        school: "Michigan",
        class: "Jr.",
        height: 77,
        weight: 245,
        archetype: "",
        ras: null,
    },
    {
        id: 2521,
        rank: 25,
        firstName: "Shavon",
        lastName: "Revel Jr.",
        position: "CB",
        school: "East Carolina",
        class: "Sr.",
        height: 75,
        weight: 193,
        archetype: "",
        ras: null,
    },
    {
        id: 2522,
        rank: 19,
        firstName: "Kenneth",
        lastName: "Grant",
        position: "DI",
        school: "Michigan",
        class: "Jr.",
        height: 75,
        weight: 339,
        archetype: "",
        ras: null,
    },
    {
        id: 2523,
        rank: 27,
        firstName: "Walter",
        lastName: "Nolan",
        position: "DI",
        school: "Ole Miss",
        class: "Jr.",
        height: 75,
        weight: 305,
        archetype: "",
        ras: null,
    },
    {
        id: 2524,
        rank: 23,
        firstName: "Benjamin",
        lastName: "Morrison",
        position: "CB",
        school: "Notre Dame",
        class: "Jr.",
        height: 72,
        weight: 190,
        archetype: "",
        ras: null,
    },
    {
        id: 2525,
        rank: 21,
        firstName: "Emeka",
        lastName: "Egbuka",
        position: "WR",
        school: "Ohio State",
        class: "G",
        height: 73,
        weight: 205,
        archetype: "",
        ras: null,
    },
    {
        id: 2526,
        rank: 32,
        firstName: "Aireontae",
        lastName: "Ersery",
        position: "T",
        school: "Minnesota",
        class: "RS Sr.",
        height: 78,
        weight: 330,
        archetype: "",
        ras: null,
    },
    {
        id: 2527,
        rank: 28,
        firstName: "Derrick",
        lastName: "Harmon",
        position: "DI",
        school: "Oregon",
        class: "Jr.",
        height: 77,
        weight: 310,
        archetype: "",
        ras: null,
    },
    {
        id: 2528,
        rank: 26,
        firstName: "Tyler",
        lastName: "Booker",
        position: "G",
        school: "Alabama",
        class: "Jr.",
        height: 77,
        weight: 325,
        archetype: "",
        ras: null,
    },
    {
        id: 2529,
        rank: 24,
        firstName: "Shemar",
        lastName: "Stewart",
        position: "ED",
        school: "Texas A&M",
        class: "Jr.",
        height: 78,
        weight: 290,
        archetype: "",
        ras: null,
    },
    {
        id: 2530,
        rank: 30,
        firstName: "Jahdae",
        lastName: "Barron",
        position: "CB",
        school: "Texas",
        class: "Sr.",
        height: 71,
        weight: 200,
        archetype: "",
        ras: null,
    },
    {
        id: 2531,
        rank: 36,
        firstName: "Cameron",
        lastName: "Williams",
        position: "T",
        school: "Texas",
        class: "Jr.",
        height: 77,
        weight: 335,
        archetype: "",
        ras: null,
    },
    {
        id: 2532,
        rank: 29,
        firstName: "Josh",
        lastName: "Conerly Jr.",
        position: "T",
        school: "Oregon",
        class: "Jr.",
        height: 76,
        weight: 315,
        archetype: "",
        ras: null,
    },
    {
        id: 2533,
        rank: 31,
        firstName: "Mike",
        lastName: "Green",
        position: "ED",
        school: "Marshall",
        class: "RS So.",
        height: 76,
        weight: 248,
        archetype: "",
        ras: null,
    },
    {
        id: 2534,
        rank: 33,
        firstName: "Tyleik",
        lastName: "Williams",
        position: "DI",
        school: "Ohio State",
        class: "Sr.",
        height: 75,
        weight: 327,
        archetype: "",
        ras: null,
    },
    {
        id: 2535,
        rank: 35,
        firstName: "Jihaad",
        lastName: "Campbell",
        position: "LB",
        school: "Alabama",
        class: "Jr.",
        height: 75,
        weight: 244,
        archetype: "",
        ras: null,
    },
    {
        id: 2536,
        rank: 42,
        firstName: "Princely",
        lastName: "Umanmielen",
        position: "CB",
        school: "Ole Miss",
        class: "Sr.",
        height: 76,
        weight: 255,
        archetype: "",
        ras: null,
    },
    {
        id: 2537,
        rank: 46,
        firstName: "Wyatt",
        lastName: "Milum",
        position: "T",
        school: "West Virginia",
        class: "Sr.",
        height: 78,
        weight: 317,
        archetype: "",
        ras: null,
    },
    {
        id: 2538,
        rank: 43,
        firstName: "Landon",
        lastName: "Jackson",
        position: "ED",
        school: "Arkansas",
        class: "Sr.",
        height: 79,
        weight: 280,
        archetype: "",
        ras: null,
    },
    {
        id: 2539,
        rank: 41,
        firstName: "Jonah",
        lastName: "Savaiinaea",
        position: "T",
        school: "Arizona",
        class: "Jr.",
        height: 77,
        weight: 336,
        archetype: "",
        ras: null,
    },
    {
        id: 2540,
        rank: 47,
        firstName: "Trey",
        lastName: "Amos",
        position: "CB",
        school: "Ole Miss",
        class: "Sr.",
        height: 73,
        weight: 190,
        archetype: "",
        ras: null,
    },
    {
        id: 2541,
        rank: 50,
        firstName: "Isaiah",
        lastName: "Bond",
        position: "WR",
        school: "Texas",
        class: "Jr.",
        height: 71,
        weight: 180,
        archetype: "",
        ras: null,
    },
    {
        id: 2542,
        rank: 40,
        firstName: "Nick",
        lastName: "Emmanwori",
        position: "S",
        school: "South Carolina",
        class: "Jr.",
        height: 75,
        weight: 227,
        archetype: "",
        ras: null,
    },
    {
        id: 2543,
        rank: 44,
        firstName: "Tre",
        lastName: "Harris",
        position: "WR",
        school: "Ole Miss",
        class: "Sr.",
        height: 75,
        weight: 210,
        archetype: "",
        ras: null,
    },
    {
        id: 2544,
        rank: 49,
        firstName: "Omarion",
        lastName: "Hampton",
        position: "RB",
        school: "North Carolina",
        class: "Jr.",
        height: 73,
        weight: 220,
        archetype: "",
        ras: null,
    },
    {
        id: 2545,
        rank: 37,
        firstName: "Jack",
        lastName: "Sawyer",
        position: "ED",
        school: "Ohio State",
        class: "Sr.",
        height: 77,
        weight: 260,
        archetype: "",
        ras: null,
    },
    {
        id: 2546,
        rank: 38,
        firstName: "Donovan",
        lastName: "Jackson",
        position: "T",
        school: "Ohio State",
        class: "Sr.",
        height: 76,
        weight: 320,
        archetype: "",
        ras: null,
    },
    {
        id: 2547,
        rank: 56,
        firstName: "Deone",
        lastName: "Walker",
        position: "DI",
        school: "Kentucky",
        class: "Jr.",
        height: 78,
        weight: 345,
        archetype: "",
        ras: null,
    },
    {
        id: 2548,
        rank: 61,
        firstName: "Kaleb",
        lastName: "Johnson",
        position: "RB",
        school: "Iowa",
        class: "Jr.",
        height: 72,
        weight: 225,
        archetype: "",
        ras: null,
    },
    {
        id: 2549,
        rank: 59,
        firstName: "Emery",
        lastName: "Jones Jr.",
        position: "T",
        school: "LSU",
        class: "Jr.",
        height: 78,
        weight: 315,
        archetype: "",
        ras: null,
    },
    {
        id: 2550,
        rank: 34,
        firstName: "Armand",
        lastName: "Membou",
        position: "T",
        school: "Missouri",
        class: "Jr.",
        height: 75,
        weight: 314,
        archetype: "",
        ras: null,
    },
    {
        id: 2551,
        rank: 48,
        firstName: "Elic",
        lastName: "Ayomanor",
        position: "WR",
        school: "Stanford",
        class: "RS Jr.",
        height: 74,
        weight: 210,
        archetype: "",
        ras: null,
    },
    {
        id: 2552,
        rank: 45,
        firstName: "JT",
        lastName: "Tuimoloau",
        position: "ED",
        school: "Ohio State",
        class: "Sr.",
        height: 77,
        weight: 269,
        archetype: "",
        ras: null,
    },
    {
        id: 2553,
        rank: 58,
        firstName: "Quinn",
        lastName: "Ewers",
        position: "QB",
        school: "Texas",
        class: "Jr.",
        height: 74,
        weight: 210,
        archetype: "",
        ras: null,
    },
    {
        id: 2554,
        rank: 69,
        firstName: "Alfred",
        lastName: "Collins",
        position: "DI",
        school: "Texas",
        class: "Sr.",
        height: 77,
        weight: 320,
        archetype: "",
        ras: null,
    },
    {
        id: 2555,
        rank: 52,
        firstName: "Harold",
        lastName: "Fannin Jr.",
        position: "TE",
        school: "Bowling Green",
        class: "Jr.",
        height: 76,
        weight: 230,
        archetype: "",
        ras: null,
    },
    {
        id: 2556,
        rank: 64,
        firstName: "Kyle",
        lastName: "Kennard",
        position: "ED",
        school: "South Carolina",
        class: "Sr.",
        height: 77,
        weight: 254,
        archetype: "",
        ras: null,
    },
    {
        id: 2557,
        rank: 57,
        firstName: "T.J.",
        lastName: "Sanders",
        position: "DI",
        school: "South Carolina",
        class: "RS Jr.",
        height: 76,
        weight: 290,
        archetype: "",
        ras: null,
    },
    {
        id: 2558,
        rank: 51,
        firstName: "Xavier",
        lastName: "Watts",
        position: "S",
        school: "Notre Dame",
        class: "G",
        height: 72,
        weight: 203,
        archetype: "",
        ras: null,
    },
    {
        id: 2559,
        rank: 62,
        firstName: "Maxwell",
        lastName: "Hairston",
        position: "CB",
        school: "Kentucky",
        class: "Jr.",
        height: 73,
        weight: 186,
        archetype: "",
        ras: null,
    },
    {
        id: 2560,
        rank: 72,
        firstName: "Omarr",
        lastName: "Norman-Lott",
        position: "DI",
        school: "Tennessee",
        class: "Sr.",
        height: 75,
        weight: 315,
        archetype: "",
        ras: null,
    },
    {
        id: 2561,
        rank: 63,
        firstName: "Quinshon",
        lastName: "Judkins",
        position: "RB",
        school: "Ohio State",
        class: "Jr.",
        height: 72,
        weight: 219,
        archetype: "",
        ras: null,
    },
    {
        id: 2562,
        rank: 67,
        firstName: "Jared",
        lastName: "Ivey",
        position: "ED",
        school: "Ole Miss",
        class: "Sr.",
        height: 78,
        weight: 285,
        archetype: "",
        ras: null,
    },
    {
        id: 2563,
        rank: 76,
        firstName: "Jordan",
        lastName: "Burch",
        position: "DI",
        school: "Oregon",
        class: "RS Sr.",
        height: 76,
        weight: 294,
        archetype: "",
        ras: null,
    },
    {
        id: 2564,
        rank: 88,
        firstName: "Grey",
        lastName: "Zabel",
        position: "T",
        school: "North Dakota State",
        class: "Sr.",
        height: 78,
        weight: 305,
        archetype: "",
        ras: null,
    },
    {
        id: 2565,
        rank: 39,
        firstName: "Matthew",
        lastName: "Golden",
        position: "WR",
        school: "Texas",
        class: "Jr.",
        height: 72,
        weight: 195,
        archetype: "",
        ras: null,
    },
    {
        id: 2566,
        rank: 55,
        firstName: "Marcus",
        lastName: "Mbow",
        position: "T",
        school: "Purdue",
        class: "Jr.",
        height: 77,
        weight: 300,
        archetype: "",
        ras: null,
    },
    {
        id: 2567,
        rank: 53,
        firstName: "Jaxson",
        lastName: "Dart",
        position: "QB",
        school: "Ole Miss",
        class: "Sr.",
        height: 74,
        weight: 225,
        archetype: "",
        ras: null,
    },
    {
        id: 2568,
        rank: 60,
        firstName: "TreVeyon",
        lastName: "Henderson",
        position: "RB",
        school: "Ohio State",
        class: "Sr.",
        height: 70,
        weight: 208,
        archetype: "",
        ras: null,
    },
    {
        id: 2569,
        rank: 54,
        firstName: "Azareye'h",
        lastName: "Thomas",
        position: "CB",
        school: "Florida State",
        class: "Jr.",
        height: 74,
        weight: 198,
        archetype: "",
        ras: null,
    },
    {
        id: 2570,
        rank: 70,
        firstName: "Shemar",
        lastName: "Turner",
        position: "DI",
        school: "Texas A&M",
        class: "Sr.",
        height: 76,
        weight: 300,
        archetype: "",
        ras: null,
    },
    {
        id: 2571,
        rank: 66,
        firstName: "Xavier",
        lastName: "Restrepo",
        position: "WR",
        school: "Miami",
        class: "Sr.",
        height: 70,
        weight: 198,
        archetype: "",
        ras: null,
    },
    {
        id: 2572,
        rank: 77,
        firstName: "Gunnar",
        lastName: "Helm",
        position: "TE",
        school: "Texas",
        class: "Sr.",
        height: 77,
        weight: 250,
        archetype: "",
        ras: null,
    },
    {
        id: 2573,
        rank: 74,
        firstName: "Darien",
        lastName: "Porter",
        position: "CB",
        school: "Iowa State",
        class: "RS Sr.",
        height: 76,
        weight: 200,
        archetype: "",
        ras: null,
    },
    {
        id: 2574,
        rank: 68,
        firstName: "Savion",
        lastName: "Williams",
        position: "WR",
        school: "TCU",
        class: "Sr.",
        height: 77,
        weight: 225,
        archetype: "",
        ras: null,
    },
    {
        id: 2575,
        rank: 71,
        firstName: "Tate",
        lastName: "Ratledge",
        position: "G",
        school: "Georgia",
        class: "Sr.",
        height: 78,
        weight: 320,
        archetype: "",
        ras: null,
    },
    {
        id: 2576,
        rank: 65,
        firstName: "Will",
        lastName: "Howard",
        position: "QB",
        school: "Ohio State",
        class: "G",
        height: 76,
        weight: 235,
        archetype: "",
        ras: null,
    },
    {
        id: 2577,
        rank: 73,
        firstName: "Donovan",
        lastName: "Ezeiruaku",
        position: "ED",
        school: "Boston College",
        class: "Sr.",
        height: 74,
        weight: 247,
        archetype: "",
        ras: null,
    },
    {
        id: 2578,
        rank: 75,
        firstName: "Barrett",
        lastName: "Carter",
        position: "LB",
        school: "Clemson",
        class: "Sr.",
        height: 73,
        weight: 230,
        archetype: "",
        ras: null,
    },
    {
        id: 2579,
        rank: 78,
        firstName: "Jayden",
        lastName: "Higgins",
        position: "WR",
        school: "Iowa State",
        class: "Sr.",
        height: 76,
        weight: 215,
        archetype: "",
        ras: null,
    },
    {
        id: 2580,
        rank: 79,
        firstName: "Jalen",
        lastName: "Royals",
        position: "WR",
        school: "Utah State",
        class: "Sr.",
        height: 72,
        weight: 205,
        archetype: "",
        ras: null,
    },
    {
        id: 2581,
        rank: 80,
        firstName: "Mason",
        lastName: "Taylor",
        position: "TE",
        school: "LSU",
        class: "Jr.",
        height: 77,
        weight: 255,
        archetype: "",
        ras: null,
    },
    {
        id: 2582,
        rank: 81,
        firstName: "Kevin",
        lastName: "Winston Jr.",
        position: "S",
        school: "Penn State",
        class: "Jr.",
        height: 74,
        weight: 208,
        archetype: "",
        ras: null,
    },
    {
        id: 2583,
        rank: 82,
        firstName: "Lander",
        lastName: "Barton",
        position: "LB",
        school: "Utah",
        class: "Jr.",
        height: 76,
        weight: 236,
        archetype: "",
        ras: null,
    },
    {
        id: 2584,
        rank: 83,
        firstName: "Cam",
        lastName: "Skattebo",
        position: "RB",
        school: "Arizona State",
        class: "Sr.",
        height: 71,
        weight: 215,
        archetype: "",
        ras: null,
    },
    {
        id: 2585,
        rank: 84,
        firstName: "Bradyn",
        lastName: "Swinson",
        position: "ED",
        school: "LSU",
        class: "Sr.",
        height: 76,
        weight: 250,
        archetype: "",
        ras: null,
    },
    {
        id: 2586,
        rank: 85,
        firstName: "Tez",
        lastName: "Johnson",
        position: "WR",
        school: "Oregon",
        class: "Sr.",
        height: 70,
        weight: 165,
        archetype: "",
        ras: null,
    },
    {
        id: 2587,
        rank: 86,
        firstName: "Denzel",
        lastName: "Burke",
        position: "CB",
        school: "Ohio State",
        class: "Sr.",
        height: 73,
        weight: 193,
        archetype: "",
        ras: null,
    },
    {
        id: 2588,
        rank: 87,
        firstName: "Carson",
        lastName: "Schwesinger",
        position: "LB",
        school: "UCLA",
        class: "RS Jr.",
        height: 74,
        weight: 225,
        archetype: "",
        ras: null,
    },
    {
        id: 2589,
        rank: 89,
        firstName: "Dorian",
        lastName: "Strong",
        position: "CB",
        school: "Virginia Tech",
        class: "G",
        height: 73,
        weight: 185,
        archetype: "",
        ras: null,
    },
    {
        id: 2590,
        rank: 90,
        firstName: "Andrew",
        lastName: "Mukuba",
        position: "S",
        school: "Texas",
        class: "Sr.",
        height: 72,
        weight: 190,
        archetype: "",
        ras: null,
    },
    {
        id: 2591,
        rank: 91,
        firstName: "Josaiah",
        lastName: "Stewart",
        position: "ED",
        school: "Michigan",
        class: "Sr.",
        height: 73,
        weight: 245,
        archetype: "",
        ras: null,
    },
    {
        id: 2592,
        rank: 92,
        firstName: "Earnest",
        lastName: "Greene",
        position: "T",
        school: "Georgia",
        class: "RS So.",
        height: 76,
        weight: 320,
        archetype: "",
        ras: null,
    },
    {
        id: 2593,
        rank: 93,
        firstName: "Ollie",
        lastName: "Gordon II",
        position: "RB",
        school: "Oklahoma State",
        class: "Sr.",
        height: 74,
        weight: 225,
        archetype: "",
        ras: null,
    },
    {
        id: 2594,
        rank: 94,
        firstName: "Zy",
        lastName: "Alexander",
        position: "CB",
        school: "LSU",
        class: "Sr.",
        height: 74,
        weight: 194,
        archetype: "",
        ras: null,
    },
    {
        id: 2595,
        rank: 95,
        firstName: "Danny",
        lastName: "Stutsman",
        position: "LB",
        school: "Oklahoma",
        class: "Sr.",
        height: 76,
        weight: 241,
        archetype: "",
        ras: null,
    },
    {
        id: 2596,
        rank: 96,
        firstName: "Kyren",
        lastName: "Lacy",
        position: "WR",
        school: "LSU",
        class: "RS Sr.",
        height: 74,
        weight: 213,
        archetype: "",
        ras: null,
    },
    {
        id: 2597,
        rank: 97,
        firstName: "Ajani",
        lastName: "Cornelius",
        position: "T",
        school: "Oregon",
        class: "Sr.",
        height: 77,
        weight: 315,
        archetype: "",
        ras: null,
    },
    {
        id: 2598,
        rank: 98,
        firstName: "Ty",
        lastName: "Hamilton",
        position: "DI",
        school: "Ohio State",
        class: "RS Sr.",
        height: 75,
        weight: 295,
        archetype: "",
        ras: null,
    },
    {
        id: 2599,
        rank: 99,
        firstName: "Andres",
        lastName: "Borregales",
        position: "K",
        school: "Miami",
        class: "Sr.",
        height: 71,
        weight: 170,
        archetype: "",
        ras: null,
    },
    {
        id: 25100,
        rank: 100,
        firstName: "Maxen",
        lastName: "Hook",
        position: "S",
        school: "Toledo",
        class: "RS Sr.",
        height: 72,
        weight: 203,
        archetype: "",
        ras: null,
    }
];


