export const NFL_2025_Prospects = [
    {
        id: 251,
        rank: 1,
        firstName: "Shedeur",
        lastName: "Sanders",
        position: "QB",
        school: "Colorado",
        class: "Sr.",
        height: 74,
        weight: 215,
        archetype: "",
        ras: null,
    },
    {
        id: 252,
        rank: 2,
        firstName: "Cam",
        lastName: "Ward",
        position: "QB",
        school: "Miami",
        class: "Sr.",
        height: 74,
        weight: 223,
        archetype: "",
        ras: null,
    },
    {
        id: 253,
        rank: 3,
        firstName: "Travis",
        lastName: "Hunter",
        position: "CB",
        school: "Colorado",
        class: "Sr.",
        height: 73,
        weight: 185,
        archetype: "",
        ras: null,
    },
    {
        id: 254,
        rank: 4,
        firstName: "Mason",
        lastName: "Graham",
        position: "DI",
        school: "Michigan",
        class: "Jr.",
        height: 75,
        weight: 320,
        archetype: "",
        ras: null,
    },
    {
        id: 255,
        rank: 5,
        firstName: "Abdul",
        lastName: "Carter",
        position: "ED",
        school: "Penn State",
        class: "Jr.",
        height: 75,
        weight: 252,
        archetype: "",
        ras: null,
    },
    {
        id: 256,
        rank: 6,
        firstName: "Will",
        lastName: "Campbell",
        position: "T",
        school: "LSU",
        class: "Jr.",
        height: 78,
        weight: 323,
        archetype: "",
        ras: null,
    },
    {
        id: 257,
        rank: 7,
        firstName: "Will",
        lastName: "Johnson",
        position: "CB",
        school: "Michigan",
        class: "Jr.",
        height: 74,
        weight: 202,
        archetype: "",
        ras: null,
    },
    {
        id: 258,
        rank: 8,
        firstName: "Tetairoa",
        lastName: "McMillan",
        position: "WR",
        school: "Arizona",
        class: "Jr.",
        height: 75,
        weight: 212,
        archetype: "",
        ras: null,
    },
    {
        id: 259,
        rank: 9,
        firstName: "Kelvin",
        lastName: "Banks",
        position: "T",
        school: "Texas",
        class: "Jr.",
        height: 76,
        weight: 320,
        archetype: "",
        ras: null,
    },
    {
        id: 2510,
        rank: 10,
        firstName: "Mykel",
        lastName: "Williams",
        position: "ED",
        school: "Georgia",
        class: "Jr.",
        height: 77,
        weight: 265,
        archetype: "",
        ras: null,
    },
    {
        id: 2511,
        rank: 11,
        firstName: "Malaki",
        lastName: "Starks",
        position: "S",
        school: "Georgia",
        class: "Jr.",
        height: 73,
        weight: 205,
        archetype: "",
        ras: null,
    },
    {
        id: 2512,
        rank: 12,
        firstName: "Ashton",
        lastName: "Jeanty",
        position: "RB",
        school: "Boise State",
        class: "Jr.",
        height: 69,
        weight: 215,
        archetype: "",
        ras: null,
    },
    {
        id: 2513,
        rank: 13,
        firstName: "Jalon",
        lastName: "Walker",
        position: "LB",
        school: "Georgia",
        class: "Jr.",
        height: 74,
        weight: 245,
        archetype: "",
        ras: null,
    },
    {
        id: 2514,
        rank: 14,
        firstName: "James",
        lastName: "Pearce Jr.",
        position: "ED",
        school: "Tennessee",
        class: "Jr.",
        height: 77,
        weight: 243,
        archetype: "",
        ras: null,
    },
    {
        id: 2515,
        rank: 15,
        firstName: "Luther",
        lastName: "Burden III",
        position: "WR",
        school: "Missouri",
        class: "Jr.",
        height: 71,
        weight: 208,
        archetype: "",
        ras: null,
    },
    {
        id: 2516,
        rank: 16,
        firstName: "Nic",
        lastName: "Scourton",
        position: "ED",
        school: "Texas A&M",
        class: "Jr.",
        height: 76,
        weight: 285,
        archetype: "",
        ras: null,
    },
    {
        id: 2517,
        rank: 17,
        firstName: "Tyler",
        lastName: "Warren",
        position: "TE",
        school: "Penn State",
        class: "Sr.",
        height: 78,
        weight: 261,
        archetype: "",
        ras: null,
    },
    {
        id: 2518,
        rank: 18,
        firstName: "Josh",
        lastName: "Simmons",
        position: "T",
        school: "Ohio State",
        class: "Sr.",
        height: 77,
        weight: 310,
        archetype: "",
        ras: null,
    },
    {
        id: 2519,
        rank: 19,
        firstName: "Jalen",
        lastName: "Milroe",
        position: "QB",
        school: "Alabama",
        class: "RS Jr.",
        height: 74,
        weight: 225,
        archetype: "",
        ras: null,
    },
    {
        id: 2520,
        rank: 20,
        firstName: "Colston",
        lastName: "Loveland",
        position: "TE",
        school: "Michigan",
        class: "Jr.",
        height: 77,
        weight: 245,
        archetype: "",
        ras: null,
    },
    {
        id: 2521,
        rank: 21,
        firstName: "Shavon",
        lastName: "Revel Jr.",
        position: "CB",
        school: "East Carolina",
        class: "Sr.",
        height: 75,
        weight: 193,
        archetype: "",
        ras: null,
    },
    {
        id: 2522,
        rank: 22,
        firstName: "Kenneth",
        lastName: "Grant",
        position: "DI",
        school: "Michigan",
        class: "Jr.",
        height: 75,
        weight: 339,
        archetype: "",
        ras: null,
    },
    {
        id: 2523,
        rank: 23,
        firstName: "Walter",
        lastName: "Nolan",
        position: "DI",
        school: "Ole Miss",
        class: "Jr.",
        height: 75,
        weight: 305,
        archetype: "",
        ras: null,
    },
    {
        id: 2524,
        rank: 24,
        firstName: "Benjamin",
        lastName: "Morrison",
        position: "CB",
        school: "Notre Dame",
        class: "Jr.",
        height: 72,
        weight: 190,
        archetype: "",
        ras: null,
    },
    {
        id: 2525,
        rank: 25,
        firstName: "Emeka",
        lastName: "Egbuka",
        position: "WR",
        school: "Ohio State",
        class: "G",
        height: 73,
        weight: 205,
        archetype: "",
        ras: null,
    },
    {
        id: 2526,
        rank: 26,
        firstName: "Aireontae",
        lastName: "Ersery",
        position: "T",
        school: "Minnesota",
        class: "RS Sr.",
        height: 78,
        weight: 330,
        archetype: "",
        ras: null,
    },
    {
        id: 2527,
        rank: 27,
        firstName: "Derrick",
        lastName: "Harmon",
        position: "DI",
        school: "Oregon",
        class: "Jr.",
        height: 77,
        weight: 310,
        archetype: "",
        ras: null,
    },
    {
        id: 2528,
        rank: 28,
        firstName: "Tyler",
        lastName: "Booker",
        position: "G",
        school: "Alabama",
        class: "Jr.",
        height: 77,
        weight: 325,
        archetype: "",
        ras: null,
    },
    {
        id: 2529,
        rank: 29,
        firstName: "Shemar",
        lastName: "Stewart",
        position: "ED",
        school: "Texas A&M",
        class: "Jr.",
        height: 78,
        weight: 290,
        archetype: "",
        ras: null,
    },
    {
        id: 2530,
        rank: 30,
        firstName: "Jahdae",
        lastName: "Barron",
        position: "CB",
        school: "Texas",
        class: "Sr.",
        height: 71,
        weight: 200,
        archetype: "",
        ras: null,
    },
    {
        id: 2531,
        rank: 31,
        firstName: "Cameron",
        lastName: "Williams",
        position: "T",
        school: "Texas",
        class: "Jr.",
        height: 77,
        weight: 335,
        archetype: "",
        ras: null,
    },
    {
        id: 2532,
        rank: 32,
        firstName: "Josh",
        lastName: "Conerly Jr.",
        position: "T",
        school: "Oregon",
        class: "Jr.",
        height: 76,
        weight: 315,
        archetype: "",
        ras: null,
    },
    {
        id: 2533,
        rank: 33,
        firstName: "Mike",
        lastName: "Green",
        position: "ED",
        school: "Marshall",
        class: "RS So.",
        height: 76,
        weight: 248,
        archetype: "",
        ras: null,
    },
    {
        id: 2534,
        rank: 34,
        firstName: "Tyleik",
        lastName: "Williams",
        position: "DI",
        school: "Ohio State",
        class: "Sr.",
        height: 75,
        weight: 327,
        archetype: "",
        ras: null,
    },
    {
        id: 2535,
        rank: 35,
        firstName: "Jihaad",
        lastName: "Campbell",
        position: "LB",
        school: "Alabama",
        class: "Jr.",
        height: 75,
        weight: 244,
        archetype: "",
        ras: null,
    },
    {
        id: 2536,
        rank: 36,
        firstName: "Princely",
        lastName: "Umanmielen",
        position: "CB",
        school: "Ole Miss",
        class: "Sr.",
        height: 76,
        weight: 255,
        archetype: "",
        ras: null,
    },
    {
        id: 2537,
        rank: 37,
        firstName: "Wyatt",
        lastName: "Milum",
        position: "T",
        school: "West Virginia",
        class: "Sr.",
        height: 78,
        weight: 317,
        archetype: "",
        ras: null,
    },
    {
        id: 2538,
        rank: 38,
        firstName: "Landon",
        lastName: "Jackson",
        position: "ED",
        school: "Arkansas",
        class: "Sr.",
        height: 79,
        weight: 280,
        archetype: "",
        ras: null,
    },
    {
        id: 2539,
        rank: 39,
        firstName: "Jonah",
        lastName: "Savaiinaea",
        position: "T",
        school: "Arizona",
        class: "Jr.",
        height: 77,
        weight: 336,
        archetype: "",
        ras: null,
    },
    {
        id: 2540,
        rank: 40,
        firstName: "Trey",
        lastName: "Amos",
        position: "CB",
        school: "Ole Miss",
        class: "Sr.",
        height: 73,
        weight: 190,
        archetype: "",
        ras: null,
    },
    {
        id: 2541,
        rank: 41,
        firstName: "Isaiah",
        lastName: "Bond",
        position: "WR",
        school: "Texas",
        class: "Jr.",
        height: 71,
        weight: 180,
        archetype: "",
        ras: null,
    },
    {
        id: 2542,
        rank: 42,
        firstName: "Nick",
        lastName: "Emmanwori",
        position: "S",
        school: "South Carolina",
        class: "Jr.",
        height: 75,
        weight: 227,
        archetype: "",
        ras: null,
    },
    {
        id: 2543,
        rank: 43,
        firstName: "Tre",
        lastName: "Harris",
        position: "WR",
        school: "Ole Miss",
        class: "Sr.",
        height: 75,
        weight: 210,
        archetype: "",
        ras: null,
    },
    {
        id: 2544,
        rank: 44,
        firstName: "Omarion",
        lastName: "Hampton",
        position: "RB",
        school: "North Carolina",
        class: "Jr.",
        height: 73,
        weight: 220,
        archetype: "",
        ras: null,
    },
    {
        id: 2545,
        rank: 45,
        firstName: "Jack",
        lastName: "Sawyer",
        position: "ED",
        school: "Ohio State",
        class: "Sr.",
        height: 77,
        weight: 260,
        archetype: "",
        ras: null,
    },
    {
        id: 2546,
        rank: 46,
        firstName: "Donovan",
        lastName: "Jackson",
        position: "T",
        school: "Ohio State",
        class: "Sr.",
        height: 76,
        weight: 320,
        archetype: "",
        ras: null,
    },
    {
        id: 2547,
        rank: 47,
        firstName: "Deone",
        lastName: "Walker",
        position: "DI",
        school: "Kentucky",
        class: "Jr.",
        height: 78,
        weight: 345,
        archetype: "",
        ras: null,
    },
    {
        id: 2548,
        rank: 48,
        firstName: "Kaleb",
        lastName: "Johnson",
        position: "RB",
        school: "Iowa",
        class: "Jr.",
        height: 72,
        weight: 225,
        archetype: "",
        ras: null,
    },
    {
        id: 2549,
        rank: 49,
        firstName: "Emery",
        lastName: "Jones Jr.",
        position: "T",
        school: "LSU",
        class: "Jr.",
        height: 78,
        weight: 315,
        archetype: "",
        ras: null,
    },
    {
        id: 2550,
        rank: 50,
        firstName: "Armand",
        lastName: "Membou",
        position: "T",
        school: "Missouri",
        class: "Jr.",
        height: 75,
        weight: 314,
        archetype: "",
        ras: null,
    },
    {
        id: 2551,
        rank: 51,
        firstName: "Elic",
        lastName: "Ayomanor",
        position: "WR",
        school: "Stanford",
        class: "RS Jr.",
        height: 74,
        weight: 210,
        archetype: "",
        ras: null,
    },
    {
        id: 2552,
        rank: 52,
        firstName: "JT",
        lastName: "Tuimoloau",
        position: "ED",
        school: "Ohio State",
        class: "Sr.",
        height: 77,
        weight: 269,
        archetype: "",
        ras: null,
    },
    {
        id: 2553,
        rank: 53,
        firstName: "Quinn",
        lastName: "Ewers",
        position: "QB",
        school: "Texas",
        class: "Jr.",
        height: 74,
        weight: 210,
        archetype: "",
        ras: null,
    }
];


