export const NFL_2023_Prospects = [
  {
    id: 100000,
    rank: 1,
    firstName: "Bryce",
    lastName: "Young",
    position: "QB",
    class: "Jr.",
    height: 70,
    weight: 204,
    ras: null,
    school: "Alabama",
    img: "https://media.pff.com/player-photos/nfl/123943.webp",
    desc: ["Playmaker", "Accurate"],
    archetype: "Playmaker",
    strengths: ["Accuracy", "Football IQ", "Improvisation", "Poise"],
    weaknesses: ["Size"],
  },
  {
    id: 1,
    rank: 4,
    firstName: "Jalen",
    lastName: "Carter",
    position: "DI",
    class: "Jr.",
    height: 75,
    weight: 300,
    ras: null,
    school: "Georgia",
    img: "https://media.pff.com/player-photos/nfl/124019.webp",
    desc: ["Elite Athlete", "Total Package"],
    archetype: "All-Around",
    strengths: ["Power", "Body Control", "Upside"],
    weaknesses: ["None"],
  },
  {
    id: 2,
    rank: 12,
    firstName: "Will",
    lastName: "Levis",
    position: "QB",
    class: "Sr.",
    height: 75,
    weight: 232,
    ras: null,
    school: "Kentucky",
    img: "https://media.pff.com/player-photos/nfl/83542.webp",
    desc: ["Strong Arm"],
    archetype: "Gunslinger",
    strengths: ["Arm Strength", "Size", "Upside"],
    weaknesses: ["Processsing", "Decision-Making"],
  },
  {
    id: 3,
    rank: 2,
    firstName: "Will",
    lastName: "Anderson Jr.",
    position: "ED",
    class: "Jr.",
    height: 76,
    weight: 243,
    ras: null,
    school: "Alabama",
    img: "https://media.pff.com/player-photos/nfl/123903.webp",
    desc: ["Elite Athlete", "Total Package"],
    archetype: "All-Around",
    strengths: ["Athleticism", "Upside"],
    weaknesses: ["None"],
  },
  {
    id: 4,
    rank: 3,
    firstName: "C.J.",
    lastName: "Stroud",
    position: "QB",
    class: "Jr.",
    height: 75,
    weight: 215,
    ras: null,
    school: "Ohio State",
    img: "https://media.pff.com/player-photos/nfl/129759.webp",
    desc: ["Pocket Passer", "Accurate"],
    archetype: "Pocket Passer",
    strengths: ["Accuracy", "Production"],
    weaknesses: ["Poise under Pressure"],
  },
  {
    id: 5,
    rank: 17,
    firstName: "Myles",
    lastName: "Murphy",
    position: "ED",
    class: "Jr.",
    height: 77,
    weight: 275,
    ras: 9.71,
    school: "Clemson",
    img: "https://media.pff.com/player-photos/nfl/122154.webp",
    desc: ["Elite Athlete", "Project"],
    archetype: "Power Rusher",
    strengths: ["Upside", "Athleticism"],
    weaknesses: ["Raw"],
  },
  {
    id: 6,
    rank: 8,
    firstName: "Tyree",
    lastName: "Wilson",
    position: "ED",
    class: "Sr.",
    height: 78,
    weight: 275,
    ras: null,
    school: "Texas Tech",
    img: "https://thedraftnetwork.com/wp-content/uploads/2022/11/USATSI_18696881_168386526_lowres.png",
    desc: ["Elite Athlete", "Versatile", "Long Arms"],
    archetype: "Power Rusher",
    strengths: ["Size", "Length", "Power"],
    weaknesses: ["Technique"],
  },
  {
    id: 7,
    rank: 28,
    firstName: "Bryan",
    lastName: "Bresee",
    position: "DI",
    class: "So.",
    height: 77,
    weight: 300,
    ras: 9.59,
    school: "Clemson",
    img: "https://media.pff.com/player-photos/nfl/122142.webp",
    desc: ["Elite Athlete", "Powerful"],
    archetype: "3 Tech",
    strengths: ["Athleticism", "Power"],
    weaknesses: ["Durability"],
  },
  {
    id: 8,
    rank: 13,
    firstName: "Paris",
    lastName: "Johnson Jr.",
    position: "T",
    class: "Jr.",
    height: 78,
    weight: 310,
    ras: null,
    school: "Ohio State",
    img: "https://media.pff.com/player-photos/nfl/129749.webp",
    desc: ["Elite Athlete", "Project"],
    archetype: "",
    strengths: ["Upside"],
    weaknesses: ["Technique"],
  },
  {
    id: 9,
    rank: 24,
    firstName: "Brian",
    lastName: "Branch",
    position: "S",
    class: "Jr.",
    height: 72,
    weight: 193,
    ras: 5.25,
    school: "Alabama",
    img: "https://media.pff.com/player-photos/nfl/123907.webp",
    desc: ["Slot", "Cerebral", "Good Tackler"],
    archetype: "Box",
    strengths: ["Football IQ", "Run Defense", "Versatility"],
    weaknesses: ["Man Coverage"],
  },
  {
    id: 10,
    rank: 7,
    firstName: "Anthony",
    lastName: "Richardson",
    position: "QB",
    class: "So.",
    height: 76,
    weight: 232,
    ras: 10,
    school: "Florida",
    img: "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse1.mm.bing.net%2Fth%3Fid%3DOIP.gaXz8ax8M21VkHj4e7ON8AHaFY%26pid%3DApi&f=1&ipt=aa157ec26dc61577c49649a36bff8af365c8d0f2b0b23ba22de29390fe68161d&ipo=images",
    desc: ["Elite Athlete", "Strong Arm", "Project"],
    archetype: "Dual Threat",
    strengths: ["Upside", "Arm Strength", "Athleticism"],
    weaknesses: ["Accuracy", "Raw"],
  },
  {
    id: 11,
    rank: 5,
    firstName: "Devon",
    lastName: "Witherspoon",
    position: "CB",
    class: "Jr.",
    height: 72,
    weight: 180,
    ras: null,
    school: "Illinois",
    img: "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse3.mm.bing.net%2Fth%3Fid%3DOIP.-rWowyXfflk4C4sKIPQYwQHaFY%26pid%3DApi&f=1&ipt=3922e1393dc98f26d6ccbde527ead2c2e9719703f82b647ddf8ec932acf5c541&ipo=images",
    desc: ["Man-to-man", "Feisty", "Playmaker"],
    archetype: "Man-to-man",
    strengths: ["Feisty", "Ball Skills", "Processing Speed"],
    weaknesses: ["Size"],
  },
  {
    id: 12,
    rank: 11,
    firstName: "Peter",
    lastName: "Skoronski",
    position: "T",
    class: "Jr.",
    height: 76,
    weight: 313,
    arms: 32.3,
    ras: 9.31,
    school: "Northwestern",
    img: "https://media.pff.com/player-photos/nfl/129737.webp",
    desc: ["Versatile", "Technician", "Short Arms"],
    archetype: "",
    strengths: ["Technique", "Football IQ", "Versatility"],
    weaknesses: ["Arm Length"],
  },
  {
    id: 13,
    rank: 6,
    firstName: "Christian",
    lastName: "Gonzalez",
    position: "CB",
    class: "So.",
    height: 74,
    weight: 201,
    ras: 9.95,
    school: "Oregon",
    img: "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse2.mm.bing.net%2Fth%3Fid%3DOIP.k_kFAx_ZLhg5nTRlgeMljAHaFY%26pid%3DApi&f=1&ipt=aa0d31b921b2ece41b5dae2424313c341798329a7c0f74dd59db8ff571aabe75&ipo=images",
    desc: ["Long Arms", "Good Instincts"],
    archetype: "Man-to-man",
    strengths: ["Athleticism", "Length", "Instincts"],
    weaknesses: ["Play Strength"],
  },
  {
    id: 14,
    rank: 21,
    firstName: "Quentin",
    lastName: "Johnston",
    position: "WR",
    class: "Jr.",
    height: 76,
    weight: 215,
    ras: 8.67,
    school: "TCU",
    img: "https://media.pff.com/player-photos/nfl/123085.webp",
    desc: ["Big Bodied", "Explosive"],
    archetype: "X",
    strengths: ["Explosiveness", "Size", "Speed"],
    weaknesses: ["Consistency"],
  },
  {
    id: 15,
    rank: 15,
    firstName: "Lukas",
    lastName: "Van Ness",
    position: "ED",
    class: "So.",
    height: 77,
    weight: 269,
    ras: 9.39,
    school: "Iowa",
    img: "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse1.mm.bing.net%2Fth%3Fid%3DOIP.GtpxVP14wxNM849RbKwYcgHaHa%26pid%3DApi&f=1&ipt=685e18c4579d6e88ee3558a783e1cb53923afde106c9405dfd1fc91b19b62ca5&ipo=images",
    desc: ["Power Rusher"],
    archetype: "Power Rusher",
    strengths: ["Strength", "Motor"],
    weaknesses: ["Inexperience"],
  },
  {
    id: 16,
    rank: 22,
    firstName: "Michael",
    lastName: "Mayer",
    position: "TE",
    class: "Jr.",
    height: 76,
    weight: 249,
    ras: 7.65,
    school: "Notre Dame",
    img: "https://media.pff.com/player-photos/nfl/122906.webp",
    desc: ["Possession", "Good Ball Skills"],
    archetype: "Possession",
    strengths: ["Ball Skills", "Blocking"],
    weaknesses: ["Explosiveness"],
  },
  {
    id: 17,
    rank: 9,
    firstName: "Bijan",
    lastName: "Robinson",
    position: "RB",
    class: "Jr.",
    height: 71,
    weight: 215,
    ras: 9.83,
    school: "Texas",
    img: "https://media.pff.com/player-photos/nfl/123126.webp",
    archetype: "Workhorse",
    strengths: ["Explosiveness", "Strength", "Receiving"],
    weaknesses: ["None"],
  },
  {
    id: 18,
    rank: 25,
    firstName: "Zay",
    lastName: "Flowers",
    position: "WR",
    class: "Sr.",
    height: 70,
    weight: 172,
    ras: 8.3,
    school: "Boston College",
    img: "https://media.pff.com/player-photos/nfl/97268.webp",
    desc: ["Slot", "Electric"],
    archetype: "Slot",
    strengths: ["Explosiveness", "Route Running", "YAC"],
    weaknesses: ["Size", "Drops"],
  },
  {
    id: 19,
    rank: 10,
    firstName: "Jaxon",
    lastName: "Smith-Njigba",
    position: "WR",
    class: "Jr.",
    height: 72,
    weight: 198,
    ras: 8.29,
    school: "Ohio State",
    img: "https://media.pff.com/player-photos/nfl/129758.webp",
    desc: ["Route Runner", "Body Control", "Sure-handed"],
    archetype: "Route Runner",
    strengths: ["Route Running", "Hands", "Body Control"],
    weaknesses: ["Explosiveness"],
  },
  {
    id: 20,
    rank: 32,
    firstName: "Anton",
    lastName: "Harrison",
    position: "T",
    class: "Jr.",
    height: 77,
    weight: 315,
    ras: 7.66,
    school: "Oklahoma",
    img: "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse1.mm.bing.net%2Fth%3Fid%3DOIP.xCBsrlO4lD8WxZJR066WzgHaFY%26pid%3DApi&f=1&ipt=fdb07cfb03945a009f8434c89e50d898fce2513fb853d7c98dc469ffee5cfca0&ipo=images",
    desc: ["Pass Protector", "Strong Hands"],
    archetype: "Pass Protector",
    strengths: ["Pass Blocking", "Length", "Agility"],
    weaknesses: ["Strength"],
  },
  {
    id: 21,
    rank: 16,
    firstName: "Nolan",
    lastName: "Smith",
    position: "ED",
    class: "Sr.",
    height: 75,
    weight: 235,
    ras: 9.25,
    school: "Georgia",
    img: "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse1.mm.bing.net%2Fth%3Fid%3DOIP.YcHt4lLNjRhlTtSZnyQzFgHaFY%26pid%3DApi&f=1&ipt=cc3843e7ebc966a1c481e7f4363bc57e8ae335a0ad3707bb1d527d67c0724d04&ipo=images",
    desc: ["Elite Athlete", "Project"],
    archetype: "Speed Rusher",
    strengths: ["Upside", "Speed", "Competitiveness"],
    weaknesses: ["Raw"],
  },
  {
    id: 22,
    rank: 23,
    firstName: "Jordan",
    lastName: "Addison",
    position: "WR",
    class: "Jr.",
    height: 72,
    weight: 175,
    ras: 5.88,
    school: "USC",
    img: "https://media.pff.com/player-photos/nfl/123000.webp",
    desc: ["Route Runner", "Body Control"],
    archetype: "Route Runner",
    strengths: ["Route Running", "Body Control"],
    weaknesses: ["Size", "Drops"],
  },
  {
    id: 23,
    rank: 18,
    firstName: "Broderick",
    lastName: "Jones",
    position: "T",
    class: "RS So.",
    height: 76,
    weight: 310,
    ras: 9.59,
    school: "Georgia",
    img: "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse3.mm.bing.net%2Fth%3Fid%3DOIP.EcCH5xj7B192vsZxhLvbqAHaFY%26pid%3DApi&f=1&ipt=c671f175caae1cfae4750d6bbc5e41d6e0e591c3ba2673083d20f3e79080222a&ipo=images",
    desc: [],
    archetype: "",
    strengths: ["Athleticism", "Upside"],
    weaknesses: ["Inconsistency"],
  },
  {
    id: 24,
    rank: 35,
    firstName: "Cam",
    lastName: "Smith",
    position: "CB",
    class: "RS Jr.",
    height: 72,
    weight: 188,
    ras: 9.68,
    school: "South Carolina",
    img: "https://media.pff.com/player-photos/nfl/98837.webp",
    archetype: "Slot",
    strengths: ["Ball Skills", "Physicality"],
    weaknesses: ["Tackling"],
  },
  {
    id: 25,
    rank: 14,
    firstName: "Joey",
    lastName: "Porter Jr.",
    position: "CB",
    class: "RS Jr.",
    height: 74,
    weight: 198,
    ras: 9.72,
    school: "Penn State",
    img: "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse4.mm.bing.net%2Fth%3Fid%3DOIP.6LeeWLro2y1qf7t0VuOMKAHaFY%26pid%3DApi&f=1&ipt=1baaa67efdace80f6b13d8158a0034f686e0983f50321df38a944cad30e4598a&ipo=images",
    archetype: "Man-to-man",
    strengths: ["Press", "Ball Skills"],
    weaknesses: ["Grabbiness"],
  },
  {
    id: 26,
    rank: 29,
    firstName: "O'Cyrus",
    lastName: "Torrence",
    position: "G",
    class: "Jr.",
    height: 77,
    weight: 330,
    arms: 33.9,
    ras: 5.97,
    school: "Florida",
    img: "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse4.mm.bing.net%2Fth%3Fid%3DOIP.VQKs5AoSHjbg9oDPg6kVzAAAAA%26pid%3DApi&f=1&ipt=e23daf20a9c1dc783278d3170043986063ca224d9e429fe084dd5c40c20e07ca&ipo=images",
    archetype: "Run Blocker",
    strengths: ["Physicality", "Run Blocking", "Anchor"],
    weaknesses: ["Lateral Agility"],
  },
  // {
  //   id: 27,
  //   rank: 126,
  //   firstName: "Tanner",
  //   lastName: "McKee",
  //   position: "QB",
  //   class: "Jr.",
  //   height: 78,
  //   weight: 230,
  //   ras: 8.69,
  //   school: "Stanford",
  //   img: "https://media.pff.com/player-photos/nfl/131770.webp",
  //   archetype: "Pocket Passer",
  //   strengths: ["Arm Strength", "Accuracy"],
  //   weaknesses: ["Pocket Awareness", "Playmaking"],
  // },
  {
    id: 28,
    rank: 48,
    firstName: "Trenton",
    lastName: "Simpson",
    position: "LB",
    class: "Jr.",
    height: 75,
    weight: 230,
    ras: 9.83,
    school: "Clemson",
    img: "https://media.pff.com/player-photos/nfl/122157.webp",
    archetype: "WLB",
    strengths: ["Explosiveness"],
    weaknesses: ["Run Defense"],
  },
  {
    id: 29,
    rank: 50,
    firstName: "Luke",
    lastName: "Musgrave",
    position: "TE",
    class: "Jr.",
    height: 78,
    weight: 253,
    ras: 9.77,
    school: "Oregon State",
    img: "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse1.mm.bing.net%2Fth%3Fid%3DOIP.MLTA2khYaL-C8CnbmtDg-AHaHa%26pid%3DApi&f=1&ipt=589fb7702bff6080d69d1a76240e441121fe30227bfb78e7a17539dfe57c6db6&ipo=images",
    archetype: "Vertical Threat",
    strengths: ["Athleticism", "Upside"],
    weaknesses: ["Route Running"],
  },
  {
    id: 30,
    rank: 68,
    firstName: "Siaki",
    lastName: "Ika",
    position: "DI",
    class: "Jr.",
    height: 76,
    weight: 358,
    ras: 2.75,
    school: "Baylor",
    img: "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse1.mm.bing.net%2Fth%3Fid%3DOIP.Wh4Ov64e5xpgWQO9hKacnwHaFY%26pid%3DApi&f=1&ipt=e561230bf33e11ba647a904fb93cf8e4cb57a2830c0c363c9cd3120693daab20&ipo=images",
    archetype: "Nose Tackle",
    strengths: ["Strength"],
    weaknesses: ["Weight"],
  },
  {
    id: 31,
    rank: 47,
    firstName: "BJ",
    lastName: "Ojulari",
    position: "ED",
    class: "Jr.",
    height: 75,
    weight: 250,
    ras: 4.9,
    school: "LSU",
    img: "https://media.pff.com/player-photos/nfl/124105.webp",
    archetype: "Pure Pass Rusher",
    strengths: ["Pass Rush Plan"],
    weaknesses: ["Strength"],
  },
  {
    id: 32,
    rank: 83,
    firstName: "Andre",
    lastName: "Carter II",
    position: "ED",
    class: "Sr.",
    height: 79,
    weight: 260,
    ras: 6.27,
    school: "Army",
    img: "https://media.pff.com/player-photos/nfl/102780.webp",
    archetype: "",
    strengths: ["Size"],
    weaknesses: ["Muscle Mass", "Flexibility"],
  },
  {
    id: 33,
    rank: 27,
    firstName: "Dalton",
    lastName: "Kincaid",
    position: "TE",
    class: "Sr.",
    height: 76,
    weight: 240,
    ras: null,
    school: "Utah",
    img: "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse2.explicit.bing.net%2Fth%3Fid%3DOIP.paNOE-T8E-cm5X3WQn2akAHaFY%26pid%3DApi&f=1&ipt=b516e2b0231386c6c34a761cdd4d0c8d2973a404bcae8c4a5de8b280e15ac08a&ipo=images",
    archetype: "Vertical Threat",
    strengths: ["Ball Skills", "Body Control", "Hands", "Route Running"],
    weaknesses: ["Blocking"],
  },
  {
    id: 34,
    rank: 26,
    firstName: "Calijah",
    lastName: "Kancey",
    position: "DI",
    class: "RS Jr.",
    height: 72,
    weight: 280,
    ras: 9.61,
    school: "Pittsburgh",
    img: "https://media.pff.com/player-photos/nfl/99822.webp",
    archetype: "3 Tech",
    strengths: ["Twitch", "Pass Rushing", "Motor"],
    weaknesses: ["Size"],
  },
  {
    id: 35,
    rank: 20,
    firstName: "Deonte",
    lastName: "Banks",
    position: "CB",
    class: "RS Jr.",
    height: 74,
    weight: 205,
    ras: 10,
    school: "Maryland",
    img: "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse1.mm.bing.net%2Fth%3Fid%3DOIP.OPpaC_z4XihbqiV_k4ExYgAAAA%26pid%3DApi&f=1&ipt=d4fbf4ff4826671680fb7761b3efe906be9cf5ed75e297d9eb20d917cb7f41e7&ipo=images",
    archetype: "Versatile",
    strengths: ["Length", "Sticky Coverage"],
    weaknesses: ["Technique"],
  },
  {
    id: 36,
    rank: 33,
    firstName: "Will",
    lastName: "McDonald IV",
    position: "ED",
    class: "RS Sr.",
    height: 75,
    weight: 236,
    ras: 9.66,
    school: "Iowa State",
    img: "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fwww.ourlads.com%2Fimages%2Fplayers%2Fncaa%2FMCD222153.png&f=1&nofb=1&ipt=14e6db2f907974f8160087e19a0f86277413dd750e9bfc63264f19b774363d5d&ipo=images",
    archetype: "Speed Rusher",
    strengths: ["Explosiveness", "Length"],
    weaknesses: ["Strength"],
  },
  {
    id: 37,
    rank: 58,
    firstName: "Antonio",
    lastName: "Johnson",
    position: "S",
    class: "Jr.",
    height: 75,
    weight: 195,
    ras: 4.78,
    school: "Texas A&M",
    img: "https://media.pff.com/player-photos/nfl/124326.webp",
    archetype: "Box",
    strengths: ["Processing", "Tackling"],
    weaknesses: ["Ball Skills"],
  },
  {
    id: 38,
    rank: 34,
    firstName: "Mazi",
    lastName: "Smith",
    position: "DI",
    class: "Sr.",
    height: 75,
    weight: 337,
    ras: null,
    school: "Michigan",
    img: "https://media.pff.com/player-photos/nfl/101419.webp",
    archetype: "Nose Tackle",
    strengths: ["Run Defense", "Strength"],
    weaknesses: ["Hand Usage"],
  },
  {
    id: 39,
    rank: 77,
    firstName: "Nathaniel",
    lastName: "Dell",
    position: "WR",
    class: "Jr.",
    height: 70,
    weight: 165,
    ras: 5.81,
    school: "Houston",
    img: "https://media.pff.com/player-photos/nfl/78874.webp",
    archetype: "Slot/Gadget",
    strengths: ["Shiftiness", "YAC"],
    weaknesses: ["Size"],
  },
  {
    id: 40,
    rank: 69,
    firstName: "Daiyan",
    lastName: "Henley",
    position: "LB",
    class: "RS Sr.",
    height: 74,
    weight: 232,
    ras: 8.06,
    school: "Washington State",
    img: "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse4.mm.bing.net%2Fth%3Fid%3DOIP.6PQIZ5MzisaZqgCL4-XgTwAAAA%26pid%3DApi&f=1&ipt=0ee7575fcd6b315e5a7d8a00c3e1c95b570de09ebd2742afeffc873ddb9a1b70&ipo=images",
    archetype: "WLB",
    strengths: ["Twitchiness"],
    weaknesses: ["Zone Coverage"],
  },
  {
    id: 41,
    rank: 71,
    firstName: "Tyrique",
    lastName: "Stevenson",
    position: "CB",
    class: "Jr.",
    height: 72,
    weight: 214,
    ras: 8.89,
    school: "Miami",
    img: "https://media.pff.com/player-photos/nfl/97562.webp",
    archetype: "Man-to-man",
    strengths: ["Length", "Balance"],
    weaknesses: ["Tackling"],
  },
  {
    id: 42,
    rank: 49,
    firstName: "Josh",
    lastName: "Downs",
    position: "WR",
    class: "Jr.",
    height: 70,
    weight: 175,
    ras: 8.97,
    school: "North Carolina",
    img: "https://media.pff.com/player-photos/nfl/122832.webp",
    archetype: "Slot",
    strengths: ["Footwork", "Explosiveness", "YAC"],
    weaknesses: ["Size"],
  },
  {
    id: 43,
    rank: 39,
    firstName: "Jalin",
    lastName: "Hyatt",
    position: "WR",
    class: "Jr.",
    height: 73,
    weight: 180,
    ras: 8.76,
    school: "Tennessee",
    img: "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fs3media.247sports.com%2FUploads%2FAssets%2F216%2F929%2F9929216.jpeg%3Ffit%3Dcrop%26width%3D100&f=1&nofb=1&ipt=3b09d9e56360d6d7246a15355ce6b124aa8d974eb864968cf1955dccac0ff615&ipo=images",
    archetype: "Deep Threat",
    strengths: ["Speed"],
    weaknesses: ["Route Running", "Defeating Press"],
  },
  {
    id: 44,
    rank: 30,
    firstName: "Jahmyr",
    lastName: "Gibbs",
    position: "RB",
    class: "Jr.",
    height: 71,
    weight: 200,
    ras: 8.04,
    school: "Alabama",
    img: "https://media.pff.com/player-photos/nfl/122474.webp",
    archetype: "Receiving Back",
    strengths: ["Shiftiness", "Explosiveness", "Pass Catching"],
    weaknesses: ["Size"],
  },
  {
    id: 45,
    rank: 38,
    firstName: "Kelee",
    lastName: "Ringo",
    position: "CB",
    class: "RS So.",
    height: 74,
    weight: 210,
    ras: 8.22,
    school: "Georgia",
    img: "https://media.pff.com/player-photos/nfl/124035.webp",
    archetype: "Zone",
    strengths: ["Size", "Speed"],
    weaknesses: ["Fluidity", "Anticipation"],
  },
  {
    id: 46,
    rank: 40,
    firstName: "Drew",
    lastName: "Sanders",
    position: "LB",
    class: "Jr.",
    height: 77,
    weight: 232,
    ras: 8.96,
    school: "Arkansas",
    img: "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse3.mm.bing.net%2Fth%3Fid%3DOIP.JW_cciyE5bDbZ2PXiYTJcgHaFY%26pid%3DApi&f=1&ipt=1955e1420dbeec266f45a9e94fbc0c11cfb8c5d677e810a8bfee7f82b2d5ec6e&ipo=images",
    archetype: "MLB",
    strengths: ["Blitzing"],
    weaknesses: ["Tackling"],
  },
  {
    id: 47,
    rank: 31,
    firstName: "Emmanuel",
    lastName: "Forbes",
    position: "CB",
    class: "Jr.",
    height: 72,
    weight: 180,
    ras: 9.23,
    school: "Mississippi State",
    img: "https://media.pff.com/player-photos/nfl/124166.webp",
    archetype: "Versatile",
    strengths: ["Ball Skills", "Instincts"],
    weaknesses: ["Muscle Mass", "Overly Aggressive"],
  },
  {
    id: 48,
    rank: 36,
    firstName: "Darnell",
    lastName: "Washington",
    position: "TE",
    class: "Jr.",
    height: 79,
    weight: 264,
    ras: 9.88,
    school: "Georgia",
    img: "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse4.mm.bing.net%2Fth%3Fid%3DOIP.cSbZpzOfbWPeh0m6yEROKgHaFY%26pid%3DApi&f=1&ipt=d918ea528bcde22a9b2b59bf62c4791e2baa596b9608b935a901766861092cd6&ipo=images",
    archetype: "Blocking",
    strengths: ["Size", "Blocking"],
    weaknesses: ["Separation"],
  },
  {
    id: 49,
    rank: 54,
    firstName: "Isaiah",
    lastName: "Foskey",
    position: "ED",
    class: "Sr.",
    height: 77,
    weight: 265,
    ras: 9.6,
    school: "Notre Dame",
    img: "https://media.pff.com/player-photos/nfl/102728.webp",
    archetype: "Pure Pass Rusher",
    strengths: ["Explosiveness", "Pass Rush Plan"],
    weaknesses: ["Run Defense"],
  },
  {
    id: 50,
    rank: 43,
    firstName: "Dawand",
    lastName: "Jones",
    position: "T",
    class: "Sr.",
    height: 80,
    weight: 350,
    ras: null,
    school: "Ohio State",
    img: "https://media.pff.com/player-photos/nfl/101550.webp",
    archetype: "Run Blocker",
    strengths: ["LENGTH", "Strength"],
    weaknesses: ["Agility"],
  },
  {
    id: 51,
    rank: 19,
    firstName: "Darnell",
    lastName: "Wright",
    position: "T",
    class: "Sr.",
    height: 78,
    weight: 335,
    ras: 9.78,
    school: "Tennessee",
    img: "https://media.pff.com/player-photos/nfl/98480.webp",
    archetype: "Pass Protector",
    strengths: ["Power", "Length"],
    weaknesses: ["Balance"],
  },
  {
    id: 52,
    rank: 45,
    firstName: "Keion",
    lastName: "White",
    position: "ED",
    class: "RS Sr.",
    height: 77,
    weight: 286,
    ras: 9.92,
    school: "Georgia Tech",
    img: "https://thedraftnetwork.com/wp-content/uploads/2022/12/WhiteK_082721_DK-46-cropped-742x1024-1.png",
    archetype: "All-Around",
    strengths: ["Athleticism", "Versatility"],
    weaknesses: ["Pass Rush Plan"],
  },
  {
    id: 53,
    rank: 61,
    firstName: "Clark",
    lastName: "Phillips III",
    position: "CB",
    class: "So.",
    height: 70,
    weight: 183,
    ras: 5.56,
    school: "Utah",
    img: "https://media.pff.com/player-photos/nfl/131871.webp",
    archetype: "Man-to-man",
    strengths: ["Ball Skills", "Instincts", "Toughness"],
    weaknesses: ["Tackling"],
  },
  {
    id: 54,
    rank: 42,
    firstName: "Jack",
    lastName: "Campbell",
    position: "LB",
    class: "Sr.",
    height: 77,
    weight: 246,
    ras: 9.98,
    school: "Iowa",
    img: "https://media.pff.com/player-photos/nfl/101515.webp",
    archetype: "MLB",
    strengths: ["Processing", "Run Defense"],
    weaknesses: ["Range"],
  },
  {
    id: 55,
    rank: 46,
    firstName: "Felix",
    lastName: "Anudike-Uzomah",
    position: "ED",
    class: "Jr.",
    height: 76,
    weight: 255,
    ras: 8.72,
    school: "Kansas State",
    img: "https://media.pff.com/player-photos/nfl/122582.webp",
    archetype: "All-Around",
    strengths: ["Bend", "Pass Rush Plan", "Motor"],
    weaknesses: ["Setting the Edge"],
  },
  {
    id: 56,
    rank: 55,
    firstName: "Derick",
    lastName: "Hall",
    position: "ED",
    class: "Sr.",
    height: 75,
    weight: 256,
    ras: 9.4,
    school: "Auburn",
    img: "https://media.pff.com/player-photos/nfl/98130.webp",
    archetype: "Run Defender",
    strengths: ["Run Defense", "Burst"],
    weaknesses: ["Pass Rushing"],
  },
  {
    id: 57,
    rank: 63,
    firstName: "Cody",
    lastName: "Mauch",
    position: "G",
    class: "Sr.",
    height: 77,
    weight: 302,
    ras: 9.31,
    school: "North Dakota State",
    img: "https://thedraftnetwork.com/wp-content/uploads/2022/11/Cody_Mauch_2022_NDSU_FB_Headshot_Crop.png",
    archetype: "",
    strengths: ["Agility", "Toughness", "Balance"],
    weaknesses: ["Pass Protection"],
  },
  {
    id: 58,
    rank: 60,
    firstName: "Tuli",
    lastName: "Tuipulotu",
    position: "ED",
    class: "Jr.",
    height: 76,
    weight: 290,
    ras: null,
    school: "USC",
    img: "https://media.pff.com/player-photos/nfl/131840.webp",
    archetype: "Versatile",
    strengths: ["Versatility", "Pass Rush Plan"],
    weaknesses: ["Finishing"],
  },
  {
    id: 59,
    rank: 44,
    firstName: "Adetomiwa",
    lastName: "Adebawore",
    position: "ED",
    class: "Sr.",
    height: 74,
    weight: 280,
    ras: 9.71,
    school: "Northwestern",
    img: "https://thedraftnetwork.com/wp-content/uploads/2022/11/USATSI_18748829_168386526_lowres.png",
    archetype: "Versatile",
    strengths: ["Ridiculous Speed", "Versatility", "Motor"],
    weaknesses: ["Anchor"],
  },
  {
    id: 60,
    rank: 57,
    firstName: "Zach",
    lastName: "Charbonnet",
    position: "RB",
    class: "Sr.",
    height: 73,
    weight: 220,
    ras: 8.73,
    school: "UCLA",
    img: "https://thedraftnetwork.com/wp-content/uploads/2022/11/USATSI_17171789_168386526_lowres.png",
    archetype: "Power Back",
    strengths: ["Power", "Contact Balance", "Vision"],
    weaknesses: ["Speed", "Route Running"],
  },
  {
    id: 61,
    rank: 41,
    firstName: "John Michael",
    lastName: "Schmitz",
    position: "C",
    class: "RS Sr.",
    height: 75,
    weight: 301,
    ras: 7.84,
    school: "Minnesota",
    img: "https://media.pff.com/player-photos/nfl/55238.webp",
    archetype: "",
    strengths: ["Technique", "Anchor"],
    weaknesses: ["Explosiveness", "Flexibility"],
  },
  {
    id: 62,
    rank: 37,
    firstName: "Hendon",
    lastName: "Hooker",
    position: "QB",
    class: "RS Sr.",
    height: 76,
    weight: 218,
    ras: null,
    school: "Tennessee",
    img: "https://media.pff.com/player-photos/nfl/60593.webp",
    archetype: "Developmental",
    strengths: ["Upside", "Accuracy"],
    weaknesses: ["Recent Injury", "Adjustment to NFL"],
  },
  {
    id: 63,
    rank: 53,
    firstName: "Steve",
    lastName: "Avila",
    position: "G",
    class: "Sr.",
    height: 75,
    weight: 332,
    ras: 8.5,
    school: "TCU",
    img: "https://thedraftnetwork.com/wp-content/uploads/2022/06/USATSI_18696924_168386526_lowres.png",
    archetype: "",
    strengths: ["Anchor", "Strength"],
    weaknesses: ["Agility", "Run Blocking"],
  },
  {
    id: 64,
    rank: 56,
    firstName: "Joe",
    lastName: "Tippmann",
    position: "C",
    class: "Jr.",
    height: 78,
    weight: 313,
    ras: null,
    school: "Wisconsin",
    img: "https://media.pff.com/player-photos/nfl/101568.webp",
    archetype: "",
    strengths: ["Athleticism"],
    weaknesses: ["Strength"],
  },
  {
    id: 65,
    rank: 62,
    firstName: "Sam",
    lastName: "LaPorta",
    position: "TE",
    class: "Sr.",
    height: 75,
    weight: 245,
    ras: 9.02,
    school: "Iowa",
    img: "https://media.pff.com/player-photos/nfl/101690.webp",
    archetype: "Vertical Threat",
    strengths: ["YAC", "Route Running", "Hands"],
    weaknesses: ["Catch Point"],
  },
  {
    id: 66,
    rank: 51,
    firstName: "D.J.",
    lastName: "Turner",
    position: "CB",
    class: "Sr.",
    height: 71,
    weight: 178,
    ras: 9.59,
    school: "Michigan",
    img: "https://thedraftnetwork.com/wp-content/uploads/2022/06/USATSI_19687956_168386526_lowres.png",
    archetype: "Versatile",
    strengths: ["Speed", "Technique"],
    weaknesses: ["Ball Production", "Strength"],
  },
  {
    id: 67,
    rank: 52,
    firstName: "Julius",
    lastName: "Brents",
    position: "CB",
    class: "Sr.",
    height: 75,
    weight: 198,
    ras: 9.99,
    school: "Kansas State",
    img: "https://thedraftnetwork.com/wp-content/uploads/2022/12/USATSI_13700725_168386526_lowres.png",
    archetype: "Zone",
    strengths: ["Size", "Physicality"],
    weaknesses: ["Speed"],
  },
  {
    id: 68,
    rank: 59,
    firstName: "Keeanu",
    lastName: "Benton",
    position: "DI",
    class: "Sr.",
    height: 76,
    weight: 309,
    ras: 8.9,
    school: "Wisconsin",
    img: "https://thedraftnetwork.com/wp-content/uploads/2022/11/USATSI_18753522_168386526_lowres.png",
    archetype: "All-Around",
    strengths: ["Power", "Hands"],
    weaknesses: ["Pass Rush"],
  },
  {
    id: 69,
    rank: 64,
    firstName: "Matthew",
    lastName: "Bergeron",
    position: "T",
    class: "Jr.",
    height: 77,
    weight: 318,
    ras: 8.73,
    school: "Syracuse",
    img: "https://thedraftnetwork.com/wp-content/uploads/2022/11/USATSI_18722941_168386526_lowres.png",
    archetype: "",
    strengths: ["Balance", "Movement Skills"],
    weaknesses: ["Mentality"],
  },
  {
    id: 70,
    rank: 66,
    firstName: "Devon",
    lastName: "Achane",
    position: "RB",
    class: "Jr.",
    height: 68,
    weight: 188,
    ras: 5.73,
    school: "Texas A&M",
    img: "https://media.pff.com/player-photos/nfl/124305.webp",
    archetype: "Scat Back",
    strengths: ["Big Play Ability"],
    weaknesses: ["Size", "Pass-blocking"],
  },
  {
    id: 71,
    rank: 65,
    firstName: "Cedric",
    lastName: "Tillman",
    position: "WR",
    class: "RS Sr.",
    height: 75,
    weight: 213,
    ras: 8.66,
    school: "Tennessee",
    img: "https://media.pff.com/player-photos/nfl/84434.webp",
    archetype: "X",
    strengths: ["Catch Radius", "Size"],
    weaknesses: ["Route Running"],
  },
  {
    id: 72,
    rank: 67,
    firstName: "Tucker",
    lastName: "Kraft",
    position: "TE",
    class: "Jr.",
    height: 77,
    weight: 254,
    ras: 9.68,
    school: "South Dakota State",
    img: "https://thedraftnetwork.com/wp-content/uploads/2022/06/USATSI_18873345_168386526_lowres.png",
    archetype: "Vertical Threat",
    strengths: ["Athleticism", "Versatility"],
    weaknesses: ["Hands", "Raw"],
  },
  {
    id: 73,
    rank: 70,
    firstName: "Gervon",
    lastName: "Dexter",
    position: "DI",
    class: "So.",
    height: 78,
    weight: 310,
    ras: 9.52,
    school: "Florida",
    img: "https://media.pff.com/player-photos/nfl/124374.webp",
    archetype: "",
    strengths: ["Size"],
    weaknesses: ["Technique", "Motor"],
  },
  {
    id: 74,
    rank: 72,
    firstName: "Jordan",
    lastName: "Battle",
    position: "S",
    class: "Sr.",
    height: 73,
    weight: 209,
    ras: 5.9,
    school: "Alabama",
    img: "https://media.pff.com/player-photos/nfl/98857.webp",
    archetype: "Box",
    strengths: ["Football IQ", "Physicality"],
    weaknesses: ["Man Coverage"],
  },
  {
    id: 75,
    rank: 78,
    firstName: "Rashee",
    lastName: "Rice",
    position: "WR",
    class: "Sr.",
    height: 73,
    weight: 204,
    ras: 9.53,
    school: "SMU",
    img: "https://media.pff.com/player-photos/nfl/97605.webp",
    archetype: "Possession",
    strengths: ["Ball Skills"],
    weaknesses: ["Route Running"],
  },
  {
    id: 76,
    rank: 73,
    firstName: "Marvin",
    lastName: "Mims",
    position: "WR",
    class: "Jr.",
    height: 71,
    weight: 183,
    ras: 9.4,
    school: "Oklahoma",
    img: "https://media.pff.com/player-photos/nfl/122937.webp",
    archetype: "Deep Threat",
    strengths: ["YAC", "Catch Point"],
    weaknesses: ["Route Running"],
  },
  {
    id: 77,
    rank: 75,
    firstName: "Sydney",
    lastName: "Brown",
    position: "S",
    class: "Sr.",
    height: 70,
    weight: 211,
    ras: 9.68,
    school: "Illinois",
    img: "https://thedraftnetwork.com/wp-content/uploads/2022/11/USATSI_18753926_168386526_lowres.png",
    archetype: "Versatile",
    strengths: ["Instincts"],
    weaknesses: ["Tackling"],
  },
  {
    id: 78,
    rank: 76,
    firstName: "Tyler",
    lastName: "Scott",
    position: "WR",
    class: "Jr.",
    height: 70,
    weight: 177,
    ras: 8.6,
    school: "Cincinnati",
    img: "https://thedraftnetwork.com/wp-content/uploads/2022/06/Scott_Tyler_1_.png",
    archetype: "Deep Threat",
    strengths: ["Explosiveness", "Separation"],
    weaknesses: ["Drops", "Strength"],
  },
  {
    id: 79,
    rank: 80,
    firstName: "Luke",
    lastName: "Wypler",
    position: "C",
    class: "Jr.",
    height: 75,
    weight: 303,
    ras: 9.31,
    school: "Ohio State",
    img: "https://thedraftnetwork.com/wp-content/uploads/2022/06/Wypler_Luke-J090-scaled-e1627399829149-1024x826-1.png",
    archetype: "",
    strengths: ["Leverage"],
    weaknesses: ["Anchor"],
  },
  {
    id: 80,
    rank: 81,
    firstName: "Garrett",
    lastName: "Williams",
    position: "CB",
    class: "RS So.",
    height: 70,
    weight: 192,
    ras: null,
    school: "Syracuse",
    img: "https://thedraftnetwork.com/wp-content/uploads/2022/06/Williams_Garrett_2021.png",
    archetype: "Versatile",
    strengths: ["Instincts", "Feet"],
    weaknesses: ["Mentality"],
  },
  {
    id: 81,
    rank: 79,
    firstName: "Johnathan",
    lastName: "Mingo",
    position: "WR",
    class: "Sr.",
    height: 74,
    weight: 220,
    ras: 9.86,
    school: "Ole Miss",
    img: "https://thedraftnetwork.com/wp-content/uploads/2022/11/Mingo_Jonathan_2022.png",
    archetype: "Slot",
    strengths: ["YAC", "Strength"],
    weaknesses: ["Route Running"],
  },
  {
    id: 82,
    rank: 82,
    firstName: "Jaelyn",
    lastName: "Duncan",
    position: "T",
    class: "RS Sr.",
    height: 78,
    weight: 306,
    ras: 9.02,
    school: "Maryland",
    img: "https://thedraftnetwork.com/wp-content/uploads/2022/06/Jalen_Duncan_Offensive_Line.png",
    archetype: "",
    strengths: ["Length", "Lateral Agility"],
    weaknesses: ["Technique", "Strength"],
  },
  {
    id: 83,
    rank: 74,
    firstName: "Tyjae",
    lastName: "Spears",
    position: "RB",
    class: "Jr.",
    height: 70,
    weight: 201,
    ras: 7.5,
    img: "https://thedraftnetwork.com/wp-content/uploads/2022/11/22_Tyjae_Spears.png",
    archetype: "Elusive",
    strengths: ["Vision", "Agility"],
    weaknesses: ["Lean"],
  },
];
