export const NFL_2024_Prospects = [
  {
    id: 1,
    rank: 1,
    firstName: "Caleb",
    lastName: "Williams",
    position: "QB",
    class: "Jr.",
    height: 73,
    weight: 215,
    ras: null,
    school: "USC",
    img: "https://a.espncdn.com/combiner/i?img=/i/headshots/college-football/players/full/4431611.png",
    desc: [],
    archetype: "",
    strengths: [],
    weaknesses: [],
  },
  {
    id: 2,
    rank: 2,
    firstName: "Drake",
    lastName: "Maye",
    position: "QB",
    class: "So.",
    height: 76,
    weight: 230,
    ras: null,
    school: "North Carolina",
    img: "https://a.espncdn.com/combiner/i?img=/i/headshots/college-football/players/full/4431452.png&w=350&h=254",
    archetype: "",
  },
  {
    id: 3,
    rank: 3,
    firstName: "Marvin",
    lastName: "Harrison Jr.",
    position: "WR",
    class: "Jr.",
    height: 76,
    weight: 205,
    ras: null,
    school: "Ohio State",
    img: "https://a.espncdn.com/combiner/i?img=/i/headshots/college-football/players/full/4432708.png&w=350&h=254",
    archetype: "",
  },
  {
    id: 4,
    rank: 4,
    firstName: "Jayden",
    lastName: "Daniels",
    position: "QB",
    class: "Sr.",
    height: 76,
    weight: 210,
    ras: null,
    school: "LSU",
    img: "https://a.espncdn.com/combiner/i?img=/i/headshots/college-football/players/full/4426348.png&w=350&h=254",
    archetype: "",
  },
  {
    id: 5,
    rank: 5,
    firstName: "Malik",
    lastName: "Nabers",
    position: "WR",
    class: "Jr.",
    height: 72,
    weight: 200,
    ras: null,
    school: "LSU",
    img: "https://a.espncdn.com/combiner/i?img=/i/headshots/college-football/players/full/4595348.png&w=350&h=254",
    archetype: "",
  },
  {
    id: 6,
    rank: 6,
    firstName: "Brock",
    lastName: "Bowers",
    position: "TE",
    class: "Jr.",
    height: 76,
    weight: 240,
    ras: null,
    school: "Georgia",
    img: "https://a.espncdn.com/combiner/i?img=/i/headshots/college-football/players/full/4432665.png&w=350&h=254",
    archetype: "",
  },
  {
    id: 7,
    rank: 7,
    firstName: "Rome",
    lastName: "Odunze",
    position: "WR",
    class: "Jr.",
    height: 75,
    weight: 215,
    ras: null,
    school: "Washington",
    img: "https://a.espncdn.com/combiner/i?img=/i/headshots/college-football/players/full/4431299.png&w=350&h=254",
    archetype: "",
  },
  {
    id: 8,
    rank: 8,
    firstName: "Joe",
    lastName: "Alt",
    position: "T",
    class: "Jr.",
    height: 80,
    weight: 322,
    ras: null,
    school: "Notre Dame",
    img: "https://a.espncdn.com/combiner/i?img=/i/headshots/college-football/players/full/4683487.png&w=350&h=254",
    archetype: "",
  },
  {
    id: 9,
    rank: 9,
    firstName: "Dallas",
    lastName: "Turner",
    position: "ED",
    class: "Jr.",
    height: 76,
    weight: 242,
    ras: null,
    school: "Alabama",
    img: "https://a.espncdn.com/combiner/i?img=/i/headshots/college-football/players/full/4565190.png&w=350&h=254",
    archetype: "",
  },
  {
    id: 10,
    rank: 10,
    firstName: "Olumuyiwa",
    lastName: "Fashanu",
    position: "T",
    class: "Jr.",
    height: 78,
    weight: 319,
    ras: null,
    school: "Penn State",
    img: "https://a.espncdn.com/combiner/i?img=/i/headshots/college-football/players/full/4431809.png&w=350&h=254",
    archetype: "",
  },
  {
    id: 11,
    rank: 11,
    firstName: "Terrion",
    lastName: "Arnold",
    position: "CB",
    class: "RS So.",
    height: 72,
    weight: 196,
    ras: null,
    school: "Alabama",
    img: "https://a.espncdn.com/combiner/i?img=/i/headshots/college-football/players/full/4592837.png&w=350&h=254",
    archetype: "",
  },
  {
    id: 12,
    rank: 12,
    firstName: "Jared",
    lastName: "Verse",
    position: "ED",
    class: "RS Jr.",
    height: 76,
    weight: 260,
    ras: null,
    school: "Florida State",
    img: "https://a.espncdn.com/combiner/i?img=/i/headshots/college-football/players/full/4578085.png&w=350&h=254",
    archetype: "",
  },
  {
    id: 13,
    rank: 13,
    firstName: "Taliese",
    lastName: "Fuaga",
    position: "T",
    class: "Jr.",
    height: 78,
    weight: 334,
    ras: null,
    school: "Oklahoma State",
    img: "https://a.espncdn.com/combiner/i?img=/i/headshots/college-football/players/full/4606711.png&w=350&h=254",
    archetype: "",
  },
  {
    id: 14,
    rank: 14,
    firstName: "Laiatu",
    lastName: "Latu",
    position: "ED",
    class: "Sr.",
    height: 77,
    weight: 265,
    ras: null,
    school: "UCLA",
    img: "https://a.espncdn.com/combiner/i?img=/i/headshots/college-football/players/full/4426473.png&w=350&h=254",
    archetype: "",
  },
  {
    id: 15,
    rank: 15,
    firstName: "Quinyon",
    lastName: "Mitchell",
    position: "CB",
    class: "Jr.",
    height: 72,
    weight: 196,
    ras: null,
    school: "Toldeo",
    img: "https://a.espncdn.com/combiner/i?img=/i/headshots/college-football/players/full/4686273.png&w=350&h=254",
    archetype: "",
  },
  {
    id: 16,
    rank: 16,
    firstName: "Nate",
    lastName: "Wiggins",
    position: "CB",
    class: "Jr.",
    height: 74,
    weight: 185,
    ras: null,
    school: "Clemson",
    img: "https://a.espncdn.com/combiner/i?img=/i/headshots/college-football/players/full/4601278.png&w=350&h=254",
    archetype: "",
  },
  {
    id: 17,
    rank: 17,
    firstName: "JC",
    lastName: "Latham",
    position: "T",
    class: "Jr.",
    height: 78,
    weight: 335,
    ras: null,
    school: "Alabama",
    img: "https://a.espncdn.com/combiner/i?img=/i/headshots/college-football/players/full/4431437.png&w=350&h=254",
    archetype: "",
  },
  {
    id: 18,
    rank: 18,
    firstName: "Cooper",
    lastName: "DeJean",
    position: "CB",
    class: "Jr.",
    height: 73,
    weight: 207,
    ras: null,
    school: "Iowa",
    img: "https://a.espncdn.com/combiner/i?img=/i/headshots/college-football/players/full/4682618.png&w=350&h=254",
    archetype: "",
  },
  {
    id: 19,
    rank: 19,
    firstName: "Kool-Aid",
    lastName: "McKinstry",
    position: "CB",
    class: "Jr.",
    height: 73,
    weight: 195,
    ras: null,
    school: "Alabama",
    img: "https://a.espncdn.com/combiner/i?img=/i/headshots/college-football/players/full/4433975.png&w=350&h=254",
    archetype: "",
  },
  {
    id: 20,
    rank: 20,
    firstName: "Jer'Zhan",
    lastName: "Newton",
    position: "DI",
    class: "Jr.",
    height: 74,
    weight: 295,
    ras: null,
    school: "Illinois",
    img: "https://a.espncdn.com/combiner/i?img=/i/headshots/college-football/players/full/4430560.png&w=350&h=254",
    archetype: "",
  },
  {
    id: 21,
    rank: 21,
    firstName: "Byron",
    lastName: "Murphy II",
    position: "DI",
    class: "Jr.",
    height: 73,
    weight: 308,
    ras: null,
    school: "Texas",
    img: "https://a.espncdn.com/combiner/i?img=/i/headshots/college-football/players/full/4570040.png&w=350&h=254",
    archetype: "",
  },
  {
    id: 22,
    rank: 22,
    firstName: "Brian",
    lastName: "Thomas Jr.",
    position: "WR",
    class: "Jr.",
    height: 76,
    weight: 205,
    ras: null,
    school: "LSU",
    img: "https://a.espncdn.com/combiner/i?img=/i/headshots/college-football/players/full/4432773.png&w=350&h=254",
    archetype: "",
  },
  {
    id: 23,
    rank: 23,
    firstName: "Amarius",
    lastName: "Mims",
    position: "T",
    class: "Jr.",
    height: 79,
    weight: 340,
    ras: null,
    school: "Georgia",
    img: "https://a.espncdn.com/combiner/i?img=/i/headshots/college-football/players/full/4431571.png&w=350&h=254",
    archetype: "",
  },
  {
    id: 24,
    rank: 24,
    firstName: "J.J.",
    lastName: "McCarthy",
    position: "QB",
    class: "Jr.",
    height: 75,
    weight: 202,
    ras: null,
    school: "Michigan",
    img: "https://a.espncdn.com/combiner/i?img=/i/headshots/college-football/players/full/4433970.png&w=350&h=254",
    archetype: "",
  },
  {
    id: 25,
    rank: 25,
    firstName: "Jackson",
    lastName: "Powers-Johnson",
    position: "C",
    class: "Jr.",
    height: 75,
    weight: 320,
    ras: null,
    school: "Oregon",
    img: "https://a.espncdn.com/combiner/i?img=/i/headshots/college-football/players/full/4875295.png&w=350&h=254",
    archetype: "",
  },
  {
    id: 26,
    rank: 26,
    firstName: "Troy",
    lastName: "Fautanu",
    position: "T",
    class: "Jr.",
    height: 76,
    weight: 317,
    ras: null,
    school: "Washington",
    img: "https://a.espncdn.com/combiner/i?img=/i/headshots/college-football/players/full/4427170.png&w=350&h=254",
    archetype: "",
  },
  {
    id: 27,
    rank: 27,
    firstName: "Tyler",
    lastName: "Guyton",
    position: "T",
    class: "RS Jr.",
    height: 79,
    weight: 327,
    ras: null,
    school: "Oklahoma",
    img: "https://a.espncdn.com/combiner/i?img=/i/headshots/college-football/players/full/4609048.png&w=350&h=254",
    archetype: "",
  },
  {
    id: 28,
    rank: 28,
    firstName: "Chop",
    lastName: "Robinson",
    position: "ED",
    class: "Jr.",
    height: 75,
    weight: 250,
    ras: null,
    school: "Penn State",
    img: "https://a.espncdn.com/combiner/i?img=/i/headshots/college-football/players/full/4431586.png&w=350&h=254",
    archetype: "",
  },
  {
    id: 29,
    rank: 29,
    firstName: "Keon",
    lastName: "Coleman",
    position: "WR",
    class: "Jr.",
    height: 76,
    weight: 215,
    ras: null,
    school: "Florida State",
    img: "https://a.espncdn.com/combiner/i?img=/i/headshots/college-football/players/full/4635008.png&w=350&h=254",
    archetype: "",
  },
  {
    id: 30,
    rank: 30,
    firstName: "Ennis",
    lastName: "Rakestraw Jr.",
    position: "CB",
    class: "Jr.",
    height: 72,
    weight: 188,
    ras: null,
    school: "Missouri",
    img: "https://a.espncdn.com/combiner/i?img=/i/headshots/college-football/players/full/4566092.png&w=350&h=254",
    archetype: "",
  },
  {
    id: 31,
    rank: 31,
    firstName: "Graham",
    lastName: "Barton",
    position: "T",
    class: "Sr.",
    height: 77,
    weight: 314,
    ras: null,
    school: "Duke",
    img: "https://a.espncdn.com/combiner/i?img=/i/headshots/college-football/players/full/4429251.png&w=350&h=254",
    archetype: "",
  },
  {
    id: 32,
    rank: 32,
    firstName: "Troy",
    lastName: "Franklin",
    position: "WR",
    class: "Jr.",
    height: 75,
    weight: 187,
    ras: null,
    school: "Oregon",
    img: "https://a.espncdn.com/combiner/i?img=/i/headshots/college-football/players/full/4431280.png&w=350&h=254",
    archetype: "",
  },
  {
    id: 33,
    rank: 33,
    firstName: "Bo",
    lastName: "Nix",
    position: "QB",
    class: "Sr.",
    height: 74,
    weight: 217,
    ras: null,
    school: "Oregon",
    img: "https://a.espncdn.com/combiner/i?img=/i/headshots/college-football/players/full/4426338.png&w=350&h=254",
    archetype: "",
  },
  {
    id: 34,
    rank: 34,
    firstName: "Bralen",
    lastName: "Trice",
    position: "ED",
    class: "Jr.",
    height: 76,
    weight: 274,
    ras: null,
    school: "Washington",
    img: "https://a.espncdn.com/combiner/i?img=/i/headshots/college-football/players/full/4428713.png&w=350&h=254",
    archetype: "",
  },
  {
    id: 35,
    rank: 35,
    firstName: "Jordan",
    lastName: "Morgan",
    position: "T",
    class: "Sr.",
    height: 78,
    weight: 320,
    ras: null,
    school: "Arizona",
    img: "https://a.espncdn.com/combiner/i?img=/i/headshots/college-football/players/full/3821571.png&w=350&h=254",
    archetype: "",
  },
  {
    id: 36,
    rank: 36,
    firstName: "Kamari",
    lastName: "Lassiter",
    position: "CB",
    class: "Jr.",
    height: 72,
    weight: 180,
    ras: null,
    school: "Georgia",
    img: "https://a.espncdn.com/combiner/i?img=/i/headshots/college-football/players/full/4602699.png&w=350&h=254",
    archetype: "",
  },
  {
    id: 37,
    rank: 37,
    firstName: "Adonai",
    lastName: "Mitchell",
    position: "WR",
    class: "Jr.",
    height: 76,
    weight: 196,
    ras: null,
    school: "Texas",
    img: "https://a.espncdn.com/combiner/i?img=/i/headshots/college-football/players/full/4597500.png&w=350&h=254",
    archetype: "",
  },
  {
    id: 38,
    rank: 38,
    firstName: "Michael",
    lastName: "Pennix Jr.",
    position: "QB",
    class: "Sr.",
    height: 75,
    weight: 213,
    ras: null,
    school: "Washington",
    img: "https://a.espncdn.com/combiner/i?img=/i/headshots/college-football/players/full/4360423.png&w=350&h=254",
    archetype: "",
  },
  {
    id: 39,
    rank: 39,
    firstName: "Darius",
    lastName: "Robinson",
    position: "ED",
    class: "Sr.",
    height: 77,
    weight: 296,
    ras: null,
    school: "Missouri",
    img: "https://a.espncdn.com/combiner/i?img=/i/headshots/college-football/players/full/4569480.png&w=350&h=254",
    archetype: "",
  },
  {
    id: 40,
    rank: 40,
    firstName: "Ladd",
    lastName: "McConkey",
    position: "WR",
    class: "Jr.",
    height: 72,
    weight: 185,
    ras: null,
    school: "Georgia",
    img: "https://a.espncdn.com/combiner/i?img=/i/headshots/college-football/players/full/4612826.png&w=350&h=254",
    archetype: "",
  },
];
