export const teams = [
  {    
    city: "Atlanta",
    teamName: "Hawks",
    abr: "ATL",
    logo: "https://content.sportslogos.net/logos/6/220/full/8452_atlanta_hawks-alternate-2016.png",
    picks: [15],
    needs: ["TBD"],
    mainColor: "#C8102E",
    secondaryColor: "#FDB927",
  },
  {
    city: "Boston",
    teamName: "Celtics",
    abr: "BOS",
    logo: "https://content.sportslogos.net/logos/6/213/thumbs/slhg02hbef3j1ov4lsnwyol5o.gif",
    picks: [],
    needs: ["TBD"],
    mainColor: "#007A33",
    secondaryColor: "#BA9653",
  },
  {
    city: "Brooklyn",
    teamName: "Nets",
    abr: "BKN",
    logo: "https://content.sportslogos.net/logos/6/3786/full/brooklyn_nets_logo_alternate_20138452.png",
    picks: [21, 22],
    needs: ["TBD"],
    mainColor: "#000000",
    secondaryColor: "#FFFFFF",
  },
  {
    city: "Charlotte",
    teamName: "Hornets",
    abr: "CHA",
    logo: "https://content.sportslogos.net/logos/6/5120/thumbs/512019262015.gif",
    picks: [2, 27],
    needs: ["TBD"],
    mainColor: "#1D1160",
    secondaryColor: "#00788C",
  },
  {
    city: "Chicago",
    teamName: "Bulls",
    abr: "CHI",
    logo: "https://content.sportslogos.net/logos/6/221/full/zdrycpc7mh5teihl10gko8sgf.png",
    picks: [],
    needs: ["TBD"],
    mainColor: "#CE1141",
    secondaryColor: "#000000",
  },
  {
    city: "Cleveland",
    teamName: "Cavaliers",
    abr: "CLE",
    logo: "https://content.sportslogos.net/logos/6/222/full/cleveland_cavaliers_logo_alternate_2023_sportslogosnet-5447.png",
    picks: [1],
    needs: ["TBD"],
    mainColor: "#860038",
    secondaryColor: "#0076A3",
  },
  {
    city: "Dallas",
    teamName: "Mavericks",
    abr: "DAL",
    logo: "https://content.sportslogos.net/logos/6/228/thumbs/22851182018.gif",
    picks: [10],
    needs: ["TBD"],
    mainColor: "#0053BC",
    secondaryColor: "#B8C4CA",
  },
  {
    city: "Denver",
    teamName: "Nuggets",
    abr: "DEN",
    logo: "https://content.sportslogos.net/logos/6/229/full/8954_denver_nuggets-alternate-2019.png",
    picks: [1],
    needs: ["TBD"],
    mainColor: "#0E2240",
    secondaryColor: "#FEC524",
  },
  {
    city: "Detroit",
    teamName: "Pistons",
    abr: "DET",
    logo: "https://content.sportslogos.net/logos/6/223/full/detroit_pistons_logo_primary_20185710.png",
    picks: [5],
    needs: ["TBD"],
    mainColor: "#C8102E",
    secondaryColor: "#006BB6",
  },
  {
    city: "Golden State",
    teamName: "Warriors",
    abr: "GSW",
    logo: "https://content.sportslogos.net/logos/6/235/full/4782_golden_state_warriors-alternate-2020.png",
    picks: [19],
    needs: ["TBD"],
    mainColor: "#1D428A",
    secondaryColor: "#FFC72C",
  },
  {
    city: "Houston",
    teamName: "Rockets",
    abr: "HOU",
    logo: "https://content.sportslogos.net/logos/6/230/full/9260_houston_rockets-alternate-2020.png",
    picks: [4, 20],
    needs: ["TBD"],
    mainColor: "#CE1141",
    secondaryColor: "#C4CED4",
  },
  {
    city: "Indiana",
    teamName: "Pacers",
    abr: "IND",
    logo: "https://content.sportslogos.net/logos/6/224/full/gdm7egmgv3tsspc6f1gym7cwz.gif",
    picks: [7, 26, 29],
    needs: ["TBD"],
    mainColor: "#002D62",
    secondaryColor: "#FDBB30",
  },
  {
    city: "Los Angeles",
    teamName: "Clippers",
    abr: "LAC",
    logo: "https://content.sportslogos.net/logos/6/236/full/1038_los_angeles_clippers-secondary-2016.png",
    picks: [30],
    needs: ["TBD"],
    mainColor: "#C8102E",
    secondaryColor: "#1D428A",
  },
  {
    city: "Los Angeles",
    teamName: "Lakers",
    abr: "LAL",
    logo: "https://content.sportslogos.net/logos/6/237/full/uig7aiht8jnpl1szbi57zzlsh.png",
    picks: [17],
    needs: ["TBD"],
    mainColor: "#552583",
    secondaryColor: "#FDB927",
  },
  {
    city: "Memphis",
    teamName: "Grizzlies",
    abr: "MEM",
    logo: "https://content.sportslogos.net/logos/6/231/full/7277_memphis_grizzlies-alternate-2019.png",
    picks: [25],
    needs: ["TBD"],
    mainColor: "#5D76A9",
    secondaryColor: "#12173F",
  },
  {
    city: "Miami",
    teamName: "Heat",
    abr: "MIA",
    logo: "https://content.sportslogos.net/logos/6/214/full/93lzfcfcnq125eh7etyxpuhfp.gif",
    picks: [18],
    needs: ["TBD"],
    mainColor: "#98002E",
    secondaryColor: "#F9A01B",
  },
  {
    city: "Milwaukee",
    teamName: "Bucks",
    abr: "MIL",
    logo: "https://content.sportslogos.net/logos/6/225/full/milwaukee_bucks_logo_alternate_20169034.png",
    picks: [],
    needs: ["TBD"],
    mainColor: "#00471B",
    secondaryColor: "#EEE1C6",
  },
  {
    city: "Minnesota",
    teamName: "Timberwolves",
    abr: "MIN",
    logo: "https://content.sportslogos.net/logos/6/232/full/6093_minnesota_timberwolves-alternate-2018.png",
    picks: [],
    needs: ["TBD"],
    mainColor: "#0C2340",
    secondaryColor: "#236192",
  },
  {
    city: "New Orleans",
    teamName: "Pelicans",
    abr: "NOP",
    logo: "https://content.sportslogos.net/logos/6/4962/full/6144_new_orleans_pelicans-secondary-2014.png",
    picks: [14],
    needs: ["TBD"],
    mainColor: "#0C2340",
    secondaryColor: "#C8102E",
  },
  {
    city: "New York",
    teamName: "Knicks",
    abr: "NYK",
    logo: "https://content.sportslogos.net/logos/6/216/full/2nn48xofg0hms8k326cqdmuis.gif",
    picks: [],
    needs: ["TBD"],
    mainColor: "#006BB6",
    secondaryColor: "#F58426",
  },
  {
    city: "Oklahoma City",
    teamName: "Thunder",
    abr: "OKC",
    logo: "https://content.sportslogos.net/logos/6/2687/full/qdx55wdx4akljqkvzi1s3e6t3.gif",
    picks: [12],
    needs: ["TBD"],
    mainColor: "#007AC1",
    secondaryColor: "#EF3B24",
  },
  {
    city: "Orlando",
    teamName: "Magic",
    abr: "ORL",
    logo: "https://content.sportslogos.net/logos/6/217/full/h2k5cbia6m8e1dbdcfxfgre84.gif",
    picks: [6, 11],
    needs: ["TBD"],
    mainColor: "#0077C0",
    secondaryColor: "#C4CED4",
  },
  {
    city: "Philadelphia",
    teamName: "76ers",
    abr: "PHI",
    logo: "https://content.sportslogos.net/logos/6/218/full/5312_philadelphia_76ers-secondary-2016.png",
    picks: [],
    needs: ["TBD"],
    mainColor: "#006BB6",
    secondaryColor: "#ED174C",
  },
  {
    city: "Phoenix",
    teamName: "Suns",
    abr: "PHX",
    logo: "https://content.sportslogos.net/logos/6/238/full/phoenix_suns_logo_alternate_20141645.png",
    picks: [],
    needs: ["TBD"],
    mainColor: "#1D1160",
    secondaryColor: "#E56020",
  },
  {
    city: "Portland",
    teamName: "Trail Blazers",
    abr: "POR",
    logo: "https://content.sportslogos.net/logos/6/239/full/9725_portland_trail_blazers-primary-2018.png",
    picks: [3, 23],
    needs: ["TBD"],
    mainColor: "#E03A3E",
    secondaryColor: "#000000",
  },
  {
    city: "Sacramento",
    teamName: "Kings",
    abr: "SAC",
    logo: "https://content.sportslogos.net/logos/6/240/full/5961_sacramento_kings-alternate-2017.png",
    picks: [24],
    needs: ["TBD"],
    mainColor: "#5A2D81",
    secondaryColor: "#63727A",
  },
  {
    city: "San Antonio",
    teamName: "Spurs",
    abr: "SAS",
    logo: "https://content.sportslogos.net/logos/6/233/full/828.gif",
    picks: [1],
    needs: ["TBD"],
    mainColor: "#C4CED4",
    secondaryColor: "#000000",
  },
  {
    city: "Toronto",
    teamName: "Raptors",
    abr: "TOR",
    logo: "https://content.sportslogos.net/logos/6/227/full/7024_toronto_raptors-primary-2021.png",
    picks: [13],
    needs: ["TBD"],
    mainColor: "#CE1141",
    secondaryColor: "#A1A1A4",
  },
  {
    city: "Utah",
    teamName: "Jazz",
    abr: "UTA",
    logo: "https://content.sportslogos.net/logos/6/234/full/utah_jazz_logo_alternate_2023_sportslogosnet-5515.png",
    picks: [9, 16, 28],
    needs: ["TBD"],
    mainColor: "#002B5C",
    secondaryColor: "#F9A01B",
  },
  {
    city: "Washington",
    teamName: "Wizards",
    abr: "WAS",
    logo: "https://content.sportslogos.net/logos/6/219/full/5671_washington_wizards-primary-2016.png",
    picks: [8],
    needs: ["TBD"],
    mainColor: "#002B5C",
    secondaryColor: "#E31837",
  },
];
