export const NFL_Teams = [
  {
    city: "Arizona",
    teamName: "Cardinals",
    abr: "ARI",
    logo: "https://content.sportslogos.net/logos/7/177/thumbs/kwth8f1cfa2sch5xhjjfaof90.gif",
    picks: [4, 27],
    needs: ["ED", "DI", "CB", "WR", "LB", "G"],
    mainColor: "#97233F",
    secondaryColor: "#FFB612",
  },
  {
    city: "Atlanta",
    teamName: "Falcons",
    abr: "ATL",
    logo: "https://content.sportslogos.net/logos/7/173/thumbs/299.gif",
    picks: [8],
    needs: ["QB", "ED", "CB", "DI", "WR"],
    mainColor: "#A71930",
    secondaryColor: "#000000",
  },
  {
    city: "Baltimore",
    teamName: "Ravens",
    abr: "BAL",
    logo: "https://content.sportslogos.net/logos/7/153/thumbs/318.gif",
    picks: [30],
    needs: ["ED", "G", "LB", "RB", "S", "WR", "CB"],
    mainColor: "#241773",
    secondaryColor: "#9E7C0C",
  },
  {
    city: "Buffalo",
    teamName: "Bills",
    abr: "BUF",
    logo: "https://content.sportslogos.net/logos/7/149/thumbs/n0fd1z6xmhigb0eej3323ebwq.gif",
    picks: [28],
    needs: ["ED", "DI", "WR", "S", "RB"],
    mainColor: "#00338D",
    secondaryColor: "#C60C30",
  },
  {
    city: "Carolina",
    teamName: "Panthers",
    abr: "CAR",
    logo: "https://content.sportslogos.net/logos/7/174/thumbs/f1wggq2k8ql88fe33jzhw641u.gif",
    picks: [],
    needs: ["WR", "G", "ED", "LB", "CB", "DI"],
    mainColor: "#0085CA",
    secondaryColor: "#101820",
  },
  {
    city: "Chicago",
    teamName: "Bears",
    abr: "CHI",
    logo: "https://content.sportslogos.net/logos/7/169/thumbs/364.gif",
    picks: [1, 9],
    needs: ["QB", "WR", "DI", "C", "ED", "TE"],
    mainColor: "#0B162A",
    secondaryColor: "#C83803",
  },
  {
    city: "Cincinnati",
    teamName: "Bengals",
    abr: "CIN",
    logo: "https://content.sportslogos.net/logos/7/154/thumbs/15420492021.gif",
    picks: [18],
    needs: ["T", "DI", "TE", "WR", "CB", "G", "RB"],
    mainColor: "#FB4F14",
    secondaryColor: "#000000",
  },
  {
    city: "Cleveland",
    teamName: "Browns",
    abr: "CLE",
    logo: "https://content.sportslogos.net/logos/7/155/thumbs/15578552015.gif",
    picks: [],
    needs: ["LB", "DI", "WR"],
    mainColor: "#311D00",
    secondaryColor: "#FF3C00",
  },
  {
    city: "Dallas",
    teamName: "Cowboys",
    abr: "DAL",
    logo: "https://content.sportslogos.net/logos/7/165/thumbs/406.gif",
    picks: [24],
    needs: ["CB", "T", "G", "C", "RB", "LB", "DI"],
    mainColor: "#041E42",
    secondaryColor: "#869397",
  },
  {
    city: "Denver",
    teamName: "Broncos",
    abr: "DEN",
    logo: "https://content.sportslogos.net/logos/7/161/thumbs/9ebzja2zfeigaziee8y605aqp.gif",
    picks: [12],
    needs: ["QB", "ED", "C", "DI", "S", "CB"],
    mainColor: "#FB4F14",
    secondaryColor: "#002244",
  },
  {
    city: "Detroit",
    teamName: "Lions",
    abr: "DET",
    logo: "https://content.sportslogos.net/logos/7/170/thumbs/17013982017.gif",
    picks: [29],
    needs: ["CB", "ED", "G", "DI", "WR"],
    mainColor: "#0076B6",
    secondaryColor: "#B0B7BC",
  },
  {
    city: "Green Bay",
    teamName: "Packers",
    abr: "GB",
    logo: "https://content.sportslogos.net/logos/7/171/thumbs/dcy03myfhffbki5d7il3.gif",
    picks: [25],
    needs: ["S", "CB", "G", "DI", "T", "RB"],
    mainColor: "#203731",
    secondaryColor: "#FFB612",
  },
  {
    city: "Houston",
    teamName: "Texans",
    abr: "HOU",
    logo: "https://content.sportslogos.net/logos/7/157/thumbs/570.gif",
    picks: [23],
    needs: ["CB", "TE", "RB", "S", "T", "G", "C", "WR"],
    mainColor: "#03202F",
    secondaryColor: "#A71930",
  },
  {
    city: "Indianapolis",
    teamName: "Colts",
    abr: "IND",
    logo: "https://content.sportslogos.net/logos/7/158/thumbs/593.gif",
    picks: [15],
    needs: ["DI", "CB", "ED", "S", "G", "WR", "TE"],
    mainColor: "#002C5F",
    secondaryColor: "#A2AAAD",
  },
  {
    city: "Jacksonville",
    teamName: "Jaguars",
    abr: "JAX",
    logo: "https://content.sportslogos.net/logos/7/159/thumbs/15988562013.gif",
    picks: [17],
    needs: ["DI", "WR", "CB", "G", "C", "RB"],
    mainColor: "#006778",
    secondaryColor: "#D7A22A",
  },
  {
    city: "Kansas City",
    teamName: "Chiefs",
    abr: "KC",
    logo: "https://content.sportslogos.net/logos/7/162/thumbs/857.gif",
    picks: [32],
    needs: ["T", "DI", "WR", "LB", "RB", "S", "CB"],
    mainColor: "#E31837",
    secondaryColor: "#FFB81C",
  },
  {
    city: "Las Vegas",
    teamName: "Raiders",
    abr: "LV",
    logo: "https://content.sportslogos.net/logos/7/6708/thumbs/670885212020.gif",
    picks: [13],
    needs: ["QB", "DI", "T", "C", "G", "RB"],
    mainColor: "#000000",
    secondaryColor: "#A5ACAF",
  },
  {
    city: "Los Angeles",
    teamName: "Chargers",
    abr: "LAC",
    logo: "https://content.sportslogos.net/logos/7/6446/thumbs/644616602020.gif",
    picks: [5],
    needs: ["DI", "CB", "C", "S", "TE", "T", "LB", "ED", "G", "RB"],
    mainColor: "#0073CF",
    secondaryColor: "#FFC20E",
  },
  {
    city: "Los Angeles",
    teamName: "Rams",
    abr: "LAR",
    logo: "https://content.sportslogos.net/logos/7/5941/thumbs/594183342020.gif",
    picks: [19],
    needs: ["CB", "S", "G", "ED", "LB"],
    mainColor: "#003594",
    secondaryColor: "#FFD100",
  },
  {
    city: "Miami",
    teamName: "Dolphins",
    abr: "MIA",
    logo: "https://content.sportslogos.net/logos/7/150/thumbs/15073062018.gif",
    picks: [21],
    needs: ["C", "G", "DI", "ED", "LB", "S", "CB"],
    mainColor: "#008E97",
    secondaryColor: "#F58220",
  },
  {
    city: "Minnesota",
    teamName: "Vikings",
    abr: "MIN",
    logo: "https://content.sportslogos.net/logos/7/172/thumbs/17227042013.gif",
    picks: [11],
    needs: ["QB", "ED", "CB", "G", "LB", "WR", "RB", "S"],
    mainColor: "#4F2683",
    secondaryColor: "#FFC62F",
  },
  {
    city: "New England",
    teamName: "Patriots",
    abr: "NE",
    logo: "https://content.sportslogos.net/logos/7/151/thumbs/y71myf8mlwlk8lbgagh3fd5e0.gif",
    picks: [3],
    needs: ["QB", "T", "TE", "WR", "S", "ED"],
    mainColor: "#002244",
    secondaryColor: "#C60C30",
  },
  {
    city: "New Orleans",
    teamName: "Saints",
    abr: "NO",
    logo: "https://content.sportslogos.net/logos/7/175/thumbs/907.gif",
    picks: [14],
    needs: ["ED", "DI", "G", "WR", "T", "CB"],
    mainColor: "#D3BC8D",
    secondaryColor: "#101820",
  },
  {
    city: "New York",
    teamName: "Giants",
    abr: "NYG",
    logo: "https://content.sportslogos.net/logos/7/166/thumbs/919.gif",
    picks: [6],
    needs: ["WR", "G", "DI", "CB", "RB", "T", "QB"],
    mainColor: "#0B2265",
    secondaryColor: "#A71930",
  },
  {
    city: "New York",
    teamName: "Jets",
    abr: "NYJ",
    logo: "https://content.sportslogos.net/logos/7/152/thumbs/15291162019.gif",
    picks: [10],
    needs: ["T", "WR", "S", "ED"],
    mainColor: "#125740",
    secondaryColor: "#000000",
  },
  {
    city: "Philadelphia",
    teamName: "Eagles",
    abr: "PHI",
    logo: "https://content.sportslogos.net/logos/7/167/thumbs/960.gif",
    picks: [22],
    needs: ["LB", "C", "G", "WR", "RB", "CB", "S", "ED"],
    mainColor: "#004C54",
    secondaryColor: "#A5ACAF",
  },
  {
    city: "Pittsburgh",
    teamName: "Steelers",
    abr: "PIT",
    logo: "https://content.sportslogos.net/logos/7/156/thumbs/970.gif",
    picks: [20],
    needs: ["CB", "T", "QB", "C", "G", "WR", "S", "LB"],
    mainColor: "#FFB612",
    secondaryColor: "#000000",
  },
  {
    city: "San Francisco",
    teamName: "49ers",
    abr: "SF",
    logo: "https://content.sportslogos.net/logos/7/179/thumbs/17994552009.gif",
    picks: [31],
    needs: ["G", "T", "ED", "CB", "LB"],
    mainColor: "#AA0000",
    secondaryColor: "#B3995D",
  },
  {
    city: "Seattle",
    teamName: "Seahawks",
    abr: "SEA",
    logo: "https://content.sportslogos.net/logos/7/180/thumbs/pfiobtreaq7j0pzvadktsc6jv.gif",
    picks: [16],
    needs: ["DI", "LB", "C", "G", "TE", "ED", "T"],
    mainColor: "#002244",
    secondaryColor: "#69BE28",
  },
  {
    city: "Tampa Bay",
    teamName: "Buccaneers",
    abr: "TB",
    logo: "https://content.sportslogos.net/logos/7/176/thumbs/17683632020.gif",
    picks: [26],
    needs: ["QB", "WR", "LB", "G", "S", "C", "DI", "RB"],
    mainColor: "#D50A0A",
    secondaryColor: "#34302D",
  },
  {
    city: "Tennessee",
    teamName: "Titans",
    abr: "TEN",
    logo: "https://content.sportslogos.net/logos/7/160/thumbs/1053.gif",
    picks: [7],
    needs: ["CB", "C", "DI", "ED", "T", "RB", "WR"],
    mainColor: "#0C2340",
    secondaryColor: "#4B92DB",
  },
  {
    city: "Washington",
    teamName: "Commanders",
    abr: "WAS",
    logo: "https://content.sportslogos.net/logos/7/6832/thumbs/683260482022.gif",
    picks: [2],
    needs: ["QB", "ED", "CB", "WR", "RB", "S", "G"],
    mainColor: "#773141",
    secondaryColor: "#FFB612",
  },
];
