import { nanoid } from "nanoid";

export const prospects = [
  {
    id: nanoid(),
    drafted: false,
    firstName: "Bryce",
    lastName: "Young",
    position: "QB",
    age: 21.5,
    height: 72,
    weight: 194,
    school: "Alabama",
    img: "https://media.pff.com/player-photos/nfl/123943.webp",
  },
  {
    id: nanoid(),
    drafted: false,
    firstName: "Jalen",
    lastName: "Carter",
    position: "DI",
    age: null,
    height: 75,
    weight: 300,
    school: "Georgia",
    img: "https://media.pff.com/player-photos/nfl/124019.webp",
  },
  {
    id: nanoid(),
    drafted: false,
    firstName: "Will",
    lastName: "Levis",
    position: "QB",
    age: 23.6,
    height: 75,
    weight: 232,
    school: "Kentucky",
    img: "https://media.pff.com/player-photos/nfl/83542.webp",
  },
  {
    id: nanoid(),
    drafted: false,
    firstName: "Will",
    lastName: "Anderson Jr.",
    position: "ED",
    age: null,
    height: 76,
    weight: 243,
    school: "Alabama",
    img: "https://media.pff.com/player-photos/nfl/123903.webp",
  },
  {
    id: nanoid(),
    drafted: false,
    firstName: "C.J.",
    lastName: "Stroud",
    position: "QB",
    age: 21.3,
    height: 75,
    weight: 215,
    school: "Ohio State",
    img: "https://media.pff.com/player-photos/nfl/129759.webp",
  },
  {
    id: nanoid(),
    drafted: false,
    firstName: "Myles",
    lastName: "Murphy",
    position: "ED",
    age: null,
    height: 77,
    weight: 275,
    school: "Clemson",
    img: "https://media.pff.com/player-photos/nfl/122154.webp",
  },
  {
    id: nanoid(),
    drafted: false,
    firstName: "Tyree",
    lastName: "Wilson",
    position: "ED",
    age: null,
    height: 78,
    weight: 275,
    school: "Texas Tech",
    img: "https://external-content.duckduckgo.com/iu/?u=http%3A%2F%2Fwww.rocnation.com%2Fwp-content%2Fuploads%2F2022%2F09%2Ftyree.png&f=1&nofb=1&ipt=a93f34d3a928d526df74233966b022d0de1705ec05086df477dcc8572a1b0893&ipo=images",
  },
  {
    id: nanoid(),
    drafted: false,
    firstName: "Bryan",
    lastName: "Bresee",
    position: "DI",
    age: null,
    height: 77,
    weight: 300,
    school: "Clemson",
    img: "https://media.pff.com/player-photos/nfl/122142.webp",
  },
  {
    id: nanoid(),
    drafted: false,
    firstName: "Paris",
    lastName: "Johnson Jr.",
    position: "T",
    age: null,
    height: 78,
    weight: 310,
    school: "Ohio State",
    img: "https://media.pff.com/player-photos/nfl/129749.webp",
  },
  {
    id: nanoid(),
    drafted: false,
    firstName: "Brian",
    lastName: "Branch",
    position: "S",
    age: null,
    height: 72,
    weight: 193,
    school: "Alabama",
    img: "https://media.pff.com/player-photos/nfl/123907.webp",
  },
  {
    id: nanoid(),
    drafted: false,
    firstName: "Anthony",
    lastName: "Richardson",
    position: "QB",
    age: 21.7,
    height: 76,
    weight: 232,
    school: "Florida",
    img: "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse1.mm.bing.net%2Fth%3Fid%3DOIP.gaXz8ax8M21VkHj4e7ON8AHaFY%26pid%3DApi&f=1&ipt=aa157ec26dc61577c49649a36bff8af365c8d0f2b0b23ba22de29390fe68161d&ipo=images",
  },
  {
    id: nanoid(),
    drafted: false,
    firstName: "Devon",
    lastName: "Witherspoon",
    position: "CB",
    age: null,
    height: 72,
    weight: 180,
    school: "Illinois",
    img: "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse3.mm.bing.net%2Fth%3Fid%3DOIP.-rWowyXfflk4C4sKIPQYwQHaFY%26pid%3DApi&f=1&ipt=3922e1393dc98f26d6ccbde527ead2c2e9719703f82b647ddf8ec932acf5c541&ipo=images",
  },
  {
    id: nanoid(),
    drafted: false,
    firstName: "Peter",
    lastName: "Skoronski",
    position: "T",
    age: null,
    height: 76,
    weight: 315,
    school: "Northwestern",
    img: "https://media.pff.com/player-photos/nfl/129737.webp",
  },
  {
    id: nanoid(),
    drafted: false,
    firstName: "Christain",
    lastName: "Gonzalez",
    position: "CB",
    age: null,
    height: 74,
    weight: 201,
    school: "Oregon",
    img: "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse2.mm.bing.net%2Fth%3Fid%3DOIP.k_kFAx_ZLhg5nTRlgeMljAHaFY%26pid%3DApi&f=1&ipt=aa0d31b921b2ece41b5dae2424313c341798329a7c0f74dd59db8ff571aabe75&ipo=images",
  },
  {
    id: nanoid(),
    drafted: false,
    firstName: "Quentin",
    lastName: "Johnston",
    position: "WR",
    age: 21.4,
    height: 76,
    weight: 215,
    school: "TCU",
    img: "https://media.pff.com/player-photos/nfl/123085.webp",
  },
  {
    id: nanoid(),
    drafted: false,
    firstName: "Lukas",
    lastName: "Van Ness",
    position: "ED",
    age: null,
    height: 77,
    weight: 269,
    school: "Iowa",
    img: "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse1.mm.bing.net%2Fth%3Fid%3DOIP.GtpxVP14wxNM849RbKwYcgHaHa%26pid%3DApi&f=1&ipt=685e18c4579d6e88ee3558a783e1cb53923afde106c9405dfd1fc91b19b62ca5&ipo=images",
  },
  {
    id: nanoid(),
    drafted: false,
    firstName: "Michael",
    lastName: "Mayer",
    position: "TE",
    age: 21.5,
    height: 76,
    weight: 265,
    img: "https://media.pff.com/player-photos/nfl/122906.webp",
  },
  {
    id: nanoid(),
    drafted: false,
    firstName: "Bijan",
    lastName: "Robinson",
    position: "RB",
    age: 21.0,
    height: 72,
    weight: 220,
    school: "Texas",
    img: "https://media.pff.com/player-photos/nfl/123126.webp",
  },
  {
    id: nanoid(),
    drafted: false,
    firstName: "Zay",
    lastName: "Flowers",
    position: "WR",
    age: 22.4,
    height: 70,
    weight: 172,
    school: "Boston College",
    img: "https://media.pff.com/player-photos/nfl/97268.webp",
  },
  {
    id: nanoid(),
    drafted: false,
    firstName: "Jaxon",
    lastName: "Smith-Njigba",
    position: "WR",
    age: 20.9,
    height: 72,
    weight: 198,
    school: "Ohio State",
    img: "https://media.pff.com/player-photos/nfl/129758.webp",
  },
  {
    id: nanoid(),
    drafted: false,
    firstName: "Anton",
    lastName: "Harrison",
    position: "T",
    age: null,
    height: 77,
    weight: 315,
    school: "Oklahoma",
    img: "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse1.mm.bing.net%2Fth%3Fid%3DOIP.xCBsrlO4lD8WxZJR066WzgHaFY%26pid%3DApi&f=1&ipt=fdb07cfb03945a009f8434c89e50d898fce2513fb853d7c98dc469ffee5cfca0&ipo=images",
  },
  {
    id: nanoid(),
    drafted: false,
    firstName: "Nolan",
    lastName: "Smith",
    position: "ED",
    age: null,
    height: 75,
    weight: 235,
    school: "Georgia",
    img: "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse1.mm.bing.net%2Fth%3Fid%3DOIP.YcHt4lLNjRhlTtSZnyQzFgHaFY%26pid%3DApi&f=1&ipt=cc3843e7ebc966a1c481e7f4363bc57e8ae335a0ad3707bb1d527d67c0724d04&ipo=images",
  },
  {
    id: nanoid(),
    drafted: false,
    firstName: "Jordan",
    lastName: "Addison",
    position: "WR",
    age: 21.0,
    height: 72,
    weight: 175,
    school: "USC",
    img: "https://media.pff.com/player-photos/nfl/123000.webp",
  },
  {
    id: nanoid(),
    drafted: false,
    firstName: "Broderick",
    lastName: "Jones",
    position: "T",
    age: null,
    height: 76,
    weight: 310,
    school: "Georgia",
    img: "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse3.mm.bing.net%2Fth%3Fid%3DOIP.EcCH5xj7B192vsZxhLvbqAHaFY%26pid%3DApi&f=1&ipt=c671f175caae1cfae4750d6bbc5e41d6e0e591c3ba2673083d20f3e79080222a&ipo=images",
  },
  {
    id: nanoid(),
    drafted: false,
    firstName: "Cam",
    lastName: "Smith",
    position: "CB",
    age: null,
    height: 72,
    weight: 188,
    school: "South Carolina",
    img: "https://media.pff.com/player-photos/nfl/98837.webp",
  },
  {
    id: nanoid(),
    drafted: false,
    firstName: "Joey",
    lastName: "Porter Jr.",
    position: "CB",
    age: null,
    height: 74,
    weight: 198,
    school: "Penn State",
    img: "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse4.mm.bing.net%2Fth%3Fid%3DOIP.6LeeWLro2y1qf7t0VuOMKAHaFY%26pid%3DApi&f=1&ipt=1baaa67efdace80f6b13d8158a0034f686e0983f50321df38a944cad30e4598a&ipo=images",
  },
  {
    id: nanoid(),
    drafted: false,
    firstName: "O'Cyrus",
    lastName: "Torrence",
    position: "G",
    age: null,
    height: 77,
    weight: 347,
    school: "Florida",
    img: "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse4.mm.bing.net%2Fth%3Fid%3DOIP.VQKs5AoSHjbg9oDPg6kVzAAAAA%26pid%3DApi&f=1&ipt=e23daf20a9c1dc783278d3170043986063ca224d9e429fe084dd5c40c20e07ca&ipo=images",
  },
  {
    id: nanoid(),
    drafted: false,
    firstName: "Tanner",
    lastName: "McKee",
    position: "QB",
    age: 22.7,
    height: 78,
    weight: 230,
    school: "Stanford",
    img: "https://media.pff.com/player-photos/nfl/131770.webp",
  },
  {
    id: nanoid(),
    drafted: false,
    firstName: "Trenton",
    lastName: "Simpson",
    position: "LB",
    age: null,
    height: 75,
    weight: 230,
    school: "Clemson",
    img: "https://media.pff.com/player-photos/nfl/122157.webp",
  },
  {
    id: nanoid(),
    drafted: false,
    firstName: "Luke",
    lastName: "Musgrave",
    position: "TE",
    age: 22.4,
    height: 78,
    weight: 250,
    school: "Oregon State",
    img: "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse1.mm.bing.net%2Fth%3Fid%3DOIP.MLTA2khYaL-C8CnbmtDg-AHaHa%26pid%3DApi&f=1&ipt=589fb7702bff6080d69d1a76240e441121fe30227bfb78e7a17539dfe57c6db6&ipo=images",
  },
  {
    id: nanoid(),
    drafted: false,
    firstName: "Siaki",
    lastName: "Ika",
    position: "DI",
    age: null,
    height: 76,
    weight: 358,
    school: "Baylor",
    img: "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse1.mm.bing.net%2Fth%3Fid%3DOIP.Wh4Ov64e5xpgWQO9hKacnwHaFY%26pid%3DApi&f=1&ipt=e561230bf33e11ba647a904fb93cf8e4cb57a2830c0c363c9cd3120693daab20&ipo=images",
  },
  {
    id: nanoid(),
    drafted: false,
    firstName: "BJ",
    lastName: "Ojulari",
    position: "ED",
    age: null,
    height: 75,
    weight: 250,
    school: "LSU",
    img: "https://media.pff.com/player-photos/nfl/124105.webp",
  },
  {
    id: nanoid(),
    drafted: false,
    firstName: "Andre",
    lastName: "Carter II",
    position: "ED",
    age: null,
    height: 79,
    weight: 260,
    school: "Army",
    img: "https://media.pff.com/player-photos/nfl/102780.webp",
  },
  {
    id: nanoid(),
    drafted: false,
    firstName: "Dalton",
    lastName: "Kincaid",
    position: "TE",
    age: 23.3,
    height: 76,
    weight: 240,
    school: "Utah",
    img: "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse2.explicit.bing.net%2Fth%3Fid%3DOIP.paNOE-T8E-cm5X3WQn2akAHaFY%26pid%3DApi&f=1&ipt=b516e2b0231386c6c34a761cdd4d0c8d2973a404bcae8c4a5de8b280e15ac08a&ipo=images",
  },
  {
    id: nanoid(),
    drafted: false,
    firstName: "Calijah",
    lastName: "Kancey",
    position: "DI",
    age: 21.9,
    height: 72,
    weight: 280,
    school: "Pittsburgh",
    img: "https://media.pff.com/player-photos/nfl/99822.webp",
  },
  {
    id: nanoid(),
    drafted: false,
    firstName: "Deonte",
    lastName: "Banks",
    position: "CB",
    age: null,
    height: 74,
    weight: 205,
    school: "Maryland",
    img: "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse1.mm.bing.net%2Fth%3Fid%3DOIP.OPpaC_z4XihbqiV_k4ExYgAAAA%26pid%3DApi&f=1&ipt=d4fbf4ff4826671680fb7761b3efe906be9cf5ed75e297d9eb20d917cb7f41e7&ipo=images",
  },
  {
    id: nanoid(),
    drafted: false,
    firstName: "Will",
    lastName: "McDonald IV",
    position: "ED",
    age: 23.7,
    height: 75,
    weight: 236,
    school: "Iowa State",
    img: "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fwww.ourlads.com%2Fimages%2Fplayers%2Fncaa%2FMCD222153.png&f=1&nofb=1&ipt=14e6db2f907974f8160087e19a0f86277413dd750e9bfc63264f19b774363d5d&ipo=images",
  },
  {
    id: nanoid(),
    drafted: false,
    firstName: "Antonio",
    lastName: "Johnson",
    position: "S",
    age: 21.3,
    height: 75,
    weight: 195,
    school: "Texas A&M",
    img: "https://media.pff.com/player-photos/nfl/124326.webp",
  },
  {
    id: nanoid(),
    drafted: false,
    firstName: "Mazi",
    lastName: "Smith",
    position: "DI",
    age: 21.6,
    height: 75,
    weight: 337,
    school: "Michigan",
    img: "https://media.pff.com/player-photos/nfl/101419.webp",
  },
  {
    id: nanoid(),
    drafted: false,
    firstName: "Nathaniel",
    lastName: "Dell",
    position: "WR",
    age: 23.3,
    height: 70,
    weight: 165,
    school: "Houston",
    img: "https://media.pff.com/player-photos/nfl/78874.webp",
  },
  {
    id: nanoid(),
    drafted: false,
    firstName: "Daiyan",
    lastName: "Henley",
    position: "LB",
    age: 23.2,
    height: 74,
    weight: 232,
    school: "Washington State",
    img: "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse4.mm.bing.net%2Fth%3Fid%3DOIP.6PQIZ5MzisaZqgCL4-XgTwAAAA%26pid%3DApi&f=1&ipt=0ee7575fcd6b315e5a7d8a00c3e1c95b570de09ebd2742afeffc873ddb9a1b70&ipo=images",
  },
  {
    id: nanoid(),
    drafted: false,
    firstName: "Tyrique",
    lastName: "Stevenson",
    position: "CB",
    age: 22.7,
    height: 72,
    weight: 214,
    school: "Miami",
    img: "https://media.pff.com/player-photos/nfl/97562.webp",
  },
  {
    id: nanoid(),
    drafted: false,
    firstName: "Josh",
    lastName: "Downs",
    position: "WR",
    age: 21.5,
    height: 70,
    weight: 175,
    school: "North Carolina",
    img: "https://media.pff.com/player-photos/nfl/122832.webp",
  },
];
//     {
//         id: nanoid(), 
//         drafted: false,
//         firstName: ,
//         lastName: ,
//         position: ,
//         age: ,
//         height: ,
//         weight: ,
//         school: ,
//         img: ,
//     },
