export const prospects = [
  {
    id: 100000,
    drafted: false,
    rank: 1,
    firstName: "Bryce",
    lastName: "Young",
    position: "QB",
    age: 21.5,
    height: 72,
    weight: 194,
    school: "Alabama",
    img: "https://media.pff.com/player-photos/nfl/123943.webp",
    desc: ["Playmaker", "Accurate"],
    archetype: "Playmaker",
    strengths: ["Accuracy", "Football IQ", "Improvisation", "Poise"],
    weaknesses: ["Size"],
  },
  {
    id: 1,
    drafted: false,
    rank: 3,
    firstName: "Jalen",
    lastName: "Carter",
    position: "DI",
    age: null,
    height: 75,
    weight: 300,
    school: "Georgia",
    img: "https://media.pff.com/player-photos/nfl/124019.webp",
    desc: ["Elite Athlete", "Total Package"],
    archetype: "All-Around",
    strengths: ["Power", "Body Control", "Upside"],
    weaknesses: ["None"],
  },
  {
    id: 2,
    drafted: false,
    rank: 7,
    firstName: "Will",
    lastName: "Levis",
    position: "QB",
    age: 23.6,
    height: 75,
    weight: 232,
    school: "Kentucky",
    img: "https://media.pff.com/player-photos/nfl/83542.webp",
    desc: ["Strong Arm"],
    archetype: "Gunslinger",
    strengths: ["Arm Strength", "Size", "Upside"],
    weaknesses: ["Processsing", "Decision-Making"],
  },
  {
    id: 3,
    drafted: false,
    rank: 2,
    firstName: "Will",
    lastName: "Anderson Jr.",
    position: "ED",
    age: null,
    height: 76,
    weight: 243,
    school: "Alabama",
    img: "https://media.pff.com/player-photos/nfl/123903.webp",
    desc: ["Elite Athlete", "Total Package"],
    archetype: "All-Around",
    strengths: ["Athleticism", "Upside"],
    weaknesses: ["None"],
  },
  {
    id: 4,
    drafted: false,
    rank: 4,
    firstName: "C.J.",
    lastName: "Stroud",
    position: "QB",
    age: 21.3,
    height: 75,
    weight: 215,
    school: "Ohio State",
    img: "https://media.pff.com/player-photos/nfl/129759.webp",
    desc: ["Pocket Passer", "Accurate"],
    archetype: "Pocket Passer",
    strengths: ["Accuracy", "Production"],
    weaknesses: ["Poise under Pressure"],
  },
  {
    id: 5,
    drafted: false,
    rank: 6,
    firstName: "Myles",
    lastName: "Murphy",
    position: "ED",
    age: null,
    height: 77,
    weight: 275,
    school: "Clemson",
    img: "https://media.pff.com/player-photos/nfl/122154.webp",
    desc: ["Elite Athlete", "Project"],
    archetype: "Power Rusher",
    strengths: ["Upside", "Athleticism"],
    weaknesses: ["Raw"],
  },
  {
    id: 6,
    drafted: false,
    rank: 5,
    firstName: "Tyree",
    lastName: "Wilson",
    position: "ED",
    age: null,
    height: 78,
    weight: 275,
    school: "Texas Tech",
    img: "https://thedraftnetwork.com/wp-content/uploads/2022/11/USATSI_18696881_168386526_lowres.png",
    desc: ["Elite Athlete", "Versatile", "Long Arms"],
    archetype: "Power Rusher",
    strengths: ["Size", "Length", "Power"],
    weaknesses: ["Technique"],
  },
  {
    id: 7,
    drafted: false,
    rank: 21,
    firstName: "Bryan",
    lastName: "Bresee",
    position: "DI",
    age: null,
    height: 77,
    weight: 300,
    school: "Clemson",
    img: "https://media.pff.com/player-photos/nfl/122142.webp",
    desc: ["Elite Athlete", "Powerful"],
    archetype: "3 Tech",
    strengths: ["Athleticism", "Power"],
    weaknesses: ["Durability"],
  },
  {
    id: 8,
    drafted: false,
    rank: 11,
    firstName: "Paris",
    lastName: "Johnson Jr.",
    position: "T",
    age: null,
    height: 78,
    weight: 310,
    school: "Ohio State",
    img: "https://media.pff.com/player-photos/nfl/129749.webp",
    desc: ["Elite Athlete", "Project"],
    archetype: "",
    strengths: ["Upside"],
    weaknesses: ["Technique"],
  },
  {
    id: 9,
    drafted: false,
    rank: 17,
    firstName: "Brian",
    lastName: "Branch",
    position: "S",
    age: null,
    height: 72,
    weight: 193,
    school: "Alabama",
    img: "https://media.pff.com/player-photos/nfl/123907.webp",
    desc: ["Slot", "Cerebral", "Good Tackler"],
    archetype: "Box",
    strengths: ["Football IQ", "Run Defense", "Versatility"],
    weaknesses: ["Man Coverage"],
  },
  {
    id: 10,
    drafted: false,
    rank: 14,
    firstName: "Anthony",
    lastName: "Richardson",
    position: "QB",
    age: 21.7,
    height: 76,
    weight: 232,
    school: "Florida",
    img: "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse1.mm.bing.net%2Fth%3Fid%3DOIP.gaXz8ax8M21VkHj4e7ON8AHaFY%26pid%3DApi&f=1&ipt=aa157ec26dc61577c49649a36bff8af365c8d0f2b0b23ba22de29390fe68161d&ipo=images",
    desc: ["Elite Athlete", "Strong Arm", "Project"],
    archetype: "Gunslinger",
    strengths: ["Upside", "Arm Strength", "Athleticism"],
    weaknesses: ["Accuracy", "Raw"],
  },
  {
    id: 11,
    drafted: false,
    rank: 9,
    firstName: "Devon",
    lastName: "Witherspoon",
    position: "CB",
    age: null,
    height: 72,
    weight: 180,
    school: "Illinois",
    img: "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse3.mm.bing.net%2Fth%3Fid%3DOIP.-rWowyXfflk4C4sKIPQYwQHaFY%26pid%3DApi&f=1&ipt=3922e1393dc98f26d6ccbde527ead2c2e9719703f82b647ddf8ec932acf5c541&ipo=images",
    desc: ["Man-to-man", "Feisty", "Playmaker"],
    archetype: "Man-to-man",
    strengths: ["Feisty", "Ball Skills", "Processing Speed"],
    weaknesses: ["Size"],
  },
  {
    id: 12,
    drafted: false,
    rank: 12,
    firstName: "Peter",
    lastName: "Skoronski",
    position: "T",
    age: null,
    height: 76,
    weight: 315,
    school: "Northwestern",
    img: "https://media.pff.com/player-photos/nfl/129737.webp",
    desc: ["Versatile", "Technician", "Short Arms"],
    archetype: "",
    strengths: ["Technique", "Football IQ", "Versatility"],
    weaknesses: ["Arm Length"],
  },
  {
    id: 13,
    drafted: false,
    rank: 8,
    firstName: "Christain",
    lastName: "Gonzalez",
    position: "CB",
    age: null,
    height: 74,
    weight: 201,
    school: "Oregon",
    img: "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse2.mm.bing.net%2Fth%3Fid%3DOIP.k_kFAx_ZLhg5nTRlgeMljAHaFY%26pid%3DApi&f=1&ipt=aa0d31b921b2ece41b5dae2424313c341798329a7c0f74dd59db8ff571aabe75&ipo=images",
    desc: ["Long Arms", "Good Instincts"],
    archetype: "Man-to-man",
    strengths: ["Athleticism", "Length", "Instincts"],
    weaknesses: ["Play Strength"],
  },
  {
    id: 14,
    drafted: false,
    rank: 13,
    firstName: "Quentin",
    lastName: "Johnston",
    position: "WR",
    age: 21.4,
    height: 76,
    weight: 215,
    school: "TCU",
    img: "https://media.pff.com/player-photos/nfl/123085.webp",
    desc: ["Big Bodied", "Explosive"],
    archetype: "X",
    strengths: ["Explosiveness", "Size", "Speed"],
    weaknesses: ["Consistency"],
  },
  {
    id: 15,
    drafted: false,
    rank: 22,
    firstName: "Lukas",
    lastName: "Van Ness",
    position: "ED",
    age: null,
    height: 77,
    weight: 269,
    school: "Iowa",
    img: "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse1.mm.bing.net%2Fth%3Fid%3DOIP.GtpxVP14wxNM849RbKwYcgHaHa%26pid%3DApi&f=1&ipt=685e18c4579d6e88ee3558a783e1cb53923afde106c9405dfd1fc91b19b62ca5&ipo=images",
    desc: ["Power Rusher"],
    archetype: "Power Rusher",
    strengths: ["Strength", "High Motor"],
    weaknesses: ["Inexperience"],
  },
  {
    id: 16,
    drafted: false,
    rank: 18,
    firstName: "Michael",
    lastName: "Mayer",
    position: "TE",
    age: 21.5,
    height: 76,
    weight: 265,
    img: "https://media.pff.com/player-photos/nfl/122906.webp",
    desc: ["Possession", "Good Ball Skills"],
    archetype: "Possession",
    strengths: ["Ball Skills", "Blocking"],
    weaknesses: ["Not Dynamic"],
  },
  {
    id: 17,
    drafted: false,
    rank: 15,
    firstName: "Bijan",
    lastName: "Robinson",
    position: "RB",
    age: 21.0,
    height: 72,
    weight: 220,
    school: "Texas",
    img: "https://media.pff.com/player-photos/nfl/123126.webp",
    desc: ["Elite Athlete", "Total Package"],
    archetype: "Workhorse",
    strengths: ["Explosiveness", "Strength", "Receiving"],
    weaknesses: ["None"],
  },
  {
    id: 18,
    drafted: false,
    rank: 27,
    firstName: "Zay",
    lastName: "Flowers",
    position: "WR",
    age: 22.4,
    height: 70,
    weight: 172,
    school: "Boston College",
    img: "https://media.pff.com/player-photos/nfl/97268.webp",
    desc: ["Slot", "Electric"],
    archetype: "Slot",
    strengths: ["Explosiveness", "Route Running", "YAC"],
    weaknesses: ["Size", "Drops"],
  },
  {
    id: 19,
    drafted: false,
    rank: 20,
    firstName: "Jaxon",
    lastName: "Smith-Njigba",
    position: "WR",
    age: 20.9,
    height: 72,
    weight: 198,
    school: "Ohio State",
    img: "https://media.pff.com/player-photos/nfl/129758.webp",
    desc: ["Route Runner", "Body Control", "Sure-handed"],
    archetype: "Route Runner",
    strengths: ["Route Running", "Hands", "Body Control"],
    weaknesses: ["Not Dynamic"],
  },
  {
    id: 20,
    drafted: false,
    rank: 33,
    firstName: "Anton",
    lastName: "Harrison",
    position: "T",
    age: null,
    height: 77,
    weight: 315,
    school: "Oklahoma",
    img: "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse1.mm.bing.net%2Fth%3Fid%3DOIP.xCBsrlO4lD8WxZJR066WzgHaFY%26pid%3DApi&f=1&ipt=fdb07cfb03945a009f8434c89e50d898fce2513fb853d7c98dc469ffee5cfca0&ipo=images",
    desc: ["Pass Protector", "Strong Hands"],
    archetype: "Pass Protector",
    strengths: ["Pass Blocking", "Length", "Agility"],
    weaknesses: ["Strength"],
  },
  {
    id: 21,
    drafted: false,
    rank: 29,
    firstName: "Nolan",
    lastName: "Smith",
    position: "ED",
    age: null,
    height: 75,
    weight: 235,
    school: "Georgia",
    img: "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse1.mm.bing.net%2Fth%3Fid%3DOIP.YcHt4lLNjRhlTtSZnyQzFgHaFY%26pid%3DApi&f=1&ipt=cc3843e7ebc966a1c481e7f4363bc57e8ae335a0ad3707bb1d527d67c0724d04&ipo=images",
    desc: ["Elite Athlete", "Project"],
    archetype: "Speed Rusher",
    strengths: ["Upside", "Athleticism"],
    weaknesses: ["Raw"],
  },
  {
    id: 22,
    drafted: false,
    rank: 16,
    firstName: "Jordan",
    lastName: "Addison",
    position: "WR",
    age: 21.0,
    height: 72,
    weight: 175,
    school: "USC",
    img: "https://media.pff.com/player-photos/nfl/123000.webp",
    desc: ["Route Runner", "Body Control"],
    archetype: "Route Runner",
    strengths: ["Route Running", "Body Control"],
    weaknesses: ["Size", "Drops"],
  },
  {
    id: 23,
    drafted: false,
    rank: 19,
    firstName: "Broderick",
    lastName: "Jones",
    position: "T",
    age: null,
    height: 76,
    weight: 310,
    school: "Georgia",
    img: "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse3.mm.bing.net%2Fth%3Fid%3DOIP.EcCH5xj7B192vsZxhLvbqAHaFY%26pid%3DApi&f=1&ipt=c671f175caae1cfae4750d6bbc5e41d6e0e591c3ba2673083d20f3e79080222a&ipo=images",
    desc: [],
    archetype: "",
    strengths: ["Athleticism", "Upside"],
    weaknesses: ["Inconsistency"],
  },
  {
    id: 24,
    drafted: false,
    rank: 23,
    firstName: "Cam",
    lastName: "Smith",
    position: "CB",
    age: null,
    height: 72,
    weight: 188,
    school: "South Carolina",
    img: "https://media.pff.com/player-photos/nfl/98837.webp",
    archetype: "Slot",
    strengths: ["Ball Skills", "Physicality"],
    weaknesses: ["Tackling"],
  },
  {
    id: 25,
    drafted: false,
    rank: 10,
    firstName: "Joey",
    lastName: "Porter Jr.",
    position: "CB",
    age: null,
    height: 74,
    weight: 198,
    school: "Penn State",
    img: "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse4.mm.bing.net%2Fth%3Fid%3DOIP.6LeeWLro2y1qf7t0VuOMKAHaFY%26pid%3DApi&f=1&ipt=1baaa67efdace80f6b13d8158a0034f686e0983f50321df38a944cad30e4598a&ipo=images",
    archetype: "Man-to-man",
    strengths: ["Press", "Ball Skills"],
    weaknesses: ["Grabbiness"],
  },
  {
    id: 26,
    drafted: false,
    rank: 24,
    firstName: "O'Cyrus",
    lastName: "Torrence",
    position: "G",
    age: null,
    height: 77,
    weight: 347,
    school: "Florida",
    img: "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse4.mm.bing.net%2Fth%3Fid%3DOIP.VQKs5AoSHjbg9oDPg6kVzAAAAA%26pid%3DApi&f=1&ipt=e23daf20a9c1dc783278d3170043986063ca224d9e429fe084dd5c40c20e07ca&ipo=images",
    archetype: "Run Blocker",
    strengths: ["Physicality", "Run Blocking", "Anchor"],
    weaknesses: ["Lateral Agility"],
  },
  {
    id: 27,
    drafted: false,
    rank: 86,
    firstName: "Tanner",
    lastName: "McKee",
    position: "QB",
    age: 22.7,
    height: 78,
    weight: 230,
    school: "Stanford",
    img: "https://media.pff.com/player-photos/nfl/131770.webp",
    archetype: "Pocket Passer",
    strengths: ["Arm Strength", "Accuracy"],
    weaknesses: ["Pocket Awareness", "Playmaking"],
  },
  {
    id: 28,
    drafted: false,
    rank: 28,
    firstName: "Trenton",
    lastName: "Simpson",
    position: "LB",
    age: null,
    height: 75,
    weight: 230,
    school: "Clemson",
    img: "https://media.pff.com/player-photos/nfl/122157.webp",
    archetype: "WLB",
    strengths: ["Explosiveness"],
    weaknesses: ["Run Defense"],
  },
  {
    id: 29,
    drafted: false,
    rank: 40,
    firstName: "Luke",
    lastName: "Musgrave",
    position: "TE",
    age: 22.4,
    height: 78,
    weight: 250,
    school: "Oregon State",
    img: "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse1.mm.bing.net%2Fth%3Fid%3DOIP.MLTA2khYaL-C8CnbmtDg-AHaHa%26pid%3DApi&f=1&ipt=589fb7702bff6080d69d1a76240e441121fe30227bfb78e7a17539dfe57c6db6&ipo=images",
    archetype: "Vertical Threat",
    strengths: ["Athleticism", "Upside"],
    weaknesses: ["Route Running"],
  },
  {
    id: 30,
    drafted: false,
    rank: 45,
    firstName: "Siaki",
    lastName: "Ika",
    position: "DI",
    age: null,
    height: 76,
    weight: 358,
    school: "Baylor",
    img: "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse1.mm.bing.net%2Fth%3Fid%3DOIP.Wh4Ov64e5xpgWQO9hKacnwHaFY%26pid%3DApi&f=1&ipt=e561230bf33e11ba647a904fb93cf8e4cb57a2830c0c363c9cd3120693daab20&ipo=images",
    archetype: "Nose Tackle",
    strengths: ["Strength"],
    weaknesses: ["Weight"],
  },
  {
    id: 31,
    drafted: false,
    rank: 38,
    firstName: "BJ",
    lastName: "Ojulari",
    position: "ED",
    age: null,
    height: 75,
    weight: 250,
    school: "LSU",
    img: "https://media.pff.com/player-photos/nfl/124105.webp",
    archetype: "Pure Pass Rusher",
    strengths: ["Pass Rush Plan"],
    weaknesses: ["Strength"],
  },
  {
    id: 32,
    drafted: false,
    rank: 64,
    firstName: "Andre",
    lastName: "Carter II",
    position: "ED",
    age: null,
    height: 79,
    weight: 260,
    school: "Army",
    img: "https://media.pff.com/player-photos/nfl/102780.webp",
    archetype: "",
    strengths: ["Size"],
    weaknesses: ["Muscle Mass", "Flexibility"],
  },
  {
    id: 33,
    drafted: false,
    rank: 31,
    firstName: "Dalton",
    lastName: "Kincaid",
    position: "TE",
    age: 23.3,
    height: 76,
    weight: 240,
    school: "Utah",
    img: "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse2.explicit.bing.net%2Fth%3Fid%3DOIP.paNOE-T8E-cm5X3WQn2akAHaFY%26pid%3DApi&f=1&ipt=b516e2b0231386c6c34a761cdd4d0c8d2973a404bcae8c4a5de8b280e15ac08a&ipo=images",
    archetype: "Vertical Threat",
    strengths: ["Ball Skills", "Body Control", "Hands", "Route Running"],
    weaknesses: ["Blocking"],
  },
  {
    id: 34,
    drafted: false,
    rank: 39,
    firstName: "Calijah",
    lastName: "Kancey",
    position: "DI",
    age: 21.9,
    height: 72,
    weight: 280,
    school: "Pittsburgh",
    img: "https://media.pff.com/player-photos/nfl/99822.webp",
    archetype: "3 Tech",
    strengths: ["Twitch", "Pass Rushing", "Motor"],
    weaknesses: ["Size"],
  },
  {
    id: 35,
    drafted: false,
    rank: 35,
    firstName: "Deonte",
    lastName: "Banks",
    position: "CB",
    age: null,
    height: 74,
    weight: 205,
    school: "Maryland",
    img: "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse1.mm.bing.net%2Fth%3Fid%3DOIP.OPpaC_z4XihbqiV_k4ExYgAAAA%26pid%3DApi&f=1&ipt=d4fbf4ff4826671680fb7761b3efe906be9cf5ed75e297d9eb20d917cb7f41e7&ipo=images",
    archetype: "Versatile",
    strengths: ["Length", "Sticky Coverage"],
    weaknesses: ["Technique"],
  },
  {
    id: 36,
    drafted: false,
    rank: 51,
    firstName: "Will",
    lastName: "McDonald IV",
    position: "ED",
    age: 23.7,
    height: 75,
    weight: 236,
    school: "Iowa State",
    img: "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fwww.ourlads.com%2Fimages%2Fplayers%2Fncaa%2FMCD222153.png&f=1&nofb=1&ipt=14e6db2f907974f8160087e19a0f86277413dd750e9bfc63264f19b774363d5d&ipo=images",
    archetype: "Speed Rusher",
    strengths: ["Explosiveness", "Length"],
    weaknesses: ["Strength"],
  },
  {
    id: 37,
    drafted: false,
    rank: 36,
    firstName: "Antonio",
    lastName: "Johnson",
    position: "S",
    age: 21.3,
    height: 75,
    weight: 195,
    school: "Texas A&M",
    img: "https://media.pff.com/player-photos/nfl/124326.webp",
    archetype: "Box",
    strengths: ["Processing", "Tackling"],
    weaknesses: ["Ball Skills"],
  },
  {
    id: 38,
    drafted: false,
    rank: 54,
    firstName: "Mazi",
    lastName: "Smith",
    position: "DI",
    age: 21.6,
    height: 75,
    weight: 337,
    school: "Michigan",
    img: "https://media.pff.com/player-photos/nfl/101419.webp",
    archetype: "Nose Tackle",
    strengths: ["Run Defense", "Strength"],
    weaknesses: ["Hand Usage"],
  },
  {
    id: 39,
    drafted: false,
    rank: 85,
    firstName: "Nathaniel",
    lastName: "Dell",
    position: "WR",
    age: 23.3,
    height: 70,
    weight: 165,
    school: "Houston",
    img: "https://media.pff.com/player-photos/nfl/78874.webp",
    archetype: "Slot/Gadget",
    strengths: ["Shiftiness", "YAC"],
    weaknesses: ["Size"],
  },
  {
    id: 40,
    drafted: false,
    rank: 69,
    firstName: "Daiyan",
    lastName: "Henley",
    position: "LB",
    age: 23.2,
    height: 74,
    weight: 232,
    school: "Washington State",
    img: "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse4.mm.bing.net%2Fth%3Fid%3DOIP.6PQIZ5MzisaZqgCL4-XgTwAAAA%26pid%3DApi&f=1&ipt=0ee7575fcd6b315e5a7d8a00c3e1c95b570de09ebd2742afeffc873ddb9a1b70&ipo=images",
    archetype: "WLB",
    strengths: ["Twitchiness"],
    weaknesses: ["Zone Coverage"],
  },
  {
    id: 41,
    drafted: false,
    rank: 57,
    firstName: "Tyrique",
    lastName: "Stevenson",
    position: "CB",
    age: 22.7,
    height: 72,
    weight: 214,
    school: "Miami",
    img: "https://media.pff.com/player-photos/nfl/97562.webp",
    archetype: "Man-to-man",
    strengths: ["Length", "Balance"],
    weaknesses: ["Tackling"],
  },
  {
    id: 42,
    drafted: false,
    rank: 46,
    firstName: "Josh",
    lastName: "Downs",
    position: "WR",
    age: 21.5,
    height: 70,
    weight: 175,
    school: "North Carolina",
    img: "https://media.pff.com/player-photos/nfl/122832.webp",
    archetype: "Slot",
    strengths: ["Footwork", "Explosiveness", "YAC"],
    weaknesses: ["Size"],
  },
  {
    id: 43,
    drafted: false,
    rank: 26,
    firstName: "Jalin",
    lastName: "Hyatt",
    position: "WR",
    age: 21.4,
    height: 73,
    weight: 180,
    school: "Tennessee",
    img: "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fs3media.247sports.com%2FUploads%2FAssets%2F216%2F929%2F9929216.jpeg%3Ffit%3Dcrop%26width%3D100&f=1&nofb=1&ipt=3b09d9e56360d6d7246a15355ce6b124aa8d974eb864968cf1955dccac0ff615&ipo=images",
    archetype: "Deep Threat",
    strengths: ["Speed"],
    weaknesses: ["Route Running", "Defeating Press"],
  },
  {
    id: 44,
    drafted: false,
    rank: 30,
    firstName: "Jahmyr",
    lastName: "Gibbs",
    position: "RB",
    age: 20.9,
    height: 71,
    weight: 200,
    school: "Alabama",
    img: "https://media.pff.com/player-photos/nfl/122474.webp",
    archetype: "Receiving Back",
    strengths: ["Shiftiness", "Explosiveness", "Pass Catching"],
    weaknesses: ["Size"],
  },
  {
    id: 45,
    drafted: false,
    rank: 25,
    firstName: "Kelee",
    lastName: "Ringo",
    position: "CB",
    age: 20.6,
    height: 74,
    weight: 210,
    school: "Georgia",
    img: "https://media.pff.com/player-photos/nfl/124035.webp",
    archetype: "Zone",
    strengths: ["Size", "Speed"],
    weaknesses: ["Fluidity", "Anticipation"],
  },
  {
    id: 46,
    drafted: false,
    rank: 32,
    firstName: "Drew",
    lastName: "Sanders",
    position: "LB",
    age: 21.1,
    height: 77,
    weight: 232,
    school: "Arkansas",
    img: "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse3.mm.bing.net%2Fth%3Fid%3DOIP.JW_cciyE5bDbZ2PXiYTJcgHaFY%26pid%3DApi&f=1&ipt=1955e1420dbeec266f45a9e94fbc0c11cfb8c5d677e810a8bfee7f82b2d5ec6e&ipo=images",
    archetype: "MLB",
    strengths: ["Blitzing"],
    weaknesses: ["Tackling"],
  },
  {
    id: 47,
    drafted: false,
    rank: 34,
    firstName: "Emmanuel",
    lastName: "Forbes",
    position: "CB",
    age: 22.1,
    height: 72,
    weight: 180,
    school: "Mississippi State",
    img: "https://media.pff.com/player-photos/nfl/124166.webp",
    archetype: "Versatile",
    strengths: ["Ball Skills", "Instincts"],
    weaknesses: ["Muscle Mass", "Overly Aggressive"],
  },
  {
    id: 48,
    drafted: false,
    rank: 37,
    firstName: "Darnell",
    lastName: "Washington",
    position: "TE",
    age: 21.5,
    height: 79,
    weight: 270,
    school: "Georgia",
    img: "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse4.mm.bing.net%2Fth%3Fid%3DOIP.cSbZpzOfbWPeh0m6yEROKgHaFY%26pid%3DApi&f=1&ipt=d918ea528bcde22a9b2b59bf62c4791e2baa596b9608b935a901766861092cd6&ipo=images",
    archetype: "Blocking",
    strengths: ["Size", "Blocking"],
    weaknesses: ["Separation"],
  },
  {
    id: 49,
    drafted: false,
    rank: 42,
    firstName: "Isaiah",
    lastName: "Foskey",
    position: "ED",
    age: 22.3,
    height: 77,
    weight: 265,
    school: "Notre Dame",
    img: "https://media.pff.com/player-photos/nfl/102728.webp",
    archetype: "Pure Pass Rusher",
    strengths: ["Explosiveness", "Pass Rush Plan"],
    weaknesses: ["Run Defense"],
  },
  {
    id: 50,
    drafted: false,
    rank: 44,
    firstName: "Dawand",
    lastName: "Jones",
    position: "T",
    age: 21.5,
    height: 80,
    weight: 350,
    school: "Ohio State",
    img: "https://media.pff.com/player-photos/nfl/101550.webp",
    archetype: "Run Blocker",
    strengths: ["LENGTH", "Strength"],
    weaknesses: ["Agility"],
  },
];
