export const teams = [
  {
    city: "Arizona",
    teamName: "Cardinals",
    abr: "ARI",
    logo: "https://content.sportslogos.net/logos/7/177/thumbs/kwth8f1cfa2sch5xhjjfaof90.gif",
    picks: [3],
    needs: ["G", "ED", "CB"],
  },
  {
    city: "Atlanta",
    teamName: "Falcons",
    abr: "ATL",
    logo: "https://content.sportslogos.net/logos/7/173/thumbs/299.gif",
    picks: [8],
    needs: ["QB", "WR", "ED", "LB", "RB"],
  },
  {
    city: "Baltimore",
    teamName: "Ravens",
    abr: "BAL",
    logo: "https://content.sportslogos.net/logos/7/153/thumbs/318.gif",
    picks: [22],
    needs: ["WR", "ED", "CB"],
  },
  {
    city: "Buffalo",
    teamName: "Bills",
    abr: "BUF",
    logo: "https://content.sportslogos.net/logos/7/149/thumbs/n0fd1z6xmhigb0eej3323ebwq.gif",
    picks: [27],
    needs: ["G", "C", "CB", "S", "WR", "RB"],
  },
  {
    city: "Carolina",
    teamName: "Panthers",
    abr: "CAR",
    logo: "https://content.sportslogos.net/logos/7/174/thumbs/f1wggq2k8ql88fe33jzhw641u.gif",
    picks: [9],
    needs: ["QB", "RB", "TE", "ED"],
  },
  {
    city: "Chicago",
    teamName: "Bears",
    abr: "CHI",
    logo: "https://content.sportslogos.net/logos/7/169/thumbs/364.gif",
    picks: [1],
    needs: ["WR", "TE", "T", "G", "C", "ED", "DI", "LB", "CB", "S"],
  },
  {
    city: "Cincinnati",
    teamName: "Bengals",
    abr: "CIN",
    logo: "https://content.sportslogos.net/logos/7/154/thumbs/15420492021.gif",
    picks: [28],
    needs: ["T", "DI", "CB"],
  },
  {
    city: "Cleveland",
    teamName: "Browns",
    abr: "CLE",
    logo: "https://content.sportslogos.net/logos/7/155/thumbs/15578552015.gif",
    picks: [],
    needs: ["WR", "DI", "S"],
  },
  {
    city: "Dallas",
    teamName: "Cowboys",
    abr: "DAL",
    logo: "https://content.sportslogos.net/logos/7/165/thumbs/406.gif",
    picks: [26],
    needs: ["WR", "DI", "LB", "RB"],
  },
  {
    city: "Denver",
    teamName: "Broncos",
    abr: "DEN",
    logo: "https://content.sportslogos.net/logos/7/161/thumbs/9ebzja2zfeigaziee8y605aqp.gif",
    picks: [],
    needs: ["T", "DI", "LB"],
  },
  {
    city: "Detroit",
    teamName: "Lions",
    abr: "DET",
    logo: "https://content.sportslogos.net/logos/7/170/thumbs/17013982017.gif",
    picks: [6, 18],
    needs: ["DI", "LB", "CB", "RB"],
  },
  {
    city: "Green Bay",
    teamName: "Packers",
    abr: "GB",
    logo: "https://content.sportslogos.net/logos/7/171/thumbs/dcy03myfhffbki5d7il3.gif",
    picks: [15],
    needs: ["WR", "TE", "ED", "S"],
  },
  {
    city: "Houston",
    teamName: "Texans",
    abr: "HOU",
    logo: "https://content.sportslogos.net/logos/7/157/thumbs/570.gif",
    picks: [2, 12],
    needs: ["QB", "G", "C", "ED", "DI"],
  },
  {
    city: "Indianapolis",
    teamName: "Colts",
    abr: "IND",
    logo: "https://content.sportslogos.net/logos/7/158/thumbs/593.gif",
    picks: [4],
    needs: ["QB", "T", "G", "C"],
  },
  {
    city: "Jacksonville",
    teamName: "Jaguars",
    abr: "JAX",
    logo: "https://content.sportslogos.net/logos/7/159/thumbs/15988562013.gif",
    picks: [24],
    needs: ["G", "C", "CB", "S"],
  },
  {
    city: "Kansas City",
    teamName: "Chiefs",
    abr: "KC",
    logo: "https://content.sportslogos.net/logos/7/162/thumbs/857.gif",
    picks: [31],
    needs: ["WR", "DI", "ED"],
  },
  {
    city: "Las Vegas",
    teamName: "Raiders",
    abr: "LV",
    logo: "https://content.sportslogos.net/logos/7/6708/thumbs/670885212020.gif",
    picks: [7],
    needs: ["QB", "T", "G", "C", "CB", "S"],
  },
  {
    city: "Los Angeles",
    teamName: "Chargers",
    abr: "LAC",
    logo: "https://content.sportslogos.net/logos/7/6446/thumbs/644616602020.gif",
    picks: [21],
    needs: ["WR", "T", "LB", "CB"],
  },
  {
    city: "Los Angeles",
    teamName: "Rams",
    abr: "LAR",
    logo: "https://content.sportslogos.net/logos/7/5941/thumbs/594183342020.gif",
    picks: [],
    needs: ["T", "G", "C", "ED", "S"],
  },
  {
    city: "Miami",
    teamName: "Dolphins",
    abr: "MIA",
    logo: "https://content.sportslogos.net/logos/7/150/thumbs/15073062018.gif",
    picks: [],
    needs: ["T", "G", "C", "CB"],
  },
  {
    city: "Minnesota",
    teamName: "Vikings",
    abr: "MIN",
    logo: "https://content.sportslogos.net/logos/7/172/thumbs/17227042013.gif",
    picks: [23],
    needs: ["DI", "LB", "CB", "WR"],
  },
  {
    city: "New England",
    teamName: "Patriots",
    abr: "NE",
    logo: "https://content.sportslogos.net/logos/7/151/thumbs/y71myf8mlwlk8lbgagh3fd5e0.gif",
    picks: [14],
    needs: ["QB", "T", "ED"],
  },
  {
    city: "New Orleans",
    teamName: "Saints",
    abr: "NO",
    logo: "https://content.sportslogos.net/logos/7/175/thumbs/907.gif",
    picks: [29],
    needs: ["QB", "DI", "CB"],
  },
  {
    city: "New York",
    teamName: "Giants",
    abr: "NYG",
    logo: "https://content.sportslogos.net/logos/7/166/thumbs/919.gif",
    picks: [25],
    needs: ["WR", "TE", "C", "LB"],
  },
  {
    city: "New York",
    teamName: "Jets",
    abr: "NYJ",
    logo: "https://content.sportslogos.net/logos/7/152/thumbs/15291162019.gif",
    picks: [13],
    needs: ["QB", "T", "LB"],
  },
  {
    city: "Philadelphia",
    teamName: "Eagles",
    abr: "PHI",
    logo: "https://content.sportslogos.net/logos/7/167/thumbs/960.gif",
    picks: [10, 30],
    needs: ["G", "C", "WR", "DI", "ED", "T", "RB"],
  },
  {
    city: "Pittsburgh",
    teamName: "Steelers",
    abr: "PIT",
    logo: "https://content.sportslogos.net/logos/7/156/thumbs/970.gif",
    picks: [17],
    needs: ["T", "LB", "CB"],
  },
  {
    city: "San Francisco",
    teamName: "49ers",
    abr: "SF",
    logo: "https://content.sportslogos.net/logos/7/179/thumbs/17994552009.gif",
    picks: [],
    needs: ["G", "C", "DI", "CB"],
  },
  {
    city: "Seattle",
    teamName: "Seahawks",
    abr: "SEA",
    logo: "https://content.sportslogos.net/logos/7/180/thumbs/pfiobtreaq7j0pzvadktsc6jv.gif",
    picks: [5, 20],
    needs: ["G", "C", "ED", "DI"],
  },
  {
    city: "Tampa Bay",
    teamName: "Buccaneers",
    abr: "TB",
    logo: "https://content.sportslogos.net/logos/7/176/thumbs/17683632020.gif",
    picks: [19],
    needs: ["QB", "TE", "G", "C", "DI"],
  },
  {
    city: "Tennessee",
    teamName: "Titans",
    abr: "TEN",
    logo: "https://content.sportslogos.net/logos/7/160/thumbs/1053.gif",
    picks: [11],
    needs: ["WR", "T", "ED"],
  },
  {
    city: "Washington",
    teamName: "Commanders",
    abr: "WAS",
    logo: "https://content.sportslogos.net/logos/7/6832/thumbs/683260482022.gif",
    picks: [16],
    needs: ["QB", "T", "G", "C", "CB", "LB"],
  },
];
